import { makeStyles, tokens } from '@fluentui/react-components';

export const useKitchenStyles = makeStyles({
  container: {
    padding: '28px 32px',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    backgroundColor: tokens.colorNeutralBackground2,
    overflowY: 'auto',
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '20px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
  },
  activeOrdersChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    paddingTop: '6px',
    paddingBottom: '6px',
    paddingLeft: '14px',
    paddingRight: '14px',
    borderRadius: '9999px',
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderRightWidth: '1px',
    borderTopStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1,
    borderRightColor: tokens.colorNeutralStroke1,
    boxShadow: tokens.shadow2,
    userSelect: 'none',
    boxSizing: 'border-box',
    height: '36px',
    transitionProperty: 'all',
    transitionDuration: '0.2s',
    transitionTimingFunction: 'ease',
  },
  chipDotActive: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#E51937',
    boxShadow: '0 0 8px rgba(229, 25, 55, 0.8)',
    animationName: {
      '0%': { transform: 'scale(0.95)', opacity: '0.8' },
      '50%': { transform: 'scale(1.2)', opacity: '1' },
      '100%': { transform: 'scale(0.95)', opacity: '0.8' },
    },
    animationDuration: '2s',
    animationIterationCount: 'infinite',
    flexShrink: 0,
  },
  chipDotClear: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#10B981',
    boxShadow: '0 0 8px rgba(16, 185, 129, 0.5)',
    flexShrink: 0,
  },
  chipCount: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: '13px',
  },
  chipLabel: {
    color: tokens.colorNeutralForeground2,
    fontSize: '13px',
    fontWeight: 500,
  },
  filterBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
  },
  ticketGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '18px',
  },
  ticketCard: {
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: '12px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    boxShadow: tokens.shadow4,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    transition: 'transform 0.15s ease, box-shadow 0.15s ease',
    ':hover': {
      boxShadow: tokens.shadow8,
      transform: 'translateY(-2px)',
    },
  },
  ticketHeader: {
    padding: '14px 18px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  itemList: {
    padding: '16px 18px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    flex: 1,
  },
  itemRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 10px',
    backgroundColor: tokens.colorNeutralBackground3,
    borderRadius: '8px',
  },
  cardFooter: {
    padding: '12px 18px',
    backgroundColor: tokens.colorNeutralBackground3,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 0',
    gap: '12px',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginBottom: '14px',
  },
  errorMessage: {
    color: tokens.colorPaletteRedForeground1,
    fontSize: '12px',
    fontWeight: 500,
  },
  pageTitle: {
    fontWeight: 700,
    fontSize: '20px',
    color: tokens.colorNeutralForeground1,
    margin: 0,
    display: 'block',
  },
  pageSubtitle: {
    color: tokens.colorNeutralForeground2,
    marginTop: '4px',
    marginBottom: 0,
    display: 'block',
    fontSize: '13px',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  timerIconActive: {
    fontSize: '18px',
    width: '18px',
    height: '18px',
    color: '#E51937',
  },
  timerIconClear: {
    fontSize: '18px',
    width: '18px',
    height: '18px',
    color: tokens.colorNeutralForeground2,
  },
  dialogSurface: {
    maxWidth: '580px',
    width: '94vw',
    padding: '24px',
    borderRadius: '16px',
  },
  dialogTitle: {
    fontWeight: 800,
    fontSize: '20px',
    margin: 0,
    paddingBottom: '12px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  dialogContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    marginTop: '16px',
  },
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '14px',
    marginTop: '4px',
  },
  foodSectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '4px',
  },
  foodSectionTitle: {
    fontWeight: 700,
    fontSize: '14px',
    color: tokens.colorNeutralForeground1,
  },
  addItemBtn: {
    color: '#E51937',
    fontWeight: 700,
    padding: '4px 10px',
  },
  foodListScroll: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    maxHeight: '320px',
    overflowY: 'auto',
    paddingRight: '4px',
  },
  foodItemCard: {
    padding: '14px 16px',
    borderRadius: '12px',
    backgroundColor: tokens.colorNeutralBackground3,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  foodItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemBadge: {
    fontSize: '11px',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    color: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    border: '1px solid rgba(229, 25, 55, 0.25)',
    padding: '2px 8px',
    borderRadius: '6px',
  },
  deleteIcon: {
    color: '#EF4444',
  },
  removeItemBtn: {
    minWidth: 'auto',
    padding: '4px 8px',
  },
  foodItemRowInputs: {
    display: 'grid',
    gridTemplateColumns: '130px 1fr',
    gap: '12px',
  },
  addAnotherBtn: {
    borderTopStyle: 'dashed', borderBottomStyle: 'dashed', borderLeftStyle: 'dashed', borderRightStyle: 'dashed',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    fontWeight: 700,
    justifyContent: 'center',
    borderRadius: '10px',
    padding: '10px',
  },
  dialogActions: {
    marginTop: '24px',
    display: 'flex',
    gap: '10px',
    justifyContent: 'flex-end',
  },
  cancelBtn: {
    borderRadius: '8px',
    fontWeight: 600,
    padding: '8px 18px',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    whiteSpace: 'nowrap',
  },
  sendTicketBtn: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: '8px',
    fontWeight: 700,
    padding: '9px 22px',
    minWidth: '140px',
    whiteSpace: 'nowrap',
    border: 'none',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.25)',
  },
  emptyIcon: {
    width: '56px',
    height: '56px',
    opacity: 0.35,
    color: tokens.colorNeutralForeground3,
  },
  emptyTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
    display: 'block',
    fontSize: '16px',
  },
  emptySubtext: {
    color: tokens.colorNeutralForeground3,
  },
  ticketHeaderReady: {
    backgroundColor: 'rgba(16, 124, 65, 0.08)',
  },
  ticketHeaderCooking: {
    backgroundColor: 'rgba(245, 158, 11, 0.08)',
  },
  ticketHeaderDefault: {
    backgroundColor: tokens.colorNeutralBackground1,
  },
  ticketMetaCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  ticketTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  ticketTitle: {
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  timeUrgent: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#EF4444',
  },
  timeWarning: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#F59E0B',
  },
  timeGood: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#10B981',
  },
  ticketTimeSub: {
    color: tokens.colorNeutralForeground2,
    display: 'block',
    fontSize: '12px',
  },
  itemName: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    display: 'block',
  },
  itemVariant: {
    color: tokens.colorNeutralForeground2,
    display: 'block',
    fontSize: '12px',
  },
  itemNotes: {
    color: '#D97706',
    fontStyle: 'italic',
    display: 'block',
    fontSize: '12px',
  },
  footerActionsLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  refText: {
    color: tokens.colorNeutralForeground3,
    fontSize: '11px',
  },
  footerActionsRight: {
    display: 'flex',
    gap: '8px',
  },
  btnStartCooking: {
    backgroundColor: '#E51937',
    borderRadius: '6px',
  },
  btnMarkReady: {
    backgroundColor: '#107C41',
    borderTopColor: '#107C41', borderBottomColor: '#107C41', borderLeftColor: '#107C41', borderRightColor: '#107C41',
    borderRadius: '6px',
  },
  btnMarkServed: {
    borderRadius: '6px',
  },
  timeChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
  },
  timerSmallIcon: {
    width: '13px',
    height: '13px',
  },
});


export const useStyles = useKitchenStyles;
