import { makeStyles, tokens } from '@fluentui/react-components';

export const useFastFoodDashboardStyles = makeStyles({
  root: {
    paddingTop: '24px',
    paddingBottom: '24px',
    paddingLeft: '32px',
    paddingRight: '32px',
    minHeight: '100%',
    boxSizing: 'border-box',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    display: 'flex',
    flexDirection: 'column',
    rowGap: '24px',
    overflowY: 'auto',
  },
  rootDark: {
    backgroundColor: '#0D0E11',
    color: '#FFFFFF',
  },
  rootLight: {
    backgroundColor: '#F8FAFC',
    color: '#0F172A',
  },

  // Header & Module Tabs
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    columnGap: '16px',
    rowGap: '16px',
    paddingBottom: '16px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
  },
  headerDark: {
    borderBottomColor: 'rgba(255, 255, 255, 0.07)',
  },
  headerLight: {
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
  },
  headerTitleRow: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '10px',
  },
  headerTitle: {
    margin: 0,
    fontSize: '24px',
    fontWeight: 900,
    letterSpacing: '-0.02em',
  },
  liveBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '6px',
    paddingTop: '3px',
    paddingBottom: '3px',
    paddingLeft: '10px',
    paddingRight: '10px',
    borderRadius: '20px',
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(16, 185, 129, 0.3)',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: 'rgba(16, 185, 129, 0.3)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(16, 185, 129, 0.3)',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: 'rgba(16, 185, 129, 0.3)',
    color: '#10B981',
    fontSize: '11px',
    fontWeight: 800,
  },
  liveBadgeDot: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: '#10B981',
    boxShadow: '0 0 8px #10B981',
  },
  headerSub: {
    marginTop: '4px',
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    fontSize: '13px',
  },
  headerSubDark: {
    color: '#94A3B8',
  },
  headerSubLight: {
    color: '#64748B',
  },
  headerRightActions: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '12px',
  },
  tabSwitcher: {
    display: 'flex',
    paddingTop: '4px',
    paddingBottom: '4px',
    paddingLeft: '4px',
    paddingRight: '4px',
    borderRadius: '10px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
  },
  tabSwitcherDark: {
    backgroundColor: '#1C1F26',
    borderTopColor: 'rgba(255, 255, 255, 0.07)',
    borderRightColor: 'rgba(255, 255, 255, 0.07)',
    borderBottomColor: 'rgba(255, 255, 255, 0.07)',
    borderLeftColor: 'rgba(255, 255, 255, 0.07)',
  },
  tabSwitcherLight: {
    backgroundColor: '#E2E8F0',
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
    borderRightColor: 'rgba(0, 0, 0, 0.08)',
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    borderLeftColor: 'rgba(0, 0, 0, 0.08)',
  },
  tabBtn: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '8px',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '18px',
    paddingRight: '18px',
    borderRadius: '7px',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    fontWeight: 800,
    fontSize: '13px',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    cursor: 'pointer',
    transitionProperty: 'all',
    transitionDuration: '0.2s',
    transitionTimingFunction: 'ease',
  },
  tabBtnFastFoodActive: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    boxShadow: '0 4px 14px rgba(229, 25, 55, 0.35)',
  },
  tabBtnMiniMartActive: {
    backgroundColor: '#2563EB',
    color: '#FFFFFF',
    boxShadow: '0 4px 14px rgba(37, 99, 235, 0.4)',
  },
  tabBtnInactiveDark: {
    backgroundColor: 'transparent',
    color: '#94A3B8',
  },
  tabBtnInactiveLight: {
    backgroundColor: 'transparent',
    color: '#64748B',
  },
  tabCountBadge: {
    fontSize: '10px',
    paddingTop: '1px',
    paddingBottom: '1px',
    paddingLeft: '6px',
    paddingRight: '6px',
    borderRadius: '10px',
    fontWeight: 800,
  },
  tabCountBadgeActive: {
    backgroundColor: 'rgba(255,255,255,0.25)',
    color: '#FFFFFF',
  },
  tabCountBadgeInactiveDark: {
    backgroundColor: '#2D3139',
    color: '#FFFFFF',
  },
  tabCountBadgeInactiveLight: {
    backgroundColor: '#CBD5E1',
    color: '#0F172A',
  },
  singleModuleBadge: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '8px',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '16px',
    paddingRight: '16px',
    borderRadius: '8px',
    fontWeight: 800,
    fontSize: '13px',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
  },
  singleModuleBadgeFastFood: {
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.25)',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: 'rgba(229, 25, 55, 0.25)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(229, 25, 55, 0.25)',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: 'rgba(229, 25, 55, 0.25)',
    color: '#E51937',
  },
  singleModuleBadgeMiniMart: {
    backgroundColor: 'rgba(37, 99, 235, 0.1)',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(37, 99, 235, 0.25)',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: 'rgba(37, 99, 235, 0.25)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(37, 99, 235, 0.25)',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: 'rgba(37, 99, 235, 0.25)',
    color: '#2563EB',
  },
  dateFilterGroup: {
    display: 'flex',
    paddingTop: '3px',
    paddingBottom: '3px',
    paddingLeft: '3px',
    paddingRight: '3px',
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
  },
  dateFilterGroupDark: {
    backgroundColor: '#14161B',
    borderTopColor: 'rgba(255, 255, 255, 0.07)',
    borderRightColor: 'rgba(255, 255, 255, 0.07)',
    borderBottomColor: 'rgba(255, 255, 255, 0.07)',
    borderLeftColor: 'rgba(255, 255, 255, 0.07)',
  },
  dateFilterGroupLight: {
    backgroundColor: '#FFFFFF',
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
    borderRightColor: 'rgba(0, 0, 0, 0.08)',
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    borderLeftColor: 'rgba(0, 0, 0, 0.08)',
  },
  dateBtn: {
    paddingTop: '6px',
    paddingBottom: '6px',
    paddingLeft: '12px',
    paddingRight: '12px',
    borderRadius: '6px',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    fontSize: '11.5px',
    fontWeight: 700,
    cursor: 'pointer',
    textTransform: 'capitalize',
  },
  dateBtnActiveDark: {
    backgroundColor: '#27272A',
    color: '#FFFFFF',
  },
  dateBtnActiveLight: {
    backgroundColor: '#E2E8F0',
    color: '#0F172A',
  },
  dateBtnInactiveDark: {
    backgroundColor: 'transparent',
    color: '#64748B',
  },
  dateBtnInactiveLight: {
    backgroundColor: 'transparent',
    color: '#94A3B8',
  },
  refreshBtn: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  refreshBtnDark: {
    backgroundColor: '#14161B',
    borderTopColor: 'rgba(255, 255, 255, 0.07)',
    borderRightColor: 'rgba(255, 255, 255, 0.07)',
    borderBottomColor: 'rgba(255, 255, 255, 0.07)',
    borderLeftColor: 'rgba(255, 255, 255, 0.07)',
    color: '#94A3B8',
  },
  refreshBtnLight: {
    backgroundColor: '#FFFFFF',
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
    borderRightColor: 'rgba(0, 0, 0, 0.08)',
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    borderLeftColor: 'rgba(0, 0, 0, 0.08)',
    color: '#64748B',
  },

  // KPI Metrics Grid & Cards
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    columnGap: '16px',
    rowGap: '16px',
  },
  kpiCard: {
    borderRadius: '12px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    paddingTop: '20px',
    paddingBottom: '20px',
    paddingLeft: '20px',
    paddingRight: '20px',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.15)',
  },
  cardDark: {
    backgroundColor: '#14161B',
    borderTopColor: 'rgba(255, 255, 255, 0.07)',
    borderRightColor: 'rgba(255, 255, 255, 0.07)',
    borderBottomColor: 'rgba(255, 255, 255, 0.07)',
    borderLeftColor: 'rgba(255, 255, 255, 0.07)',
  },
  cardLight: {
    backgroundColor: '#FFFFFF',
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
    borderRightColor: 'rgba(0, 0, 0, 0.08)',
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    borderLeftColor: 'rgba(0, 0, 0, 0.08)',
  },
  laserRed: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '3px',
    backgroundColor: '#E51937',
    boxShadow: '0 0 10px #E51937',
  },
  laserBlue: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '3px',
    backgroundColor: '#3B82F6',
    boxShadow: '0 0 10px #3B82F6',
  },
  laserAmber: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '3px',
    backgroundColor: '#F59E0B',
    boxShadow: '0 0 10px #F59E0B',
  },
  laserGreen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '3px',
    backgroundColor: '#10B981',
    boxShadow: '0 0 10px #10B981',
  },
  kpiHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  kpiTitle: {
    fontSize: '12px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  kpiIconRed: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#E51937',
  },
  kpiIconBlue: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#3B82F6',
  },
  kpiIconAmber: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#F59E0B',
  },
  kpiIconGreen: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#10B981',
  },
  kpiValue: {
    fontSize: '28px',
    fontWeight: 900,
    marginTop: '12px',
    letterSpacing: '-0.02em',
  },
  kpiUnit: {
    fontSize: '14px',
    fontWeight: 600,
  },
  kpiTrendRow: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '6px',
    marginTop: '8px',
    fontSize: '11.5px',
  },
  kpiDotRow: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '8px',
    marginTop: '8px',
    fontSize: '11.5px',
  },
  trendGreen: {
    color: '#10B981',
    fontWeight: 800,
  },
  trendAmber: {
    color: '#F59E0B',
    fontWeight: 800,
  },
  dotGreen: {
    color: '#10B981',
    fontWeight: 700,
  },
  dotAmber: {
    color: '#F59E0B',
    fontWeight: 700,
  },

  // Main Charts Row
  chartsGrid: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    columnGap: '20px',
    rowGap: '20px',
  },
  columnChartCard: {
    borderRadius: '14px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    paddingTop: '22px',
    paddingBottom: '22px',
    paddingLeft: '22px',
    paddingRight: '22px',
    display: 'flex',
    flexDirection: 'column',
    rowGap: '16px',
    position: 'relative',
  },
  chartHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    columnGap: '12px',
    rowGap: '12px',
    fontFamily: "'Plus Jakarta Sans', sans-serif",
  },
  chartTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '8px',
  },
  chartTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 800,
    fontFamily: 'inherit',
  },
  telemetryTag: {
    fontSize: '11px',
    fontWeight: 800,
    paddingTop: '2px',
    paddingBottom: '2px',
    paddingLeft: '8px',
    paddingRight: '8px',
    borderRadius: '4px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    color: '#E51937',
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '4px',
  },
  chartSub: {
    marginTop: '4px',
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    fontSize: '12px',
  },
  peakTagsRow: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '6px',
  },
  peakTagLunchDark: {
    fontSize: '11px',
    paddingTop: '4px',
    paddingBottom: '4px',
    paddingLeft: '8px',
    paddingRight: '8px',
    borderRadius: '6px',
    backgroundColor: '#27272A',
    color: '#F59E0B',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '4px',
  },
  peakTagLunchLight: {
    fontSize: '11px',
    paddingTop: '4px',
    paddingBottom: '4px',
    paddingLeft: '8px',
    paddingRight: '8px',
    borderRadius: '6px',
    backgroundColor: '#F1F5F9',
    color: '#F59E0B',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '4px',
  },
  peakTagDinnerDark: {
    fontSize: '11px',
    paddingTop: '4px',
    paddingBottom: '4px',
    paddingLeft: '8px',
    paddingRight: '8px',
    borderRadius: '6px',
    backgroundColor: '#27272A',
    color: '#E51937',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '4px',
  },
  peakTagDinnerLight: {
    fontSize: '11px',
    paddingTop: '4px',
    paddingBottom: '4px',
    paddingLeft: '8px',
    paddingRight: '8px',
    borderRadius: '6px',
    backgroundColor: '#F1F5F9',
    color: '#E51937',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '4px',
  },
  chartSvgWrap: {
    position: 'relative',
    width: '100%',
    overflow: 'hidden',
  },
  chartSvg: {
    width: '100%',
    height: '240px',
    display: 'block',
  },
  columnGroup: {
    cursor: 'pointer',
  },
  columnTrack: {
    transitionProperty: 'fill',
    transitionDuration: '0.15s',
    transitionTimingFunction: 'ease',
  },
  columnBar: {
    transitionProperty: 'all',
    transitionDuration: '0.15s',
    transitionTimingFunction: 'ease',
  },
  currentHourDot: {
    filter: 'drop-shadow(0 0 4px #10B981)',
  },

  // Tooltip
  chartTooltip: {
    position: 'absolute',
    top: '10px',
    paddingTop: '10px',
    paddingBottom: '10px',
    paddingLeft: '14px',
    paddingRight: '14px',
    borderRadius: '10px',
    borderTopWidth: '1.5px',
    borderTopStyle: 'solid',
    borderRightWidth: '1.5px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1.5px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1.5px',
    borderLeftStyle: 'solid',
    pointerEvents: 'none',
    zIndex: 20,
    minWidth: '150px',
  },
  chartTooltipDark: {
    backgroundColor: 'rgba(20, 22, 27, 0.96)',
    backdropFilter: 'blur(14px)',
    boxShadow: '0 10px 28px rgba(0,0,0,0.45), 0 0 14px rgba(229, 25, 55, 0.35)',
  },
  chartTooltipLight: {
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    backdropFilter: 'blur(14px)',
    boxShadow: '0 10px 28px rgba(0,0,0,0.15), 0 0 14px rgba(229, 25, 55, 0.25)',
  },
  tooltipBorderPeak: {
    borderTopColor: '#E51937',
    borderRightColor: '#E51937',
    borderBottomColor: '#E51937',
    borderLeftColor: '#E51937',
  },
  tooltipBorderNormal: {
    borderTopColor: 'rgba(255,255,255,0.18)',
    borderRightColor: 'rgba(255,255,255,0.18)',
    borderBottomColor: 'rgba(255,255,255,0.18)',
    borderLeftColor: 'rgba(255,255,255,0.18)',
  },
  tooltipHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    columnGap: '6px',
  },
  tooltipLabel: {
    fontSize: '11px',
    fontWeight: 800,
  },
  tooltipPeakTagDinner: {
    fontSize: '10px',
    fontWeight: 800,
    color: '#E51937',
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '3px',
  },
  tooltipPeakTagLunch: {
    fontSize: '10px',
    fontWeight: 800,
    color: '#F59E0B',
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '3px',
  },
  tooltipOrders: {
    fontSize: '17px',
    fontWeight: 900,
    marginTop: '3px',
  },
  tooltipSalesRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '4px',
    fontSize: '11.5px',
  },
  tooltipAvgRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '2px',
    fontSize: '11px',
  },

  // Donut Ring Card
  donutCard: {
    borderRadius: '14px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    paddingTop: '22px',
    paddingBottom: '22px',
    paddingLeft: '22px',
    paddingRight: '22px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  donutSvgWrap: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '14px',
    marginBottom: '14px',
  },
  donutSvg: {
    transform: 'rotate(-90deg)',
  },
  donutSegmentDineIn: {
    filter: 'drop-shadow(0 0 8px rgba(229, 25, 55, 0.35))',
  },
  donutCenter: {
    position: 'absolute',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  donutCenterCount: {
    fontSize: '24px',
    fontWeight: 900,
    lineHeight: 1,
  },
  donutCenterLabel: {
    fontSize: '11px',
    fontWeight: 700,
    marginTop: '2px',
  },
  donutLegendList: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '8px',
  },
  donutLegendRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '12px',
  },
  donutLegendLeft: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '8px',
  },
  donutLegendDotRed: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: '#E51937',
    boxShadow: '0 0 6px #E51937',
  },
  donutLegendDotAmber: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: '#F59E0B',
    boxShadow: '0 0 6px #F59E0B',
  },
  donutLegendDotGreen: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: '#10B981',
    boxShadow: '0 0 6px #10B981',
  },
  donutLegendRight: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '6px',
  },

  // Lower Section: Live Kitchen & Top Sellers
  lowerGrid: {
    display: 'grid',
    gridTemplateColumns: '1.2fr 1fr',
    columnGap: '20px',
    rowGap: '20px',
  },
  kitchenCard: {
    borderRadius: '14px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    paddingTop: '22px',
    paddingBottom: '22px',
    paddingLeft: '22px',
    paddingRight: '22px',
    display: 'flex',
    flexDirection: 'column',
    rowGap: '16px',
  },
  kitchenHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  kitchenTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '8px',
  },
  kitchenTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 800,
  },
  kitchenInKitchenBadge: {
    fontSize: '11px',
    fontWeight: 800,
    paddingTop: '2px',
    paddingBottom: '2px',
    paddingLeft: '8px',
    paddingRight: '8px',
    borderRadius: '10px',
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    color: '#F59E0B',
  },
  openKitchenBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '5px',
    paddingTop: '6px',
    paddingBottom: '6px',
    paddingLeft: '12px',
    paddingRight: '12px',
    borderRadius: '6px',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    fontSize: '12px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  openKitchenBtnDark: {
    backgroundColor: '#27272A',
    color: '#FFFFFF',
  },
  openKitchenBtnLight: {
    backgroundColor: '#F1F5F9',
    color: '#0F172A',
  },
  pipelineStagesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    columnGap: '12px',
    rowGap: '12px',
  },
  stageCard: {
    borderRadius: '10px',
    paddingTop: '12px',
    paddingBottom: '12px',
    paddingLeft: '12px',
    paddingRight: '12px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
  },
  stageCard1Dark: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderTopColor: 'rgba(255, 255, 255, 0.07)',
    borderRightColor: 'rgba(255, 255, 255, 0.07)',
    borderBottomColor: 'rgba(255, 255, 255, 0.07)',
    borderLeftColor: 'rgba(255, 255, 255, 0.07)',
  },
  stageCard1Light: {
    backgroundColor: '#F8FAFC',
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
    borderRightColor: 'rgba(0, 0, 0, 0.08)',
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    borderLeftColor: 'rgba(0, 0, 0, 0.08)',
  },
  stageCard2Dark: {
    backgroundColor: 'rgba(245, 158, 11, 0.05)',
    borderTopColor: 'rgba(245, 158, 11, 0.25)',
    borderRightColor: 'rgba(245, 158, 11, 0.25)',
    borderBottomColor: 'rgba(245, 158, 11, 0.25)',
    borderLeftColor: 'rgba(245, 158, 11, 0.25)',
  },
  stageCard2Light: {
    backgroundColor: '#FFFBEB',
    borderTopColor: 'rgba(245, 158, 11, 0.25)',
    borderRightColor: 'rgba(245, 158, 11, 0.25)',
    borderBottomColor: 'rgba(245, 158, 11, 0.25)',
    borderLeftColor: 'rgba(245, 158, 11, 0.25)',
  },
  stageCard3Dark: {
    backgroundColor: 'rgba(16, 185, 129, 0.05)',
    borderTopColor: 'rgba(16, 185, 129, 0.25)',
    borderRightColor: 'rgba(16, 185, 129, 0.25)',
    borderBottomColor: 'rgba(16, 185, 129, 0.25)',
    borderLeftColor: 'rgba(16, 185, 129, 0.25)',
  },
  stageCard3Light: {
    backgroundColor: '#F0FDF4',
    borderTopColor: 'rgba(16, 185, 129, 0.25)',
    borderRightColor: 'rgba(16, 185, 129, 0.25)',
    borderBottomColor: 'rgba(16, 185, 129, 0.25)',
    borderLeftColor: 'rgba(16, 185, 129, 0.25)',
  },
  stageHeader: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '6px',
    fontSize: '12px',
    fontWeight: 800,
  },
  stageHeaderBlue: {
    color: '#3B82F6',
  },
  stageHeaderAmber: {
    color: '#F59E0B',
  },
  stageHeaderGreen: {
    color: '#10B981',
  },
  stageDotBlue: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: '#3B82F6',
  },
  stageDotAmber: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: '#F59E0B',
  },
  stageDotGreen: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: '#10B981',
  },
  stageCount: {
    fontSize: '20px',
    fontWeight: 900,
    marginTop: '8px',
  },
  stageCountAmber: {
    color: '#F59E0B',
  },
  stageCountGreen: {
    color: '#10B981',
  },
  stageSub: {
    fontSize: '11px',
  },
  noticeBanner: {
    marginTop: '4px',
    paddingTop: '12px',
    paddingBottom: '12px',
    paddingLeft: '14px',
    paddingRight: '14px',
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  noticeBannerDark: {
    backgroundColor: 'rgba(229, 25, 55, 0.06)',
    borderTopColor: 'rgba(229, 25, 55, 0.2)',
    borderRightColor: 'rgba(229, 25, 55, 0.2)',
    borderBottomColor: 'rgba(229, 25, 55, 0.2)',
    borderLeftColor: 'rgba(229, 25, 55, 0.2)',
  },
  noticeBannerLight: {
    backgroundColor: '#FFF1F2',
    borderTopColor: 'rgba(229, 25, 55, 0.2)',
    borderRightColor: 'rgba(229, 25, 55, 0.2)',
    borderBottomColor: 'rgba(229, 25, 55, 0.2)',
    borderLeftColor: 'rgba(229, 25, 55, 0.2)',
  },
  noticeLeft: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '8px',
  },
  noticeIcon: {
    color: '#E51937',
    width: '18px',
    height: '18px',
  },
  noticeTitle: {
    fontSize: '12px',
    fontWeight: 800,
  },
  noticeSub: {
    fontSize: '11px',
  },
  restockBtn: {
    paddingTop: '5px',
    paddingBottom: '5px',
    paddingLeft: '10px',
    paddingRight: '10px',
    borderRadius: '5px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: '#E51937',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: '#E51937',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#E51937',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: '#E51937',
    backgroundColor: 'transparent',
    color: '#E51937',
    fontSize: '11px',
    fontWeight: 800,
    cursor: 'pointer',
  },

  // Leaderboard
  leaderboardCard: {
    borderRadius: '14px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    paddingTop: '22px',
    paddingBottom: '22px',
    paddingLeft: '22px',
    paddingRight: '22px',
    display: 'flex',
    flexDirection: 'column',
    rowGap: '14px',
  },
  leaderboardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leaderboardTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: 800,
  },
  leaderboardSub: {
    marginTop: '2px',
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    fontSize: '12px',
  },
  openPosBtn: {
    paddingTop: '6px',
    paddingBottom: '6px',
    paddingLeft: '12px',
    paddingRight: '12px',
    borderRadius: '6px',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    fontSize: '11.5px',
    fontWeight: 800,
    cursor: 'pointer',
  },
  rankedList: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '10px',
  },
  rankedItem: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: '4px',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '10px',
    paddingRight: '10px',
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
  },
  rankedItemDark: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderTopColor: 'rgba(255, 255, 255, 0.07)',
    borderRightColor: 'rgba(255, 255, 255, 0.07)',
    borderBottomColor: 'rgba(255, 255, 255, 0.07)',
    borderLeftColor: 'rgba(255, 255, 255, 0.07)',
  },
  rankedItemLight: {
    backgroundColor: '#F8FAFC',
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
    borderRightColor: 'rgba(0, 0, 0, 0.08)',
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    borderLeftColor: 'rgba(0, 0, 0, 0.08)',
  },
  rankedItemRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rankedItemLeft: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '8px',
  },
  rankBadge: {
    fontSize: '11px',
    fontWeight: 800,
    minWidth: '22px',
    display: 'inline-flex',
    alignItems: 'center',
    columnGap: '2px',
  },
  rankGold: {
    color: '#F59E0B',
  },
  rankSilver: {
    color: '#94A3B8',
  },
  rankBronze: {
    color: '#B45309',
  },
  rankedItemImg: {
    width: '26px',
    height: '26px',
    borderRadius: '5px',
    objectFit: 'cover',
  },
  rankedItemName: {
    fontSize: '12.5px',
    fontWeight: 800,
  },
  rankedItemRight: {
    display: 'flex',
    alignItems: 'baseline',
    columnGap: '6px',
  },
  rankedItemQty: {
    fontSize: '12px',
    fontWeight: 800,
  },
  rankedItemRev: {
    fontSize: '11px',
    color: '#10B981',
    fontWeight: 700,
  },
  meterTrack: {
    width: '100%',
    height: '4px',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  meterTrackDark: {
    backgroundColor: '#27272A',
  },
  meterTrackLight: {
    backgroundColor: '#E2E8F0',
  },
  meterBar: {
    height: '100%',
    borderRadius: '2px',
    transitionProperty: 'width',
    transitionDuration: '0.4s',
    transitionTimingFunction: 'ease',
  },
  meterBarRed: {
    backgroundColor: '#E51937',
  },
  meterBarAmber: {
    backgroundColor: '#F59E0B',
  },
  meterBarBlue: {
    backgroundColor: '#3B82F6',
  },

  // Modal
  modalOverlay: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    backdropFilter: 'blur(6px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    paddingTop: '20px',
    paddingBottom: '20px',
    paddingLeft: '20px',
    paddingRight: '20px',
  },
  modalContent: {
    borderRadius: '14px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    width: '100%',
    maxWidth: '560px',
    maxHeight: '80vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 20px 50px rgba(0, 0, 0, 0.5)',
    overflow: 'hidden',
  },
  modalHeader: {
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingLeft: '20px',
    paddingRight: '20px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalHeaderDark: {
    borderBottomColor: 'rgba(255, 255, 255, 0.07)',
  },
  modalHeaderLight: {
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
  },
  modalTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    columnGap: '8px',
  },
  modalTitle: {
    margin: 0,
    fontSize: '17px',
    fontWeight: 800,
  },
  currentHourPill: {
    fontSize: '10px',
    paddingTop: '2px',
    paddingBottom: '2px',
    paddingLeft: '6px',
    paddingRight: '6px',
    borderRadius: '10px',
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    fontWeight: 800,
  },
  modalSub: {
    fontSize: '12px',
    marginTop: '2px',
  },
  closeBtn: {
    background: 'none',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    cursor: 'pointer',
    paddingTop: '4px',
    paddingBottom: '4px',
    paddingLeft: '4px',
    paddingRight: '4px',
  },
  modalBody: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    overflowY: 'auto',
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingLeft: '20px',
    paddingRight: '20px',
    display: 'flex',
    flexDirection: 'column',
    rowGap: '10px',
  },
  emptyOrders: {
    textAlign: 'center',
    paddingTop: '30px',
    paddingBottom: '30px',
    fontSize: '13px',
  },
  orderTicket: {
    paddingTop: '12px',
    paddingBottom: '12px',
    paddingLeft: '14px',
    paddingRight: '14px',
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    display: 'flex',
    flexDirection: 'column',
    rowGap: '6px',
  },
  orderTicketDark: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderTopColor: 'rgba(255, 255, 255, 0.07)',
    borderRightColor: 'rgba(255, 255, 255, 0.07)',
    borderBottomColor: 'rgba(255, 255, 255, 0.07)',
    borderLeftColor: 'rgba(255, 255, 255, 0.07)',
  },
  orderTicketLight: {
    backgroundColor: '#F8FAFC',
    borderTopColor: 'rgba(0, 0, 0, 0.08)',
    borderRightColor: 'rgba(0, 0, 0, 0.08)',
    borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    borderLeftColor: 'rgba(0, 0, 0, 0.08)',
  },
  orderTicketHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderTicketId: {
    fontSize: '12px',
    fontWeight: 800,
  },
  orderTypeTag: {
    fontSize: '11px',
    textTransform: 'uppercase',
    paddingTop: '1px',
    paddingBottom: '1px',
    paddingLeft: '6px',
    paddingRight: '6px',
    borderRadius: '4px',
    fontWeight: 700,
  },
  orderTypeTagDark: {
    backgroundColor: '#27272A',
    color: '#94A3B8',
  },
  orderTypeTagLight: {
    backgroundColor: '#E2E8F0',
    color: '#64748B',
  },
  tokenTag: {
    fontSize: '11px',
    color: '#F59E0B',
    fontWeight: 800,
  },
  ticketTime: {
    fontSize: '11.5px',
  },
  ticketTotal: {
    fontSize: '13px',
    fontWeight: 900,
    color: '#10B981',
  },
  ticketItems: {
    fontSize: '11.5px',
  },

  // Generic helpers
  icon12: { width: '12px', height: '12px' },
  icon13: { width: '13px', height: '13px' },
  icon14: { width: '14px', height: '14px' },
  icon16: { width: '16px', height: '16px' },
  icon18: { width: '18px', height: '18px' },
  icon20: { width: '20px', height: '20px' },
  colorRed: { color: '#E51937' },
  colorGreen: { color: '#10B981' },
  colorAmber: { color: '#F59E0B' },
  colorBlue: { color: '#3B82F6' },
  textMutedDark: { color: '#64748B' },
  textMutedLight: { color: '#94A3B8' },
  textSecondaryDark: { color: '#94A3B8' },
  textSecondaryLight: { color: '#64748B' },
  textPrimaryDark: { color: '#FFFFFF' },
  textPrimaryLight: { color: '#0F172A' },
  fw800: { fontWeight: 800 },
  fw700: { fontWeight: 700 },
  fw900: { fontWeight: 900 },
});
