import { makeStyles, tokens } from '@fluentui/react-components';

export const useAddProductStyles = makeStyles({
  container: {
    padding: '20px 24px',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    backgroundColor: tokens.colorNeutralBackground2,
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '16px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  headerBackBtn: {
    borderRadius: '8px',
  },
  headerTitle: {
    fontWeight: 800,
    fontSize: '20px',
    color: tokens.colorNeutralForeground1,
    margin: 0,
  },
  headerSubtitle: {
    color: tokens.colorNeutralForeground2,
    marginTop: '2px',
    display: 'block',
  },
  headerActions: {
    display: 'flex',
    gap: '10px',
  },
  btnCancel: {
    borderRadius: '8px',
    fontWeight: 600,
  },
  btnPrimarySave: {
    backgroundColor: '#E51937',
    color: '#ffffff',
    borderRadius: '8px',
    fontWeight: 600,
    ':hover': {
      backgroundColor: '#be123c',
    },
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 340px',
    gap: '24px',
    alignItems: 'stretch',
  },
  cardSurface: {
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: tokens.borderRadiusMedium,
    boxShadow: tokens.shadow4,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
  },
  cardSurfaceRight: {
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: tokens.borderRadiusMedium,
    boxShadow: tokens.shadow4,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
    height: '100%',
    boxSizing: 'border-box',
  },
  twoColGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
  },
  threeColGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '16px',
  },
  fieldLabel: {
    fontWeight: 600,
    display: 'block',
    marginBottom: '6px',
  },
  fieldHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '6px',
  },
  linkBtn: {
    background: 'none',
    border: 'none',
    color: '#E51937',
    fontSize: '11px',
    fontWeight: 700,
    cursor: 'pointer',
    padding: '0 2px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '2px',
  },
  newCategoryLink: {
    fontSize: '12px',
    color: '#E51937',
    fontWeight: 700,
    cursor: 'pointer',
  },
  fullWidth: {
    width: '100%',
  },
  errorCaption: {
    color: tokens.colorPaletteRedForeground1,
    marginTop: '4px',
    display: 'block',
  },
  descTextarea: {
    width: '100%',
    minHeight: '70px',
  },

  // Presets Bar
  presetsBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 14px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground3,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    marginTop: '2px',
    marginBottom: '6px',
  },
  presetsTitle: {
    fontSize: '11.5px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
    whiteSpace: 'nowrap',
  },
  presetsWrap: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  presetChip: {
    fontSize: '11px',
    padding: '4px 10px',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },

  // Pricing Type Section
  pricingTypeSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginTop: '4px',
    marginBottom: '6px',
  },
  pricingTypeLabel: {
    fontSize: '12px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  pricingTypeRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    alignItems: 'center',
  },
  pricingTypeBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '7px',
    padding: '7px 14px',
    borderRadius: '8px',
    fontSize: '12.5px',
    fontWeight: 600,
    cursor: 'pointer',
    boxSizing: 'border-box',
    border: `1.5px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground2,
    outline: 'none',
    transition: 'background-color 0.15s ease, border-color 0.15s ease, color 0.15s ease, box-shadow 0.15s ease',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground3,
      color: tokens.colorNeutralForeground1,
    },
  },
  pricingTypeBtnActive: {
    backgroundColor: '#E51937',
    color: '#FFFFFF !important',
    fontWeight: 700,
    borderTopColor: '#E51937',
    borderBottomColor: '#E51937',
    borderLeftColor: '#E51937',
    borderRightColor: '#E51937',
    borderTopWidth: '1.5px',
    borderBottomWidth: '1.5px',
    borderLeftWidth: '1.5px',
    borderRightWidth: '1.5px',
    borderTopStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderRightStyle: 'solid',
    boxShadow: '0 2px 10px rgba(229, 25, 55, 0.35)',
    ':hover': {
      backgroundColor: '#be123c',
      color: '#FFFFFF !important',
    },
  },
  pricingTypeDesc: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
    fontWeight: 500,
    marginTop: '2px',
  },

  // Variants Section
  variantSectionBox: {
    padding: '16px',
    borderRadius: '10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  variantHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  variantHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  variantProfileTag: {
    fontSize: '10px',
    fontWeight: 800,
    padding: '2px 7px',
    borderRadius: '4px',
  },
  variantHeaderLabel: {
    fontWeight: 700,
    fontSize: '13.5px',
  },
  variantCustomBtn: {
    fontSize: '11.5px',
    fontWeight: 600,
  },
  variantChipsCaption: {
    color: tokens.colorNeutralForeground3,
    display: 'block',
    marginBottom: '6px',
  },
  variantChipsWrap: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  variantChipBtn: {
    padding: '4px 12px',
    borderRadius: '6px',
    fontSize: '12px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    transition: 'all 0.15s ease',
  },
  variantTableContainer: {
    marginTop: '4px',
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    paddingTop: '10px',
  },
  variantTableHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  variantTableCaption: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
  },
  variantColumnHeaderRow: {
    display: 'grid',
    gridTemplateColumns: '85px 95px 120px 1fr 32px',
    gap: '8px',
    alignItems: 'center',
    padding: '4px 8px',
    fontSize: '11px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
    marginBottom: '2px',
  },
  variantRowsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  variantRowItem: {
    display: 'grid',
    gridTemplateColumns: '85px 95px 120px 1fr 32px',
    gap: '8px',
    alignItems: 'center',
    padding: '6px 8px',
    borderRadius: '6px',
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  variantRowLabel: {
    fontWeight: 800,
    fontSize: '12.5px',
  },
  variantDeleteBtn: {
    color: '#D13438',
  },

  // Media / Right Column
  mediaHeaderTitle: {
    fontWeight: 700,
    fontSize: '13.5px',
    color: tokens.colorNeutralForeground1,
    marginBottom: '4px',
  },
  mediaHeaderSubtitle: {
    color: tokens.colorNeutralForeground2,
    display: 'block',
    marginBottom: '10px',
  },
  imageDropzone: {
    border: `2px dashed ${tokens.colorNeutralStroke1}`,
    borderRadius: '8px',
    padding: '16px',
    textAlign: 'center',
    backgroundColor: tokens.colorNeutralBackground2,
    cursor: 'pointer',
    position: 'relative',
  },
  imageDropzoneIcon: {
    width: '28px',
    height: '28px',
    color: tokens.colorNeutralForeground3,
    margin: '0 auto 6px',
  },
  imageDropzoneText: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#E51937',
  },
  imageDropzoneCaption: {
    color: tokens.colorNeutralForeground3,
    fontSize: '11px',
  },
  urlInputContainer: {
    marginTop: '10px',
  },
  previewSection: {
    borderTop: `1px solid ${tokens.colorNeutralStroke1}`,
    paddingTop: '14px',
  },
  previewTitle: {
    fontSize: '11.5px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
    textTransform: 'uppercase',
    marginBottom: '8px',
  },
  previewCard: {
    width: '100%',
    height: '190px',
    borderRadius: '8px',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: tokens.shadow4,
  },
  previewImageWrap: {
    height: '114px',
    width: '100%',
    position: 'relative',
    backgroundColor: tokens.colorNeutralBackground3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  previewNoPhotoBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    color: tokens.colorNeutralForeground4,
  },
  previewBadge: {
    position: 'absolute',
    top: '6px',
    right: '6px',
    padding: '2px 6px',
    borderRadius: '4px',
    backgroundColor: 'rgba(0,0,0,0.65)',
    color: '#ffffff',
    fontSize: '10px',
    fontWeight: 700,
  },
  previewDetailsWrap: {
    height: '76px',
    padding: '6px 10px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  previewProductTitle: {
    fontSize: '12px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  previewVariantsRow: {
    display: 'flex',
    gap: '3px',
    marginTop: '2px',
    overflow: 'hidden',
  },
  previewVariantBadge: {
    fontSize: '8.5px',
    fontWeight: 800,
    padding: '0 4px',
    borderRadius: '3px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    color: '#E51937',
    border: '1px solid rgba(229, 25, 55, 0.25)',
  },
  previewMoreVariantsText: {
    fontSize: '8.5px',
    color: tokens.colorNeutralForeground3,
  },
  previewCategoryText: {
    fontSize: '10.5px',
    color: tokens.colorNeutralForeground3,
  },
  previewBottomRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  previewPriceText: {
    fontSize: '13px',
    fontWeight: 800,
    color: '#E51937',
  },
  previewModuleText: {
    fontSize: '10.5px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
  },
  proTipBox: {
    marginTop: 'auto',
    padding: '12px 14px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground3,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  proTipTitle: {
    fontSize: '11px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  proTipCaption: {
    color: tokens.colorNeutralForeground3,
    fontSize: '11px',
    lineHeight: '1.4',
  },

  // Modal Dialog
  dialogSurface: {
    maxWidth: '460px',
    width: '92vw',
    borderRadius: '16px',
    padding: '24px',
    boxSizing: 'border-box',
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    boxShadow: '0 24px 64px rgba(0, 0, 0, 0.5)',
    display: 'flex',
    flexDirection: 'column',
  },
  dialogForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
    width: '100%',
  },
  dialogHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '14px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    width: '100%',
  },
  dialogHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  dialogIconBox: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#E51937',
  },
  dialogTitleText: {
    fontSize: '17px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  dialogSubtitleText: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  dialogFieldsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: '100%',
  },
  dialogActionsRow: {
    display: 'flex',
    gap: '10px',
    justifyContent: 'flex-end',
    marginTop: '6px',
    paddingTop: '14px',
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    width: '100%',
  },
  dialogCancelBtn: {
    borderRadius: '8px',
    fontWeight: 600,
  },
  dialogSaveBtn: {
    backgroundColor: '#E51937',
    color: '#ffffff',
    borderRadius: '8px',
    fontWeight: 700,
    padding: '0 20px',
    ':hover': {
      backgroundColor: '#be123c',
    },
  },

  /* ── Layout & Typography Helpers ── */
  colEnd: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
  },
  flexEndRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginBottom: '6px',
  },
  requiredStar: {
    color: '#E51937',
    fontWeight: 800,
  },
  flexShrink0: {
    flexShrink: 0,
  },
  hiddenInput: {
    display: 'none',
  },
  noPhotoIcon: {
    width: '28px',
    height: '28px',
  },
  noPhotoText: {
    fontSize: '11px',
  },
  tag20Icon: {
    width: '20px',
    height: '20px',
  },
  strongForeground: {
    color: tokens.colorNeutralForeground1,
  },

  /* ── Industry Profile Classes ── */
  presetChipSelectedFood: {
    fontWeight: 800,
    borderTopWidth: '1.5px', borderBottomWidth: '1.5px', borderLeftWidth: '1.5px', borderRightWidth: '1.5px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#E51937', borderBottomColor: '#E51937', borderLeftColor: '#E51937', borderRightColor: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.15)',
    color: '#E51937',
  },
  presetChipSelectedApparel: {
    fontWeight: 800,
    borderTopWidth: '1.5px', borderBottomWidth: '1.5px', borderLeftWidth: '1.5px', borderRightWidth: '1.5px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#8b5cf6', borderBottomColor: '#8b5cf6', borderLeftColor: '#8b5cf6', borderRightColor: '#8b5cf6',
    backgroundColor: 'rgba(139, 92, 246, 0.15)',
    color: '#8b5cf6',
  },
  presetChipSelectedFootwear: {
    fontWeight: 800,
    borderTopWidth: '1.5px', borderBottomWidth: '1.5px', borderLeftWidth: '1.5px', borderRightWidth: '1.5px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#3b82f6', borderBottomColor: '#3b82f6', borderLeftColor: '#3b82f6', borderRightColor: '#3b82f6',
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    color: '#3b82f6',
  },
  presetChipSelectedHardware: {
    fontWeight: 800,
    borderTopWidth: '1.5px', borderBottomWidth: '1.5px', borderLeftWidth: '1.5px', borderRightWidth: '1.5px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#f59e0b', borderBottomColor: '#f59e0b', borderLeftColor: '#f59e0b', borderRightColor: '#f59e0b',
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    color: '#f59e0b',
  },
  presetChipSelectedStandard: {
    fontWeight: 800,
    borderTopWidth: '1.5px', borderBottomWidth: '1.5px', borderLeftWidth: '1.5px', borderRightWidth: '1.5px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#64748b', borderBottomColor: '#64748b', borderLeftColor: '#64748b', borderRightColor: '#64748b',
    backgroundColor: 'rgba(100, 116, 139, 0.15)',
    color: '#64748b',
  },
  variantSectionActiveFood: {
    borderTopColor: 'rgba(229, 25, 55, 0.3)', borderBottomColor: 'rgba(229, 25, 55, 0.3)', borderLeftColor: 'rgba(229, 25, 55, 0.3)', borderRightColor: 'rgba(229, 25, 55, 0.3)',
    backgroundColor: 'rgba(229, 25, 55, 0.04)',
  },
  variantSectionActiveApparel: {
    borderTopColor: 'rgba(139, 92, 246, 0.3)', borderBottomColor: 'rgba(139, 92, 246, 0.3)', borderLeftColor: 'rgba(139, 92, 246, 0.3)', borderRightColor: 'rgba(139, 92, 246, 0.3)',
    backgroundColor: 'rgba(139, 92, 246, 0.04)',
  },
  variantSectionActiveFootwear: {
    borderTopColor: 'rgba(59, 130, 246, 0.3)', borderBottomColor: 'rgba(59, 130, 246, 0.3)', borderLeftColor: 'rgba(59, 130, 246, 0.3)', borderRightColor: 'rgba(59, 130, 246, 0.3)',
    backgroundColor: 'rgba(59, 130, 246, 0.04)',
  },
  apStyle_1: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  apStyle_2: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    backgroundColor: tokens.colorNeutralBackground1,
    padding: '16px 20px',
    borderRadius: tokens.borderRadiusMedium,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    boxShadow: tokens.shadow2,
  },
  apStyle_3: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8px',
  },
  apStyle_4: {
    fontSize: '11px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  apStyle_5: {
    margin: '3px 0 0 0',
    fontSize: '13px',
    color: tokens.colorNeutralForeground1,
    fontWeight: 600,
  },
  apStyle_6: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  apStyle_8: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '12px',
  },
  apStyle_11: {
    width: '24px',
    height: '24px',
  },
  apStyle_12: {
    flex: 1,
  },
  apStyle_13: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  apStyle_15: {
    color: '#E51937',
    width: '18px',
    height: '18px',
  },
  apStyle_16: {
    display: 'block',
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground3,
    marginTop: '2px',
  },
  apStyle_20: {
    color: '#0284C7',
    width: '18px',
    height: '18px',
  },
  apStyle_21: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '12px 16px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke2,
  },
  apStyle_22: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  apStyle_23: {
    width: '20px',
    height: '20px',
  },
  apStyle_24: {
    fontWeight: 700,
    fontSize: '13.5px',
    color: tokens.colorNeutralForeground1,
  },
  apStyle_25: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: '#0284C7',
    color: '#FFFFFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  apStyle_27: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '8px',
    flexWrap: 'wrap',
    gap: '6px',
  },
  apStyle_28: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  apStyle_29: {
    fontSize: '12px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  apStyle_30: {
    fontSize: '11px',
    fontWeight: 500,
    color: tokens.colorNeutralForeground3,
  },
  apStyle_31: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#E51937',
    background: 'none',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    cursor: 'pointer',
    textDecoration: 'underline',
  },
  apStyle_32: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  apStyle_36: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  apStyle_37: {
    marginBottom: 0,
  },
  apStyle_42: {
    marginTop: '16px',
  },
  apStyle_43: {
    fontSize: '13px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    marginBottom: '8px',
  },
  apStyle_44: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '12px',
  },
  apStyle_45: {
    display: 'block',
    fontSize: '12px',
    fontWeight: 600,
    marginBottom: '5px',
    color: tokens.colorNeutralForeground2,
  },
  apStyle_46: {
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground3,
    marginTop: '8px',
  },
  apStyle_47: {
    marginTop: '16px',
    padding: '14px',
    borderRadius: '10px',
    backgroundColor: tokens.colorNeutralBackground2,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
  },
  apStyle_48: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8px',
    marginBottom: '12px',
  },
  apStyle_49: {
    fontSize: '13px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  apStyle_50: {
    margin: '2px 0 0',
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground3,
  },
  apStyle_51: {
    fontSize: '11px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground2,
  },
  apStyle_52: {
    width: '90px',
    padding: '4px 8px',
    borderRadius: '6px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    fontSize: '12px',
  },
  apStyle_53: {
    padding: '4px 10px',
    borderRadius: '6px',
    backgroundColor: '#E51937',
    color: '#fff',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    fontSize: '11px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  apStyle_54: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '10px',
  },
  apStyle_55: {
    display: 'block',
    fontSize: '11.5px',
    fontWeight: 700,
    marginBottom: '4px',
    color: tokens.colorNeutralForeground2,
  },
  apStyle_56: {
    marginTop: '16px',
    padding: '16px 18px',
    borderRadius: '12px',
    backgroundColor: tokens.colorNeutralBackground2,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  apStyle_57: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '10px',
    paddingBottom: '12px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  apStyle_58: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  apStyle_59: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: 'rgba(229, 25, 55, 0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  apStyle_60: {
    fontSize: '14px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  apStyle_61: {
    fontSize: '10.5px',
    fontWeight: 700,
    padding: '2px 8px',
    borderRadius: '6px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    color: '#E51937',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.3)',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: 'rgba(229, 25, 55, 0.3)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(229, 25, 55, 0.3)',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: 'rgba(229, 25, 55, 0.3)',
  },
  apStyle_62: {
    margin: '3px 0 0',
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground3,
  },
  apStyle_63: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: tokens.colorNeutralBackground3,
    padding: '6px 12px',
    borderRadius: '8px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
  },
  apStyle_64: {
    textAlign: 'right',
  },
  apStyle_65: {
    fontSize: '10.5px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
  },
  apStyle_67: {
    width: '105px',
    padding: '6px 10px',
    borderRadius: '6px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    fontSize: '12px',
    fontWeight: 700,
  },
  apStyle_68: {
    fontSize: '11.5px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  apStyle_69: {
    display: 'flex',
    gap: '8px',
  },
  apStyle_70: {
    padding: '3px 9px',
    borderRadius: '6px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.4)',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: 'rgba(229, 25, 55, 0.4)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(229, 25, 55, 0.4)',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: 'rgba(229, 25, 55, 0.4)',
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    color: '#E51937',
    fontSize: '11px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  apStyle_71: {
    padding: '3px 9px',
    borderRadius: '6px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground2,
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  apStyle_74: {
    fontSize: '11px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
    marginBottom: '8px',
  },
  apStyle_75: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(95px, 1fr))',
    gap: '8px',
  },
  apStyle_77: {
    color: '#E51937',
    fontSize: '14px',
    flexShrink: 0,
  },
  apStyle_78: {
    width: '12px',
    height: '12px',
    borderRadius: '50%',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    display: 'inline-block',
    flexShrink: 0,
  },
  apStyle_79: {
    fontSize: '13px',
    fontWeight: 700,
  },
  apStyle_80: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '10px',
  },
  apStyle_81: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  apStyle_82: {
    width: '100px',
    padding: '4px 8px',
    borderRadius: '6px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    fontSize: '11.5px',
  },
  apStyle_83: {
    padding: '4px 10px',
    borderRadius: '6px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground1,
    fontSize: '11px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  apStyle_84: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8px',
    padding: '10px 14px',
    borderRadius: '8px',
    backgroundColor: 'rgba(229, 25, 55, 0.08)',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.25)',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: 'rgba(229, 25, 55, 0.25)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(229, 25, 55, 0.25)',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: 'rgba(229, 25, 55, 0.25)',
  },
  apStyle_85: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  apStyle_86: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground2,
  },
  apStyle_87: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  apStyle_88: {
    color: '#10b981',
  },
  apStyle_89: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '12px',
  },
  apStyle_90: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '12px',
  },
  apStyle_91: {
    padding: '4px 10px',
    borderRadius: '6px',
    backgroundColor: '#0284C7',
    color: '#fff',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    fontSize: '11px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  apStyle_92: {
    padding: '4px 10px',
    borderRadius: '6px',
    backgroundColor: '#D97706',
    color: '#fff',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    fontSize: '11px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  apStyle_93: {
    padding: '4px 10px',
    borderRadius: '6px',
    backgroundColor: '#EAB308',
    color: '#000',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    fontSize: '11px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  apStyle_94: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '8px',
  },
  apStyle_95: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '14px',
  },
  apStyle_96: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '16px',
  },
  apStyle_97: {
    fontSize: '13px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    marginBottom: '8px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  apStyle_98: {
    width: '16px',
    height: '16px',
    color: '#E51937',
  },
  apStyle_99: {
    width: '16px',
    height: '16px',
    color: '#0284C7',
  },
  apStyle_100: {
    marginTop: '4px',
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '4px',
  },
  icon14: { width: '14px', height: '14px' },
  apStyle_101: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  apStyle_102: {
    width: '13px',
    height: '13px',
  },
  apStyle_103: {
    color: '#2563EB',
    fontWeight: 600,
  },
  apStyle_104: {
    marginTop: '4px',
    padding: '10px 14px',
    borderRadius: '8px',
    backgroundColor: 'rgba(229, 25, 55, 0.08)',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.25)',
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: 'rgba(229, 25, 55, 0.25)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'rgba(229, 25, 55, 0.25)',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: 'rgba(229, 25, 55, 0.25)',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '12.5px',
    color: tokens.colorNeutralForeground1,
  },
  apStyle_105: {
    width: '22px',
    height: '22px',
    color: '#E51937',
    flexShrink: 0,
  },
  apStyle_106: {
    color: '#E51937',
  },
  apStyle_107: {
    fontWeight: 800,
    color: '#E51937',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  apStyle_108: {
    width: '14px',
    height: '14px',
  },
  apStyle_114: {
    width: '12px',
    height: '12px',
  },
  apStyle_115: {
    color: tokens.colorNeutralForeground1,
  },
  apStyle_116: {
    height: 'auto',
    minHeight: '80px',
    padding: '8px 10px',
  },
  apStyle_117: {
    fontSize: '10.5px',
    color: tokens.colorNeutralForeground3,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    marginTop: '1px',
  },
  apStyle_120: {
    fontSize: '7.5px',
    opacity: 0.85,
  },
  apStyle_121: {
    marginTop: '5px',
    padding: '4px',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: '4px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
  },
  apStyle_122: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '2px',
  },
  apStyle_123: {
    textAlign: 'center',
    padding: '1px 0',
    fontSize: '7.5px',
    fontWeight: 700,
    color: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    borderRadius: '2px',
  },
  apStyle_124: {
    display: 'flex',
    alignItems: 'center',
    gap: '2px',
    marginTop: '3px',
  },
  apStyle_125: {
    fontSize: '7.5px',
    fontWeight: 800,
    color: '#E51937',
  },
  apStyle_126: {
    flex: 1,
    height: '14px',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: '2px',
    fontSize: '7.5px',
    padding: '0 3px',
    display: 'flex',
    alignItems: 'center',
    color: tokens.colorNeutralForeground3,
  },
  apStyle_127: {
    backgroundColor: '#E51937',
    color: '#fff',
    fontSize: '7px',
    fontWeight: 700,
    padding: '1px 3px',
    borderRadius: '2px',
  },
  apStyle_128: {
    marginTop: '6px',
  },
  apStyle_129: {
    fontSize: '12px',
    fontWeight: 800,
    color: '#10B981',
    display: 'flex',
    alignItems: 'baseline',
  },
  apStyle_130: {
    fontSize: '9px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
    marginLeft: '2px',
  },
  apStyle_131: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
    padding: '4px 8px',
    borderRadius: '4px',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    backgroundColor: '#E51937',
    color: '#ffffff',
    fontSize: '10px',
    fontWeight: 700,
    cursor: 'default',
  },
  apStyle_132: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '5px',
  },
  apStyle_133: {
    background: 'none',
    borderTopStyle: 'none',
    borderRightStyle: 'none',
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    color: '#E51937',
    fontSize: '11.5px',
    fontWeight: 700,
    cursor: 'pointer',
    padding: 0,
  },
  apStyle_134: {
    padding: '8px 10px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke2,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  apStyle_135: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    flexWrap: 'wrap',
  },
  apStyle_136: {
    fontSize: '10.5px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground3,
  },
  apStyle_137: {
    fontSize: '10.5px',
    fontWeight: 600,
    padding: '1px 6px',
    borderRadius: '4px',
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    color: tokens.colorNeutralForeground1,
  },

  apDeptBadgeFastFood: {
    fontSize: '11px', fontWeight: 700, paddingTop: '4px', paddingBottom: '4px', paddingLeft: '12px', paddingRight: '12px', borderRadius: '12px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)', color: '#E51937',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: 'rgba(229, 25, 55, 0.25)',
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: 'rgba(229, 25, 55, 0.25)',
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: 'rgba(229, 25, 55, 0.25)',
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: 'rgba(229, 25, 55, 0.25)',
  },
  apDeptBadgeMinimart: {
    fontSize: '11px', fontWeight: 700, paddingTop: '4px', paddingBottom: '4px', paddingLeft: '12px', paddingRight: '12px', borderRadius: '12px',
    backgroundColor: 'rgba(2, 132, 199, 0.12)', color: '#0284C7',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: 'rgba(2, 132, 199, 0.25)',
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: 'rgba(2, 132, 199, 0.25)',
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: 'rgba(2, 132, 199, 0.25)',
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: 'rgba(2, 132, 199, 0.25)',
  },
  apDeptCardBase: {
    display: 'flex', alignItems: 'center', columnGap: '14px', rowGap: '14px', paddingTop: '14px', paddingBottom: '14px', paddingLeft: '18px', paddingRight: '18px', borderRadius: '10px', boxSizing: 'border-box',
    cursor: 'pointer', textAlign: 'left', transitionProperty: 'all', transitionDuration: '0.15s', transitionTimingFunction: 'ease',
    borderTopWidth: '2px', borderTopStyle: 'solid', borderRightWidth: '2px', borderRightStyle: 'solid', borderBottomWidth: '2px', borderBottomStyle: 'solid', borderLeftWidth: '2px', borderLeftStyle: 'solid',
  },
  apDeptCardFastFoodActive: {
    borderTopColor: '#E51937', borderRightColor: '#E51937', borderBottomColor: '#E51937', borderLeftColor: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.09)', boxShadow: '0 4px 14px rgba(229, 25, 55, 0.18)',
  },
  apDeptCardFastFoodInactive: {
    borderTopColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2, borderLeftColor: tokens.colorNeutralStroke2,
    backgroundColor: tokens.colorNeutralBackground2, boxShadow: 'none',
  },
  apDeptCardMinimartActive: {
    borderTopColor: '#0284C7', borderRightColor: '#0284C7', borderBottomColor: '#0284C7', borderLeftColor: '#0284C7',
    backgroundColor: 'rgba(2, 132, 199, 0.09)', boxShadow: '0 4px 14px rgba(2, 132, 199, 0.20)',
  },
  apDeptCardMinimartInactive: {
    borderTopColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2, borderLeftColor: tokens.colorNeutralStroke2,
    backgroundColor: tokens.colorNeutralBackground2, boxShadow: 'none',
  },
  apDeptIconBase: {
    width: '44px', height: '44px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  apDeptIconFastFoodActive: {
    backgroundColor: '#E51937', color: '#FFFFFF', boxShadow: '0 2px 8px rgba(229, 25, 55, 0.35)',
  },
  apDeptIconFastFoodInactive: {
    backgroundColor: tokens.colorNeutralBackground3, color: tokens.colorNeutralForeground2, boxShadow: 'none',
  },
  apDeptIconMinimartActive: {
    backgroundColor: '#0284C7', color: '#FFFFFF', boxShadow: '0 2px 8px rgba(2, 132, 199, 0.35)',
  },
  apDeptIconMinimartInactive: {
    backgroundColor: tokens.colorNeutralBackground3, color: tokens.colorNeutralForeground2, boxShadow: 'none',
  },
  apDeptTextTitleBase: {
    fontWeight: 800, fontSize: '14px',
  },
  apDeptTextTitleFastFoodActive: {
    color: '#E51937',
  },
  apDeptTextTitleMinimartActive: {
    color: '#0284C7',
  },
  apDeptTextTitleInactive: {
    color: tokens.colorNeutralForeground1,
  },

  // 2. Chip / Pill selections
  apChipBase: {
    paddingTop: '6px', paddingBottom: '6px', paddingLeft: '14px', paddingRight: '14px', borderRadius: '8px', boxSizing: 'border-box',
    fontWeight: 600, fontSize: '12px', cursor: 'pointer', display: 'flex', alignItems: 'center', columnGap: '6px', rowGap: '6px',
    borderTopWidth: '1.5px', borderTopStyle: 'solid', borderRightWidth: '1.5px', borderRightStyle: 'solid', borderBottomWidth: '1.5px', borderBottomStyle: 'solid', borderLeftWidth: '1.5px', borderLeftStyle: 'solid',
    transitionProperty: 'all', transitionDuration: '0.15s', transitionTimingFunction: 'ease',
  },
  apChipActive: {
    borderTopColor: '#E51937', borderRightColor: '#E51937', borderBottomColor: '#E51937', borderLeftColor: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.15)', color: '#ffffff',
  },
  apChipInactive: {
    borderTopColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground3, color: tokens.colorNeutralForeground2,
  },
  apChipBadgeActive: {
    fontSize: '10.5px', paddingTop: '1px', paddingBottom: '1px', paddingLeft: '5px', paddingRight: '5px', borderRadius: '4px',
    backgroundColor: '#E51937', color: '#ffffff', fontWeight: 700,
  },
  apChipBadgeInactive: {
    fontSize: '10.5px', paddingTop: '1px', paddingBottom: '1px', paddingLeft: '5px', paddingRight: '5px', borderRadius: '4px',
    backgroundColor: 'rgba(255, 255, 255, 0.08)', color: '#ffffff', fontWeight: 700,
  },
  apGridChipBase: {
    paddingTop: '8px', paddingBottom: '8px', paddingLeft: '10px', paddingRight: '10px', borderRadius: '8px', boxSizing: 'border-box',
    display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', columnGap: '6px', rowGap: '6px', cursor: 'pointer',
    borderTopWidth: '1.5px', borderTopStyle: 'solid', borderRightWidth: '1.5px', borderRightStyle: 'solid', borderBottomWidth: '1.5px', borderBottomStyle: 'solid', borderLeftWidth: '1.5px', borderLeftStyle: 'solid',
    transitionProperty: 'all', transitionDuration: '0.15s', transitionTimingFunction: 'ease', whiteSpace: 'nowrap',
  },
  apGridChipActive: {
    borderTopColor: '#E51937', borderRightColor: '#E51937', borderBottomColor: '#E51937', borderLeftColor: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.14)', color: '#ffffff', boxShadow: '0 0 10px rgba(229, 25, 55, 0.25)',
  },
  apGridChipInactive: {
    borderTopColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground3, color: tokens.colorNeutralForeground2, boxShadow: 'none',
  },

  // 3. Simple toggles
  apPriceNumGreen: { fontSize: '14px', fontWeight: 800, color: '#10b981' },
  apPriceNumAmber: { fontSize: '14px', fontWeight: 800, color: '#f59e0b' },
  apBtnSelectActive: { backgroundColor: '#E51937', color: '#FFFFFF', borderTopColor: '#E51937', borderRightColor: '#E51937', borderBottomColor: '#E51937', borderLeftColor: '#E51937', borderTopWidth: '1.5px', borderRightWidth: '1.5px', borderBottomWidth: '1.5px', borderLeftWidth: '1.5px', borderTopStyle: 'solid', borderRightStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', boxSizing: 'border-box' },
  apBtnSelectTextWhite: { color: '#FFFFFF' },
  apBtnSelectStrokeWhite: { stroke: '#FFFFFF', color: '#FFFFFF' },

  // 4. Dynamic accent helpers
  apAccentPillBase: {
    paddingTop: '6px', paddingBottom: '6px', paddingLeft: '14px', paddingRight: '14px', borderRadius: '20px', fontSize: '12px', fontWeight: 600, boxSizing: 'border-box',
    cursor: 'pointer', display: 'inline-flex', alignItems: 'center', columnGap: '6px', rowGap: '6px',
    borderTopWidth: '1.5px', borderTopStyle: 'solid', borderRightWidth: '1.5px', borderRightStyle: 'solid', borderBottomWidth: '1.5px', borderBottomStyle: 'solid', borderLeftWidth: '1.5px', borderLeftStyle: 'solid',
    transitionProperty: 'all', transitionDuration: '0.15s', transitionTimingFunction: 'ease',
  },
  apAccentPillInactive: {
    borderTopColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1, color: tokens.colorNeutralForeground1, boxShadow: 'none',
  },
  apAccentBoxBase: {
    boxSizing: 'border-box', fontWeight: 600,
    borderTopWidth: '1.5px', borderTopStyle: 'solid', borderRightWidth: '1.5px', borderRightStyle: 'solid', borderBottomWidth: '1.5px', borderBottomStyle: 'solid', borderLeftWidth: '1.5px', borderLeftStyle: 'solid',
    transitionProperty: 'all', transitionDuration: '0.15s', transitionTimingFunction: 'ease',
  },
  apAccentBoxInactive: {
    borderTopColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1, color: tokens.colorNeutralForeground2,
  },
  apAccentWrapCard: {
    paddingTop: '12px', paddingBottom: '12px', paddingLeft: '16px', paddingRight: '16px', borderRadius: '10px',
    backgroundColor: tokens.colorNeutralBackground2,
    borderTopWidth: '1px', borderTopStyle: 'solid', borderRightWidth: '1px', borderRightStyle: 'solid', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderLeftWidth: '1px', borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2, borderLeftColor: tokens.colorNeutralStroke2,
    transitionProperty: 'all', transitionDuration: '0.2s', transitionTimingFunction: 'ease',
  },
  apCategoryBadgeBase: {
    fontSize: '10.5px', fontWeight: 600, paddingTop: '1px', paddingBottom: '1px', paddingLeft: '6px', paddingRight: '6px', borderRadius: '4px',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderRightWidth: '1px', borderRightStyle: 'solid', borderBottomWidth: '1px', borderBottomStyle: 'solid', borderLeftWidth: '1px', borderLeftStyle: 'solid',
  },
  apPreviewTabHeader: {
    display: 'grid', borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: tokens.colorNeutralStroke1,
    borderRadius: '4px', overflow: 'hidden', marginTop: '5px',
  },
  apPreviewTabFirst: {
    paddingTop: '2px', paddingBottom: '1px', paddingLeft: '1px', paddingRight: '1px', textAlign: 'center', backgroundColor: '#E51937', color: '#FFFFFF', fontSize: '8.5px', fontWeight: 700, lineHeight: 1.1,
  },
  apPreviewTabOther: {
    paddingTop: '2px', paddingBottom: '1px', paddingLeft: '1px', paddingRight: '1px', textAlign: 'center', backgroundColor: 'transparent', color: tokens.colorNeutralForeground3, fontSize: '8.5px', fontWeight: 700, lineHeight: 1.1,
  },
  apRupeesQuickBadge: {
    textAlign: 'center', paddingTop: '1px', paddingBottom: '1px', paddingLeft: 0, paddingRight: 0, fontSize: '7.5px', fontWeight: 700, color: '#E51937', backgroundColor: 'rgba(229, 25, 55, 0.1)', borderRadius: '2px',
  },
  apRupeesLabel: {
    fontSize: '7.5px', fontWeight: 800, color: '#E51937',
  },
  apRupeesInputMock: {
    flexGrow: 1, flexShrink: 1, flexBasis: 0, height: '14px', backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: '2px', fontSize: '7.5px', paddingLeft: '3px', paddingRight: '3px', display: 'flex', alignItems: 'center', color: tokens.colorNeutralForeground3,
  },
  apRupeesAddBtn: {
    backgroundColor: '#E51937', color: '#ffffff', fontSize: '7px', fontWeight: 700, paddingTop: '1px', paddingBottom: '1px', paddingLeft: '3px', paddingRight: '3px', borderRadius: '2px',
  },
  apPreviewPriceRow: {
    fontSize: '12px', fontWeight: 800, color: '#10B981', display: 'flex', alignItems: 'baseline',
  },
  apRupeesSaleNotice: {
    marginTop: '4px', paddingTop: '10px', paddingBottom: '10px', paddingLeft: '14px', paddingRight: '14px', borderRadius: '8px', backgroundColor: 'rgba(229, 25, 55, 0.08)',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: 'rgba(229, 25, 55, 0.25)',
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: 'rgba(229, 25, 55, 0.25)',
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: 'rgba(229, 25, 55, 0.25)',
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: 'rgba(229, 25, 55, 0.25)',
    display: 'flex', alignItems: 'center', columnGap: '10px', rowGap: '10px', fontSize: '12.5px', color: tokens.colorNeutralForeground1,
  },
  apSanitaryLink: {
    marginLeft: '8px', fontSize: '11px', fontWeight: 700,
  },
  apRemCard1: {
    display: 'flex', flexDirection: 'column', gap: '10px', backgroundColor: tokens.colorNeutralBackground1, padding: '16px 20px', borderRadius: tokens.borderRadiusMedium,
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: tokens.colorNeutralStroke1,
    boxShadow: tokens.shadow2,
  },
  apRemCard2: {
    display: 'flex', alignItems: 'center', gap: '14px', padding: '12px 16px', borderRadius: '8px', backgroundColor: tokens.colorNeutralBackground2,
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: tokens.colorNeutralStroke2,
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: tokens.colorNeutralStroke2,
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: tokens.colorNeutralStroke2,
  },
  apRemIconRed36: {
    width: '36px', height: '36px', borderRadius: '8px', backgroundColor: '#E51937', color: '#FFFFFF', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  apRemIconBlue36: {
    width: '36px', height: '36px', borderRadius: '8px', backgroundColor: '#0284C7', color: '#FFFFFF', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  apRemSectionCard16: {
    marginTop: '16px', padding: '16px 18px', borderRadius: '12px', backgroundColor: tokens.colorNeutralBackground2,
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: tokens.colorNeutralStroke1,
    display: 'flex', flexDirection: 'column', gap: '14px',
  },
  apRemSectionHeaderRow: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '10px', paddingBottom: '12px',
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke2,
  },
  apRemBadgeRedGlow36: {
    width: '36px', height: '36px', borderRadius: '8px', backgroundColor: 'rgba(229, 25, 55, 0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  apRemPillRedBorder: {
    fontSize: '10.5px', fontWeight: 700, padding: '2px 8px', borderRadius: '6px', backgroundColor: 'rgba(229, 25, 55, 0.12)', color: '#E51937',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: 'rgba(229, 25, 55, 0.3)',
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: 'rgba(229, 25, 55, 0.3)',
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: 'rgba(229, 25, 55, 0.3)',
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: 'rgba(229, 25, 55, 0.3)',
  },
  apRemRowStroke1: {
    display: 'flex', alignItems: 'center', gap: '10px', backgroundColor: tokens.colorNeutralBackground3, padding: '6px 12px', borderRadius: '8px',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: tokens.colorNeutralStroke1,
  },
  apRemInput105: {
    width: '105px', padding: '6px 10px', borderRadius: '6px',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1, color: tokens.colorNeutralForeground1, fontSize: '12px', fontWeight: 700,
  },
  apRemBtnRedOutline: {
    padding: '3px 9px', borderRadius: '6px',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: 'rgba(229, 25, 55, 0.4)',
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: 'rgba(229, 25, 55, 0.4)',
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: 'rgba(229, 25, 55, 0.4)',
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: 'rgba(229, 25, 55, 0.4)',
    backgroundColor: 'rgba(229, 25, 55, 0.1)', color: '#E51937', fontSize: '11px', fontWeight: 700, cursor: 'pointer',
  },
  apRemBtnNeutralOutline: {
    padding: '3px 9px', borderRadius: '6px',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground3, color: tokens.colorNeutralForeground2, fontSize: '11px', fontWeight: 600, cursor: 'pointer',
  },
  apRemGridAutoFill: {
    display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(95px, 1fr))', gap: '8px',
  },
  apRemInput100: {
    width: '100px', padding: '4px 8px', borderRadius: '6px',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: tokens.colorNeutralStroke1,
    fontSize: '11.5px',
  },
  apRemBtnNeutralSolid: {
    padding: '4px 10px', borderRadius: '6px',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground3, color: tokens.colorNeutralForeground1, fontSize: '11px', fontWeight: 700, cursor: 'pointer',
  },
  apRemBoxRedTranslucent: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px', padding: '10px 14px', borderRadius: '8px',
    backgroundColor: 'rgba(229, 25, 55, 0.08)',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: 'rgba(229, 25, 55, 0.25)',
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: 'rgba(229, 25, 55, 0.25)',
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: 'rgba(229, 25, 55, 0.25)',
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: 'rgba(229, 25, 55, 0.25)',
  },
  apRemSaleNoticeBox: {
    marginTop: '4px', padding: '10px 14px', borderRadius: '8px', backgroundColor: 'rgba(229, 25, 55, 0.08)',
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: 'rgba(229, 25, 55, 0.25)',
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: 'rgba(229, 25, 55, 0.25)',
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: 'rgba(229, 25, 55, 0.25)',
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: 'rgba(229, 25, 55, 0.25)',
    display: 'flex', alignItems: 'center', gap: '10px', fontSize: '12.5px', color: tokens.colorNeutralForeground1,
  },
  apRemBtnRedPillSmall: {
    display: 'inline-flex', alignItems: 'center', gap: '3px', padding: '4px 8px', borderRadius: '4px', borderTopStyle: 'none', borderRightStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none',
    backgroundColor: '#E51937', color: '#ffffff', fontSize: '10px', fontWeight: 700, cursor: 'default',
  },
  apRemLinkRedPlain: {
    background: 'none', borderTopStyle: 'none', borderRightStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none',
    color: '#E51937', fontSize: '11.5px', fontWeight: 700, cursor: 'pointer', padding: 0,
  },
  apRemBadgeStroke1: {
    fontSize: '10.5px', fontWeight: 600, padding: '1px 6px', borderRadius: '4px', backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px', borderTopStyle: 'solid', borderTopColor: tokens.colorNeutralStroke1,
    borderRightWidth: '1px', borderRightStyle: 'solid', borderRightColor: tokens.colorNeutralStroke1,
    borderBottomWidth: '1px', borderBottomStyle: 'solid', borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftWidth: '1px', borderLeftStyle: 'solid', borderLeftColor: tokens.colorNeutralStroke1,
    color: tokens.colorNeutralForeground1,
  },
});

export const useStyles = useAddProductStyles;
