import React from 'react';
import { makeStyles, tokens } from '@fluentui/react-components';

export const getAccentIconStyle = (accentColor: string): React.CSSProperties => ({
  backgroundColor: `${accentColor}16`,
  borderTopColor: `${accentColor}35`,
  borderBottomColor: `${accentColor}35`,
  borderLeftColor: `${accentColor}35`,
  borderRightColor: `${accentColor}35`,
  color: accentColor,
});

export const getAccentBadgeStyle = (accentColor: string): React.CSSProperties => ({
  backgroundColor: `${accentColor}18`,
  borderTopColor: `${accentColor}40`,
  borderBottomColor: `${accentColor}40`,
  borderLeftColor: `${accentColor}40`,
  borderRightColor: `${accentColor}40`,
  color: accentColor,
});

export const useCategoriesStyles = makeStyles({
  container: {
    padding: '20px 24px',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    backgroundColor: tokens.colorNeutralBackground2,
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: '16px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
  },
  headerTitle: {
    fontWeight: 800,
    fontSize: '20px',
    color: tokens.colorNeutralForeground1,
    margin: 0,
    display: 'block',
  },
  headerSubtitle: {
    color: tokens.colorNeutralForeground2,
    margin: 0,
    display: 'block',
    fontSize: '13px',
    marginTop: '2px',
  },
  primaryBtn: {
    backgroundColor: '#E51937',
    color: '#ffffff',
    borderRadius: tokens.borderRadiusMedium,
    fontWeight: 600,
    ':hover': {
      backgroundColor: '#be123c',
    },
  },
  sectionBox: {
    display: 'flex',
    flexDirection: 'column',
  },
  sectionBoxSpaced: {
    marginTop: '10px',
  },
  sectionTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '15px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    marginBottom: '12px',
  },
  sectionIconRed: {
    color: '#E51937',
    width: '20px',
    height: '20px',
  },
  sectionAddBtn: {
    marginLeft: 'auto',
    fontSize: '12px',
    fontWeight: 600,
    color: '#E51937',
  },
  categoryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: '16px',
  },
  categoryCard: {
    borderRadius: '12px',
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    padding: '16px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    transition: 'all 0.18s cubic-bezier(0.16, 1, 0.3, 1)',
    ':hover': {
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.16)',
      transform: 'translateY(-2px)',
    },
  },
  categoryCardLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  tagIconBox: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  tagIcon: {
    width: '18px',
    height: '18px',
  },
  categoryInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  categoryTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    fontSize: '14.5px',
  },
  categoryMetaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginTop: '2px',
  },
  profileBadge: {
    fontSize: '9.5px',
    fontWeight: 800,
    padding: '1px 6px',
    borderRadius: '4px',
  },
  productCountText: {
    color: tokens.colorNeutralForeground2,
    fontSize: '11.5px',
  },
  deleteActionBtn: {
    color: '#D13438',
  },

  // Modal Dialog
  dialogSurface: {
    maxWidth: '480px',
    width: '92vw',
    borderRadius: '16px',
    padding: '24px',
    boxSizing: 'border-box',
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    boxShadow: '0 24px 64px rgba(0, 0, 0, 0.5)',
    display: 'flex',
    flexDirection: 'column',
  },
  dialogForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
    width: '100%',
  },
  dialogHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '14px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    width: '100%',
  },
  dialogHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  dialogIconBox: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#E51937',
  },
  dialogTitleText: {
    fontSize: '17px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  dialogSubtitleText: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  dialogFieldsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: '100%',
  },
  fieldLabel: {
    display: 'block',
    marginBottom: '6px',
    fontWeight: 600,
    fontSize: '13px',
  },
  fullWidth: {
    width: '100%',
  },
  errorCaption: {
    color: tokens.colorPaletteRedForeground1,
    marginTop: '4px',
    display: 'block',
  },
  hintCaption: {
    color: tokens.colorNeutralForeground3,
    marginTop: '5px',
    display: 'block',
    fontSize: '11px',
    lineHeight: '1.4',
  },
  dialogActionsRow: {
    display: 'flex',
    gap: '10px',
    justifyContent: 'flex-end',
    marginTop: '6px',
    paddingTop: '14px',
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    width: '100%',
  },
  dialogCancelBtn: {
    borderRadius: '8px',
    fontWeight: 600,
  },
  dialogSaveBtn: {
    backgroundColor: '#E51937',
    color: '#ffffff',
    borderRadius: '8px',
    fontWeight: 700,
    padding: '0 20px',
    ':hover': {
      backgroundColor: '#be123c',
    },
  },

  /* ── 1-Click Industry Templates Modal Styles ── */
  templateDialogSurface: {
    maxWidth: '1040px',
    width: '95vw',
    maxHeight: '90vh',
    borderRadius: '16px',
    padding: '24px',
    boxSizing: 'border-box',
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    boxShadow: '0 24px 64px rgba(0, 0, 0, 0.5)',
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
  },
  templateDialogHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: '16px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    marginBottom: '16px',
  },
  templateHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  templateIconBox: {
    width: '42px',
    height: '42px',
    borderRadius: '12px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#E51937',
    flexShrink: 0,
  },
  templateDialogTitle: {
    fontSize: '18px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  templateDialogSubtitle: {
    fontSize: '12.5px',
    color: tokens.colorNeutralForeground3,
    marginTop: '2px',
  },
  successBanner: {
    padding: '10px 16px',
    borderRadius: '8px',
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    border: '1px solid rgba(16, 185, 129, 0.3)',
    color: '#059669',
    fontWeight: 700,
    fontSize: '13px',
    marginBottom: '16px',
  },
  templateGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(290px, 1fr))',
    gap: '16px',
    paddingBottom: '10px',
  },
  templateCard: {
    borderRadius: '12px',
    backgroundColor: tokens.colorNeutralBackground2,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    transition: 'all 0.15s ease-in-out',
    ':hover': {
      boxShadow: '0 6px 18px rgba(0, 0, 0, 0.18)',
      transform: 'translateY(-2px)',
    },
  },
  templateCardTop: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
  },
  templateCardIcon: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  templateCardMeta: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minWidth: 0,
  },
  templateCardTitleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  templateCardTitle: {
    fontWeight: 800,
    fontSize: '13.5px',
    color: tokens.colorNeutralForeground1,
    lineHeight: '1.3',
  },
  templateCardUrdu: {
    fontSize: '12px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
    marginTop: '2px',
  },
  templateCardDesc: {
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground2,
    margin: 0,
    lineHeight: '1.4',
  },
  templateSpecsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    backgroundColor: tokens.colorNeutralBackground1,
    padding: '6px 10px',
    borderRadius: '6px',
  },
  specLabel: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
  },
  specValue: {
    fontWeight: 600,
  },
  specDivider: {
    opacity: 0.5,
  },
  chipsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
    flex: 1,
  },
  chipsTitle: {
    fontSize: '10.5px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  chipsWrapper: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px',
  },
  previewChip: {
    fontSize: '10.5px',
    padding: '2px 7px',
    borderRadius: '4px',
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    color: tokens.colorNeutralForeground2,
    fontWeight: 500,
  },
  templateCardFooter: {
    marginTop: 'auto',
    paddingTop: '6px',
  },
  hintCaptionRow: {
    marginTop: '4px',
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  hintCaptionLocked: {
    color: '#059669',
    fontWeight: 600,
  },
  catFormHintRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '5px',
  },
  catFormHintText: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  catFormToggleBtn: {
    backgroundColor: 'transparent',
    borderTopStyle: 'none', borderBottomStyle: 'none',
    borderLeftStyle: 'none', borderRightStyle: 'none',
    color: '#E51937',
    fontSize: '11.5px',
    fontWeight: 700,
    cursor: 'pointer',
    padding: 0,
  },
  presetInfoBox: {
    padding: '8px 10px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  presetChipRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    flexWrap: 'wrap',
  },
  presetChipLabel: {
    fontSize: '10.5px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground3,
  },
  presetUnitChip: {
    fontSize: '10.5px',
    fontWeight: 600,
    padding: '1px 6px',
    borderRadius: '4px',
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    color: tokens.colorNeutralForeground1,
  },
});

export const useStyles = useCategoriesStyles;
