import { makeStyles, tokens } from '@fluentui/react-components';

export const useProductsCatalogStyles = makeStyles({
  container: {
    padding: '20px 24px',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
    backgroundColor: tokens.colorNeutralBackground2, // #F5F5F5 Mica Canvas
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: '20px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
  },
  hudCard: {
    borderRadius: '12px',
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    padding: '18px 20px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    transition: 'all 0.2s ease',
    ':hover': {
      boxShadow: tokens.shadow8,
      transform: 'translateY(-2px)',
    },
  },
  divisionHeroCard: {
    borderRadius: '14px',
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow8,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    transition: 'all 0.2s ease',
    ':hover': {
      boxShadow: tokens.shadow16,
    },
  },
  tableCard: {
    borderRadius: tokens.borderRadiusMedium, // 8px
    backgroundColor: tokens.colorNeutralBackground1, // White container
    boxShadow: tokens.shadow4, // Subtle Fluent elevation
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  filterBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  categoryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))',
    gap: '16px',
  },
  categoryCard: {
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    padding: '16px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
  },
  productDialogSurface: {
    maxWidth: '980px',
    width: 'min(980px, 95vw)',
    minWidth: 'min(800px, 90vw)',
    maxHeight: 'min(92vh, 680px)',
    borderRadius: '16px',
    padding: '18px 24px 14px 24px',
    boxShadow: '0 24px 64px rgba(0, 0, 0, 0.45)',
    boxSizing: 'border-box',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  productDialogContent: {
    overflowY: 'auto',
    overflowX: 'hidden',
    padding: '0',
    flex: '1 1 auto',
    minHeight: '0',
  },
  kpiContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '22px',
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '16px',
  },
  kpiHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  kpiLabel: {
    fontSize: '11px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground3,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  kpiValue: {
    fontSize: '26px',
    fontWeight: 900,
    color: tokens.colorNeutralForeground1,
    marginTop: '4px',
    lineHeight: '1.1',
  },
  kpiSkus: {
    fontSize: '13px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
  },
  kpiValueGreen: {
    fontSize: '24px',
    fontWeight: 900,
    color: '#10B981',
    marginTop: '4px',
    lineHeight: '1.1',
  },
  kpiValueRed: {
    fontSize: '26px',
    fontWeight: 900,
    color: '#EF4444',
    marginTop: '4px',
    lineHeight: '1.1',
  },
  kpiIconFastFood: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    background: 'rgba(229, 25, 55, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#E51937',
  },
  kpiIconBlue: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    background: 'rgba(2, 132, 199, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#0284C7',
  },
  kpiIconGreen: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    background: 'rgba(160, 230, 190, 0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#10B981',
  },
  kpiIconRed: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    background: 'rgba(239, 68, 68, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#EF4444',
  },
  kpiIconPurple: {
    width: '38px',
    height: '38px',
    borderRadius: '10px',
    background: 'rgba(168, 85, 247, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#A855F7',
  },
  kpiSubRow: {
    display: 'flex',
    gap: '8px',
    marginTop: '12px',
    fontSize: '11.5px',
  },
  kpiRedText: {
    color: '#E51937',
    fontWeight: 700,
  },
  kpiBlueText: {
    color: '#0284C7',
    fontWeight: 700,
  },
  kpiAmberText: {
    color: '#F59E0B',
    fontWeight: 700,
  },
  kpiManageCatsLink: {
    color: '#A855F7',
    fontWeight: 700,
    cursor: 'pointer',
  },
  divisionHeroTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  divisionHeroTitleWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  divisionIconFastFood: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    background: 'linear-gradient(135deg, #FF1E3C 0%, #990012 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    boxShadow: '0 0 16px rgba(229, 25, 55, 0.4)',
  },
  divisionIconOmnimart: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    background: 'linear-gradient(135deg, #0EA5E9 0%, #0369A1 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    boxShadow: '0 0 16px rgba(14, 165, 233, 0.4)',
  },
  divisionTitle: {
    fontSize: '18px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  divisionSubtitle: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  divisionTagFastFood: {
    fontSize: '10.5px',
    fontWeight: 800,
    color: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    padding: '3px 8px',
    borderRadius: '6px',
    border: '1px solid rgba(229, 25, 55, 0.25)',
  },
  divisionTagOmnimart: {
    fontSize: '10.5px',
    fontWeight: 800,
    color: '#0284C7',
    backgroundColor: 'rgba(14, 165, 233, 0.12)',
    padding: '3px 8px',
    borderRadius: '6px',
    border: '1px solid rgba(14, 165, 233, 0.25)',
  },
  divisionStatBox: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '12px',
    marginTop: '20px',
    padding: '14px',
    borderRadius: '8px',
    background: tokens.colorNeutralBackground3,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  divisionStatHead: {
    fontSize: '10.5px',
    color: tokens.colorNeutralForeground3,
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  divisionStatNum: {
    fontSize: '18px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    marginTop: '2px',
  },
  divisionStatNumGreen: {
    fontSize: '18px',
    fontWeight: 800,
    color: '#10B981',
    marginTop: '2px',
  },
  divisionStatNumBlue: {
    fontSize: '18px',
    fontWeight: 800,
    color: '#0284C7',
    marginTop: '2px',
  },
  divisionBtnRow: {
    display: 'flex',
    gap: '10px',
    marginTop: '20px',
  },
  btnFastFoodHero: {
    backgroundColor: '#E51937',
    color: '#ffffff',
    borderRadius: '8px',
    fontWeight: 700,
    flex: 1,
    ':hover': {
      backgroundColor: '#be123c',
    },
  },
  btnOmnimartHero: {
    backgroundColor: '#0284C7',
    color: '#ffffff',
    borderRadius: '8px',
    fontWeight: 700,
    flex: 1,
    ':hover': {
      backgroundColor: '#0369a1',
    },
  },
  btnOutlineRounded: {
    borderRadius: '8px',
    fontWeight: 600,
  },
  // Header styles
  headerTitleWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  headerTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  headerTitle: {
    fontWeight: 800,
    fontSize: '20px',
    color: tokens.colorNeutralForeground1,
    margin: 0,
  },
  headerBadge: {
    fontSize: '10px',
    fontWeight: 800,
    padding: '2px 7px',
    borderRadius: '4px',
    backgroundColor: 'rgba(229, 25, 55, 0.15)',
    color: '#FF4D63',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.3)', borderBottomColor: 'rgba(229, 25, 55, 0.3)',
    borderLeftColor: 'rgba(229, 25, 55, 0.3)', borderRightColor: 'rgba(229, 25, 55, 0.3)',
    letterSpacing: '0.06em',
  },
  headerSubtitle: {
    color: tokens.colorNeutralForeground2,
    margin: 0,
    display: 'block',
    fontSize: '13px',
    marginTop: '2px',
  },
  headerActions: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
  },
  categoriesMgrBtn: {
    borderRadius: tokens.borderRadiusMedium,
    fontWeight: 600,
  },
  addProductBtn: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: tokens.borderRadiusMedium,
    fontWeight: 600,
    ':hover': {
      backgroundColor: '#C6172E',
    },
  },

  // KPI & Radar styles
  kpiDot: {
    color: tokens.colorNeutralForeground4,
  },
  kpiSubRowColored: {
    color: tokens.colorNeutralForeground3,
  },
  totalCostVal: {
    color: tokens.colorNeutralForeground1,
  },
  icon22: {
    width: '22px',
    height: '22px',
  },
  icon26: {
    width: '26px',
    height: '26px',
  },
  icon28: {
    width: '28px',
    height: '28px',
  },
  icon14: {
    width: '14px',
    height: '14px',
  },
  icon20: {
    width: '20px',
    height: '20px',
  },
  divisionGrid: {
    display: 'grid',
    gap: '20px',
  },
  divisionGrid2: {
    gridTemplateColumns: '1fr 1fr',
  },
  divisionGrid1: {
    gridTemplateColumns: '1fr',
  },
  radarCard: {
    borderRadius: '12px',
    padding: '18px 20px',
    background: 'rgba(239, 68, 68, 0.04)',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(239, 68, 68, 0.2)', borderBottomColor: 'rgba(239, 68, 68, 0.2)',
    borderLeftColor: 'rgba(239, 68, 68, 0.2)', borderRightColor: 'rgba(239, 68, 68, 0.2)',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  radarHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  radarTitleWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  radarIcon: {
    color: '#EF4444',
    width: '20px',
    height: '20px',
  },
  radarTitle: {
    fontWeight: 800,
    fontSize: '14px',
    color: tokens.colorNeutralForeground1,
  },
  radarBadge: {
    fontSize: '11px',
    fontWeight: 700,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    color: '#EF4444',
    padding: '2px 7px',
    borderRadius: '999px',
  },
  radarActionBtn: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#E51937',
  },
  radarGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
    gap: '12px',
  },
  radarItemCard: {
    padding: '12px 14px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    boxShadow: tokens.shadow2,
  },
  radarItemLeft: {
    overflow: 'hidden',
    marginRight: '10px',
  },
  radarItemName: {
    fontSize: '13px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  radarItemMeta: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  radarItemRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
  },
  radarItemBadge: {
    fontWeight: 800,
    fontSize: '11px',
  },

  // Live POS Cards Showcase styles
  liveHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '14px',
  },
  liveTitleWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  liveTitle: {
    fontWeight: 800,
    fontSize: '16px',
    color: tokens.colorNeutralForeground1,
  },
  liveSubtitle: {
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground3,
  },
  liveSearchWrap: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
    width: '280px',
  },
  liveCardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(210px, 1fr))',
    gap: '14px',
  },
  liveCard: {
    height: '210px',
    borderRadius: '10px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: tokens.shadow4,
    transition: 'transform 0.15s ease, box-shadow 0.15s ease',
    position: 'relative',
  },
  liveCardImgWrap: {
    height: '126px',
    width: '100%',
    position: 'relative',
    backgroundColor: tokens.colorNeutralBackground3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  noPhotoPlaceholder: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    color: tokens.colorNeutralForeground4,
  },
  noPhotoText: {
    fontSize: '10px',
  },
  cardStockBadge: {
    position: 'absolute',
    top: '6px',
    right: '6px',
    padding: '2px 6px',
    borderRadius: '4px',
    color: '#ffffff',
    fontSize: '10px',
    fontWeight: 700,
  },
  cardStockBadgeAlert: {
    backgroundColor: 'rgba(239, 68, 68, 0.9)',
  },
  cardStockBadgeNormal: {
    backgroundColor: 'rgba(0,0,0,0.65)',
  },
  cardEditBtn: {
    position: 'absolute',
    bottom: '6px',
    right: '6px',
    width: '26px',
    height: '26px',
    borderRadius: '6px',
    backgroundColor: 'rgba(0,0,0,0.7)',
    color: '#ffffff',
    borderTopStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none', borderRightStyle: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveCardContent: {
    height: '84px',
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  cardProdName: {
    fontSize: '13px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  cardVariantRow: {
    display: 'flex',
    gap: '3px',
    marginTop: '2px',
    overflow: 'hidden',
  },
  cardVariantTag: {
    fontSize: '9px',
    fontWeight: 800,
    padding: '0 4px',
    borderRadius: '3px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    color: '#E51937',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.25)', borderBottomColor: 'rgba(229, 25, 55, 0.25)',
    borderLeftColor: 'rgba(229, 25, 55, 0.25)', borderRightColor: 'rgba(229, 25, 55, 0.25)',
  },
  cardVariantMore: {
    fontSize: '9px',
    color: tokens.colorNeutralForeground3,
  },
  cardCatSubtitle: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    marginTop: '1px',
  },
  cardBottomRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardPrice: {
    fontSize: '14px',
    fontWeight: 900,
    color: '#E51937',
  },
  cardSku: {
    fontSize: '10px',
    fontFamily: tokens.fontFamilyMonospace,
    color: tokens.colorNeutralForeground3,
  },

  // Detailed Table styles
  searchRow: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
  },
  searchCol300: {
    width: '300px',
  },
  filterCol200: {
    width: '200px',
  },
  tableCaption: {
    color: tokens.colorNeutralForeground2,
  },
  tableOverflow: {
    overflowX: 'auto',
    width: '100%',
  },
  dataTable: {
    width: '100%',
    borderCollapse: 'separate',
    borderSpacing: 0,
    tableLayout: 'auto',
  },
  tableTheadTr: {
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  thDetails: {
    padding: '12px 14px',
    width: '28%',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  thCategory: {
    padding: '12px 12px',
    width: '15%',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  thPrice: {
    padding: '12px 12px',
    width: '13%',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  thCost: {
    padding: '12px 12px',
    width: '13%',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  thStock: {
    padding: '12px 12px',
    width: '11%',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  thSku: {
    padding: '12px 12px',
    width: '10%',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  thActions: {
    padding: '12px 14px',
    width: '10%',
    textAlign: 'right',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  emptyTd: {
    textAlign: 'center',
    padding: '40px',
    color: tokens.colorNeutralForeground3,
  },
  tbodyTr: {
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    transition: 'background-color 0.15s ease',
  },
  tdDetails: {
    padding: '12px 18px',
    verticalAlign: 'middle',
  },
  prodDetailsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  prodThumbnailWrap: {
    width: '44px',
    height: '44px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    flexShrink: 0,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
  },
  prodTextCol: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  prodTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
  },
  prodDesc: {
    color: tokens.colorNeutralForeground2,
    maxWidth: '240px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  tdCell: {
    padding: '12px 14px',
    verticalAlign: 'middle',
  },
  badgeRow: {
    display: 'flex',
    gap: '6px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  catSub: {
    color: tokens.colorNeutralForeground3,
  },
  costCaption: {
    color: tokens.colorNeutralForeground2,
    fontWeight: 600,
  },
  stockBadge: {
    fontWeight: 700,
  },
  skuCol: {
    display: 'flex',
    flexDirection: 'column',
  },
  skuCode: {
    fontFamily: tokens.fontFamilyMonospace,
    fontWeight: 600,
  },
  rackText: {
    color: tokens.colorNeutralForeground3,
  },
  tdActions: {
    padding: '12px 18px',
    verticalAlign: 'middle',
    textAlign: 'right',
  },
  actionsRow: {
    display: 'flex',
    gap: '6px',
    justifyContent: 'flex-end',
  },
  deleteIcon: {
    color: '#D13438',
  },

  // Modal styles (Product Dialog & Category Dialog)
  modalForm: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
  },
  modalBody: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    padding: 0,
  },
  modalHeader: {
    marginBottom: '10px',
    paddingBottom: '8px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    flexShrink: 0,
  },
  dialogTitle: {
    fontSize: '18px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    margin: 0,
  },
  dialogSub: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground2,
    marginTop: '2px',
  },
  dialogContentGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 280px',
    gap: '18px',
    alignItems: 'start',
    paddingRight: '4px',
    overflowY: 'auto',
  },
  formColLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  formGrid2Col: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  formBottomAlign: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
  },
  categoryHeaderRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginBottom: '6px',
  },
  newCategoryLink: {
    fontSize: '11.5px',
    color: '#E51937',
    fontWeight: 700,
    cursor: 'pointer',
  },
  formColRight: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    width: '280px',
  },
  uploadCard: {
    backgroundColor: tokens.colorNeutralBackground2,
    borderRadius: '12px',
    padding: '12px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
  },
  uploadLabel: {
    display: 'block',
    marginBottom: '8px',
    fontWeight: 700,
    fontSize: '12px',
  },
  hiddenInput: {
    display: 'none',
  },
  attachedRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 10px',
    borderRadius: '8px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  attachedThumb: {
    width: '46px',
    height: '46px',
    borderRadius: '6px',
    overflow: 'hidden',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    flexShrink: 0,
    backgroundColor: '#1E1E1E',
  },
  attachedInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    flex: 1,
    minWidth: 0,
  },
  attachedTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
  },
  attachedPath: {
    fontSize: '10.5px',
    color: tokens.colorNeutralForeground3,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  attachedActions: {
    display: 'flex',
    gap: '2px',
    alignItems: 'center',
  },
  changeBtn: {
    minWidth: 'auto',
    padding: '3px 8px',
    fontSize: '11px',
  },
  dropzone: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '5px',
    padding: '14px 10px',
    borderRadius: '8px',
    borderTopWidth: '1.5px', borderBottomWidth: '1.5px', borderLeftWidth: '1.5px', borderRightWidth: '1.5px',
    borderTopStyle: 'dashed', borderBottomStyle: 'dashed', borderLeftStyle: 'dashed', borderRightStyle: 'dashed',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    ':hover': {
      borderTopColor: '#E51937', borderBottomColor: '#E51937', borderLeftColor: '#E51937', borderRightColor: '#E51937',
      backgroundColor: 'rgba(229, 25, 55, 0.04)',
    },
  },
  uploadIcon: {
    width: '24px',
    height: '24px',
    color: '#E51937',
  },
  uploadTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
  },
  uploadSub: {
    fontSize: '10.5px',
    color: tokens.colorNeutralForeground3,
  },
  urlWrap: {
    marginTop: '8px',
  },
  previewCard: {
    backgroundColor: tokens.colorNeutralBackground2,
    borderRadius: '12px',
    padding: '12px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
  },
  previewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  previewHeadTitle: {
    fontSize: '10.5px',
    fontWeight: 800,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    color: tokens.colorNeutralForeground2,
  },
  previewHeadSub: {
    fontSize: '10.5px',
    color: tokens.colorNeutralForeground3,
  },
  posMockup: {
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: '10px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    overflow: 'hidden',
    boxShadow: '0 4px 14px rgba(0, 0, 0, 0.12)',
    display: 'flex',
    flexDirection: 'column',
  },
  mockupMedia: {
    height: '114px',
    width: '100%',
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: '#18181B',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noPhotoMockup: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '3px',
    color: '#71717A',
  },
  mockupCatBadge: {
    position: 'absolute',
    top: '6px',
    left: '6px',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    color: '#FFFFFF',
    padding: '2px 6px',
    borderRadius: '4px',
    fontSize: '9.5px',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  mockupStockBadge: {
    position: 'absolute',
    top: '6px',
    right: '6px',
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    padding: '2px 6px',
    borderRadius: '4px',
    fontSize: '9.5px',
    fontWeight: 800,
  },
  mockupContent: {
    height: '76px',
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    boxSizing: 'border-box',
  },
  mockupName: {
    fontWeight: 800,
    fontSize: '12.5px',
    color: tokens.colorNeutralForeground1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  mockupBottom: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '2px',
  },
  mockupPriceLabel: {
    fontSize: '9px',
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase',
    fontWeight: 600,
  },
  mockupPriceVal: {
    fontWeight: 900,
    fontSize: '14.5px',
    color: '#E51937',
  },
  mockupUnitTag: {
    fontSize: '10px',
    fontWeight: 700,
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    color: '#E51937',
    padding: '2px 7px',
    borderRadius: '4px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.2)', borderBottomColor: 'rgba(229, 25, 55, 0.2)',
    borderLeftColor: 'rgba(229, 25, 55, 0.2)', borderRightColor: 'rgba(229, 25, 55, 0.2)',
  },
  dialogFooterActions: {
    marginTop: 'auto',
    paddingTop: '10px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    display: 'flex',
    gap: '10px',
    justifyContent: 'flex-end',
    alignItems: 'center',
    flexShrink: 0,
  },
  dialogCancelBtn: {
    borderRadius: '8px',
    fontWeight: 600,
    padding: '8px 18px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    whiteSpace: 'nowrap',
  },
  dialogSubmitBtn: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: '8px',
    fontWeight: 700,
    padding: '9px 24px',
    minWidth: '150px',
    whiteSpace: 'nowrap',
    borderTopStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none', borderRightStyle: 'none',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.25)',
    ':hover': {
      backgroundColor: '#C6172E',
    },
  },

  // Category Dialog styles
  catDialogSurface: {
    maxWidth: '460px',
    width: '92vw',
    borderRadius: '16px',
    padding: '24px',
    boxSizing: 'border-box',
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    boxShadow: '0 24px 64px rgba(0, 0, 0, 0.5)',
    display: 'flex',
    flexDirection: 'column',
  },
  catForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '18px',
    width: '100%',
  },
  catHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '14px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    width: '100%',
  },
  catHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  catIconWrap: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#E51937',
  },
  catTitle: {
    fontSize: '17px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  catDialogSub: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  catFieldsCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: '100%',
  },
  catFooter: {
    display: 'flex',
    gap: '10px',
    justifyContent: 'flex-end',
    marginTop: '6px',
    paddingTop: '14px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    width: '100%',
  },
  catCancelBtn: {
    borderRadius: '8px',
    fontWeight: 600,
    padding: '8px 18px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    whiteSpace: 'nowrap',
  },
  catSubmitBtn: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: '8px',
    fontWeight: 700,
    padding: '9px 22px',
    minWidth: '130px',
    whiteSpace: 'nowrap',
    borderTopStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none', borderRightStyle: 'none',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.25)',
    ':hover': {
      backgroundColor: '#C6172E',
    },
  },
  catFormHintRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '5px',
  },
  catFormHintText: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  catFormToggleBtn: {
    backgroundColor: 'transparent',
    borderTopStyle: 'none', borderBottomStyle: 'none',
    borderLeftStyle: 'none', borderRightStyle: 'none',
    color: '#E51937',
    fontSize: '11.5px',
    fontWeight: 700,
    cursor: 'pointer',
    padding: 0,
  },
  presetInfoBox: {
    padding: '8px 10px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  presetChipRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    flexWrap: 'wrap',
  },
  presetChipLabel: {
    fontSize: '10.5px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground3,
  },
  presetUnitChip: {
    fontSize: '10.5px',
    fontWeight: 600,
    padding: '1px 6px',
    borderRadius: '4px',
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    color: tokens.colorNeutralForeground1,
  },
});

export const useStyles = useProductsCatalogStyles;
