import { makeStyles, tokens } from '@fluentui/react-components';

export const useProductDetailsStyles = makeStyles({
  container: {
    padding: '24px 32px',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    backgroundColor: tokens.colorNeutralBackground2,
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  topBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    flexWrap: 'wrap',
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    backgroundColor: 'transparent',
    border: 'none',
    color: tokens.colorNeutralForeground2,
    padding: '6px 10px',
    borderRadius: '6px',
    transition: 'all 0.15s ease',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
      color: tokens.colorNeutralForeground1,
    },
  },
  actionsGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  heroCard: {
    display: 'grid',
    gridTemplateColumns: '240px 1fr',
    gap: '28px',
    padding: '24px',
    borderRadius: '12px',
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    '@media (max-width: 860px)': {
      gridTemplateColumns: '1fr',
    },
  },
  imageBox: {
    width: '100%',
    height: '240px',
    borderRadius: '10px',
    overflow: 'hidden',
    backgroundColor: tokens.colorNeutralBackground3,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    position: 'relative',
  },
  productImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  noPhotoBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    color: tokens.colorNeutralForeground4,
  },
  heroInfo: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: '16px',
  },
  titleHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  badgeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  productTitle: {
    fontSize: '26px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    margin: 0,
    lineHeight: 1.2,
  },
  productDesc: {
    fontSize: '13.5px',
    color: tokens.colorNeutralForeground3,
    lineHeight: 1.5,
    margin: 0,
  },
  skuBarcodeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '10px 14px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
    border: `1px dashed ${tokens.colorNeutralStroke1}`,
    width: 'fit-content',
  },
  skuPill: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  skuLabel: {
    fontSize: '10px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground4,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  skuValue: {
    fontSize: '13px',
    fontWeight: 700,
    fontFamily: 'monospace',
    color: tokens.colorNeutralForeground1,
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '16px',
  },
  kpiCard: {
    borderRadius: '10px',
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow2,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    padding: '16px 18px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    position: 'relative',
    overflow: 'hidden',
  },
  kpiTopStripeRed: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '3px',
    backgroundColor: '#E51937',
  },
  kpiTopStripeGreen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '3px',
    backgroundColor: '#10B981',
  },
  kpiTopStripeBlue: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '3px',
    backgroundColor: '#2563EB',
  },
  kpiTopStripeAmber: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '3px',
    backgroundColor: '#F59E0B',
  },
  kpiLabel: {
    fontSize: '11.5px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  kpiValue: {
    fontSize: '22px',
    fontWeight: 900,
    color: tokens.colorNeutralForeground1,
    lineHeight: 1.1,
  },
  kpiSubtext: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground4,
  },
  contentGrid: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    gap: '20px',
    '@media (max-width: 960px)': {
      gridTemplateColumns: '1fr',
    },
  },
  sectionCard: {
    borderRadius: '12px',
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  sectionTitle: {
    fontSize: '15px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '12.5px',
  },
  th: {
    textAlign: 'left',
    padding: '8px 12px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground3,
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground3,
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  td: {
    padding: '10px 12px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke3}`,
    color: tokens.colorNeutralForeground1,
  },
  tagList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  tagItem: {
    padding: '3px 10px',
    borderRadius: '12px',
    fontSize: '11px',
    fontWeight: 600,
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground2,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  kitchenInfoGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  kitchenInfoBox: {
    padding: '12px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  kitchenLabel: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground4,
    fontWeight: 600,
  },
  kitchenValue: {
    fontSize: '14px',
    color: tokens.colorNeutralForeground1,
    fontWeight: 700,
  },
  loadingWrap: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '60vh',
  },
});
