import { makeStyles, tokens } from '@fluentui/react-components';

export const useQuotationsStyles = makeStyles({
  container: {
    padding: '24px',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    backgroundColor: tokens.colorNeutralBackground2,
    overflowY: 'auto',
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '16px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  iconBox: {
    width: '46px',
    height: '46px',
    borderRadius: '12px',
    backgroundColor: 'rgba(229, 25, 55, 0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#E51937',
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '14px',
  },
  kpiCard: {
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: '12px',
    padding: '16px 18px',
    borderTopWidth: '1px', borderRightWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px',
    borderTopStyle: 'solid', borderRightStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2, borderLeftColor: tokens.colorNeutralStroke2,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    boxShadow: tokens.shadow2,
  },
  kpiTitle: {
    fontSize: '11.5px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  kpiValue: {
    fontSize: '22px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  kpiSub: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground4,
  },
  filterBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
  },
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px', borderRightWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px',
    borderTopStyle: 'solid', borderRightStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2, borderLeftColor: tokens.colorNeutralStroke2,
    borderRadius: '8px',
    padding: '0 12px',
    height: '38px',
    flex: '1',
    maxWidth: '380px',
  },
  searchInput: {
    border: 'none',
    outline: 'none',
    backgroundColor: 'transparent',
    fontSize: '13px',
    color: tokens.colorNeutralForeground1,
    marginLeft: '8px',
    width: '100%',
  },
  statusTabs: {
    display: 'flex',
    gap: '6px',
    backgroundColor: tokens.colorNeutralBackground1,
    padding: '4px',
    borderRadius: '8px',
    borderTopWidth: '1px', borderRightWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px',
    borderTopStyle: 'solid', borderRightStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2, borderLeftColor: tokens.colorNeutralStroke2,
  },
  statusTab: {
    border: 'none',
    backgroundColor: 'transparent',
    padding: '5px 12px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    color: tokens.colorNeutralForeground3,
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground2,
    },
  },
  statusTabActive: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    ':hover': {
      backgroundColor: '#C4122C',
    },
  },
  tableCard: {
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: '12px',
    borderTopWidth: '1px', borderRightWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px',
    borderTopStyle: 'solid', borderRightStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2, borderLeftColor: tokens.colorNeutralStroke2,
    overflow: 'hidden',
    boxShadow: tokens.shadow2,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
  },
  th: {
    backgroundColor: tokens.colorNeutralBackground3,
    padding: '12px 16px',
    fontSize: '11.5px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  td: {
    padding: '14px 16px',
    fontSize: '12.5px',
    color: tokens.colorNeutralForeground1,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  tr: {
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground2,
    },
  },
  actionBtn: {
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    padding: '6px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground3,
    },
  },
  dialogSurface: {
    maxWidth: '850px',
    width: '100%',
    borderRadius: '14px',
    padding: '24px',
    maxHeight: '92vh',
    overflowY: 'auto',
  },
  titleBold: {
    fontWeight: 800,
  },
  captionMuted: {
    color: tokens.colorNeutralForeground3,
  },
  btnPrimaryRed: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    fontWeight: 700,
    borderRadius: '8px',
  },
  iconSky: {
    color: '#0284C7',
  },
  iconAmber: {
    color: '#F59E0B',
  },
  iconEmerald: {
    color: '#10B981',
  },
  kpiValueEmerald: {
    color: '#10B981',
  },
  iconRed: {
    color: '#E51937',
  },
  kpiValueRed: {
    color: '#E51937',
  },
  iconMuted: {
    color: tokens.colorNeutralForeground4,
  },
  thRight: {
    textAlign: 'right',
  },
  thCenter: {
    textAlign: 'center',
  },
  loadingTd: {
    padding: '30px',
    textAlign: 'center',
    color: tokens.colorNeutralForeground3,
  },
  emptyTd: {
    padding: '40px',
    textAlign: 'center',
  },
  emptyIcon: {
    fontSize: '36px',
    color: tokens.colorNeutralForeground4,
    marginBottom: '8px',
  },
  emptyTitle: {
    fontWeight: 700,
    fontSize: '14px',
    color: tokens.colorNeutralForeground2,
  },
  emptySub: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground4,
    marginTop: '2px',
  },
  quoteNumberText: {
    fontWeight: 800,
    color: '#E51937',
  },
  moduleMuted: {
    fontSize: '10.5px',
    color: tokens.colorNeutralForeground4,
  },
  customerNameBold: {
    fontWeight: 700,
  },
  customerPhoneMuted: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  validityText: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  fontSemiBold: {
    fontWeight: 600,
  },
  lineOverviewText: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground4,
    maxWidth: '220px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  totalPriceCell: {
    textAlign: 'right',
    fontWeight: 800,
    fontSize: '13px',
  },
  statusPill: {
    fontSize: '11px',
    padding: '3px 10px',
    borderRadius: '999px',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  statusConverted: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    color: '#059669',
  },
  statusSent: {
    backgroundColor: 'rgba(2, 132, 199, 0.12)',
    color: '#0284C7',
  },
  statusPending: {
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    color: '#D97706',
  },
  actionGroup: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '4px',
  },
  printIcon: {
    color: '#0284C7',
  },
  convertIcon: {
    color: '#10B981',
  },
  editIcon: {
    color: tokens.colorNeutralForeground3,
  },
  deleteIcon: {
    color: '#EF4444',
  },
  dialogHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '18px',
  },
  dialogHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  dialogHeaderIconBox: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#E51937',
  },
  dialogTitleText: {
    fontSize: '17px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  dialogSubText: {
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground3,
  },
  dialogFormGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '14px',
    marginBottom: '16px',
  },
  itemsSection: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    paddingTop: '16px',
    marginBottom: '14px',
  },
  itemsHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  itemsSectionTitle: {
    fontWeight: 800,
    fontSize: '13.5px',
    color: tokens.colorNeutralForeground1,
  },
  addCustomBtn: {
    color: '#E51937',
    fontWeight: 700,
  },
  searchScannerContainer: {
    marginBottom: '14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  searchScannerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  flex1: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '0%',
  },
  scannerBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    padding: '8px 12px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground3,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    fontWeight: 600,
    whiteSpace: 'nowrap',
  },
  scannerIcon: {
    width: '16px',
    height: '16px',
    color: '#E51937',
  },
  scannerToast: {
    padding: '6px 12px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
  },
  scannerToastSuccess: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderTopColor: '#10B981', borderBottomColor: '#10B981', borderLeftColor: '#10B981', borderRightColor: '#10B981',
    color: '#059669',
  },
  scannerToastError: {
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderTopColor: '#EF4444', borderBottomColor: '#EF4444', borderLeftColor: '#EF4444', borderRightColor: '#EF4444',
    color: '#DC2626',
  },
  scannerToastIcon: {
    width: '16px',
    height: '16px',
  },
  lineItemsTableWrap: {
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    borderRadius: '8px',
    overflow: 'hidden',
  },
  lineItemsTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '12px',
  },
  lineItemsTheadTr: {
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground2,
  },
  thItemName: {
    padding: '8px 12px',
    textAlign: 'left',
  },
  thSpecUnit: {
    padding: '8px 8px',
    textAlign: 'left',
    width: '130px',
  },
  thQty: {
    padding: '8px 8px',
    textAlign: 'center',
    width: '80px',
  },
  thRate: {
    padding: '8px 12px',
    textAlign: 'right',
    width: '120px',
  },
  thLineTotal: {
    padding: '8px 12px',
    textAlign: 'right',
    width: '120px',
  },
  thDeleteCol: {
    padding: '8px 6px',
    textAlign: 'center',
    width: '40px',
  },
  emptyLinesTd: {
    padding: '24px',
    textAlign: 'center',
    color: tokens.colorNeutralForeground4,
  },
  lineItemTr: {
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  tdItemName: {
    padding: '6px 12px',
  },
  inputItemName: {
    width: '100%',
    padding: '4px 8px',
    borderRadius: '4px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    fontSize: '12px',
  },
  tdSpecUnit: {
    padding: '6px 8px',
  },
  inputSpecUnit: {
    width: '100%',
    padding: '4px 8px',
    borderRadius: '4px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    fontSize: '12px',
  },
  tdQty: {
    padding: '6px 8px',
    textAlign: 'center',
  },
  inputQty: {
    width: '60px',
    padding: '4px 6px',
    borderRadius: '4px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    textAlign: 'center',
    fontSize: '12px',
    fontWeight: 700,
  },
  tdRate: {
    padding: '6px 12px',
    textAlign: 'right',
  },
  inputRate: {
    width: '100px',
    padding: '4px 6px',
    borderRadius: '4px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    textAlign: 'right',
    fontSize: '12px',
    fontWeight: 700,
  },
  tdLineTotal: {
    padding: '6px 12px',
    textAlign: 'right',
    fontWeight: 800,
    color: '#E51937',
  },
  tdDeleteCol: {
    padding: '6px 6px',
    textAlign: 'center',
  },
  deleteLineBtn: {
    borderTopStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none', borderRightStyle: 'none',
    backgroundColor: 'transparent',
    color: '#EF4444',
    cursor: 'pointer',
    padding: '4px',
  },
  bottomTotalsBar: {
    backgroundColor: tokens.colorNeutralBackground2,
    borderRadius: '10px',
    padding: '14px 18px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '20px',
    marginBottom: '18px',
  },
  notesCol: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '0%',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  noteInput: {
    padding: '6px 10px',
    borderRadius: '6px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    fontSize: '11.5px',
    width: '100%',
    boxSizing: 'border-box',
  },
  calcBox: {
    width: '260px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    textAlign: 'right',
  },
  calcRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '12px',
  },
  calcRowCenter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '12px',
  },
  colorMuted3: {
    color: tokens.colorNeutralForeground3,
  },
  discountInput: {
    width: '60px',
    padding: '2px 6px',
    borderRadius: '4px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    textAlign: 'right',
    fontSize: '12px',
    fontWeight: 700,
  },
  grandTotalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    paddingTop: '6px',
    borderTopWidth: '1.5px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
    fontSize: '15px',
    fontWeight: 900,
    color: '#E51937',
  },
  dialogActionsRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  btnSaveFinalize: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    fontWeight: 700,
  },
});

export const useStyles = useQuotationsStyles;
