import { makeStyles, tokens } from '@fluentui/react-components';

export const useKhataStyles = makeStyles({
  container: {
    padding: '28px 32px',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    backgroundColor: tokens.colorNeutralBackground2,
    overflowY: 'auto',
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '20px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
  },
  summaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '16px',
  },
  statCard: {
    backgroundColor: tokens.colorNeutralBackground1,
    padding: '18px 20px',
    borderRadius: '12px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    boxShadow: tokens.shadow4,
  },
  tableCard: {
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: '12px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    boxShadow: tokens.shadow4,
    overflow: 'hidden',
  },
  filterBar: {
    padding: '16px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    gap: '12px',
  },

  headerTitle: {
    fontWeight: 700,
    fontSize: '20px',
    color: tokens.colorNeutralForeground1,
    margin: 0,
    display: 'block',
  },
  headerSubtitle: {
    color: tokens.colorNeutralForeground2,
    display: 'block',
    marginTop: '4px',
    fontSize: '13px',
  },
  addCustomerBtn: {
    backgroundColor: '#E51937',
    borderRadius: tokens.borderRadiusMedium,
    fontWeight: 700,
    ':hover': {
      backgroundColor: '#C6172E',
    },
  },
  statLabel: {
    color: tokens.colorNeutralForeground2,
    display: 'block',
    fontWeight: 600,
  },
  statVal: {
    fontSize: '28px',
    fontWeight: 800,
    marginTop: '6px',
    display: 'block',
    color: tokens.colorNeutralForeground1,
  },
  statValRed: {
    color: '#E51937',
  },
  statValBrand: {
    color: tokens.colorBrandForeground1,
  },
  statValWarn: {
    color: '#D97706',
  },
  statValSuccess: {
    color: '#107C41',
  },
  statSub: {
    color: tokens.colorNeutralForeground3,
  },
  searchWrap: {
    width: '320px',
  },
  filterWrap: {
    width: '220px',
  },
  tableWrapper: {
    overflowX: 'auto',
    width: '100%',
  },
  table: {
    width: '100%',
    minWidth: '980px',
    borderCollapse: 'separate',
    borderSpacing: 0,
  },
  tableHeaderRow: {
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  thProfile: {
    padding: '14px 20px',
    width: '27%',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  thContact: {
    padding: '14px 16px',
    width: '18%',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  thUsage: {
    padding: '14px 16px',
    width: '20%',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  thDebt: {
    padding: '14px 16px',
    width: '14%',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  thActions: {
    padding: '14px 20px',
    width: '21%',
    textAlign: 'right',
    fontWeight: 700,
    fontSize: '11.5px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: tokens.colorNeutralForeground2,
  },
  emptyTableCell: {
    textAlign: 'center',
    padding: '40px',
    color: tokens.colorNeutralForeground3,
  },
  tableBodyRow: {
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    transition: 'background-color 0.15s ease',
  },
  tdProfile: {
    padding: '14px 20px',
    verticalAlign: 'middle',
  },
  avatarWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  profileAvatar: {
    width: '42px',
    height: '42px',
    borderRadius: '10px',
    background: 'linear-gradient(135deg, rgba(229, 25, 55, 0.12) 0%, rgba(229, 25, 55, 0.04) 100%)',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.2)', borderBottomColor: 'rgba(229, 25, 55, 0.2)',
    borderLeftColor: 'rgba(229, 25, 55, 0.2)', borderRightColor: 'rgba(229, 25, 55, 0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#E51937',
    fontWeight: 800,
    fontSize: '14px',
    flexShrink: 0,
  },
  profileInfoCol: {
    minWidth: 0,
  },
  profileTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
  },
  profileName: {
    fontWeight: 700,
    fontSize: '14px',
    color: tokens.colorNeutralForeground1,
  },
  profileBadge: {
    textTransform: 'uppercase',
    fontSize: '10px',
    fontWeight: 700,
  },
  profileAddressRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginTop: '3px',
    color: tokens.colorNeutralForeground3,
    fontSize: '11.5px',
  },
  locationIcon: {
    width: '13px',
    height: '13px',
    flexShrink: 0,
  },
  addressText: {
    maxWidth: '200px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  tdCell: {
    padding: '14px 16px',
    verticalAlign: 'middle',
  },
  colGap3: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  contactPhone: {
    fontWeight: 600,
    fontSize: '13px',
    color: tokens.colorNeutralForeground1,
  },
  contactCnic: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    fontFamily: 'monospace',
    backgroundColor: tokens.colorNeutralBackground3,
    padding: '2px 6px',
    borderRadius: '4px',
    width: 'fit-content',
  },
  usageContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    minWidth: '150px',
  },
  usageHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '11.5px',
  },
  usagePercent: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
  },
  usagePercentOver: {
    color: '#DC2626',
  },
  usagePercentNear: {
    color: '#D97706',
  },
  usageCap: {
    color: tokens.colorNeutralForeground3,
    fontSize: '11px',
  },
  progressBarTrack: {
    width: '100%',
    height: '6px',
    backgroundColor: tokens.colorNeutralBackground3,
    borderRadius: '999px',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: '999px',
    transition: 'width 0.3s ease',
  },
  progressBarNormal: {
    backgroundColor: '#107C41',
  },
  progressBarWarn: {
    backgroundColor: '#F59E0B',
  },
  progressBarAlert: {
    backgroundColor: '#DC2626',
  },
  debtBadge: {
    display: 'inline-block',
    padding: '4px 10px',
    borderRadius: '8px',
    fontWeight: 800,
    fontSize: '13px',
    width: 'fit-content',
  },
  debtBadgeDue: {
    backgroundColor: '#FEF2F2',
    color: '#DC2626',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#FECACA', borderBottomColor: '#FECACA', borderLeftColor: '#FECACA', borderRightColor: '#FECACA',
  },
  debtBadgeClear: {
    backgroundColor: '#F0FDF4',
    color: '#16A34A',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#BBF7D0', borderBottomColor: '#BBF7D0', borderLeftColor: '#BBF7D0', borderRightColor: '#BBF7D0',
  },
  termText: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  tdActions: {
    padding: '14px 20px',
    verticalAlign: 'middle',
    textAlign: 'right',
  },
  actionsGroup: {
    display: 'flex',
    gap: '6px',
    justifyContent: 'flex-end',
    alignItems: 'center',
    whiteSpace: 'nowrap',
  },
  btnPassbook: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '6px 10px',
    borderRadius: '7px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  btnReceive: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '6px 11px',
    borderRadius: '7px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#A7F3D0', borderBottomColor: '#A7F3D0',
    borderLeftColor: '#A7F3D0', borderRightColor: '#A7F3D0',
    backgroundColor: '#ECFDF5',
    color: '#047857',
    fontSize: '12px',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  btnUdhaar: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '6px 11px',
    borderRadius: '7px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#FECACA', borderBottomColor: '#FECACA',
    borderLeftColor: '#FECACA', borderRightColor: '#FECACA',
    backgroundColor: '#FEF2F2',
    color: '#DC2626',
    fontSize: '12px',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  btnWhatsApp: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    borderRadius: '7px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#BBF7D0', borderBottomColor: '#BBF7D0',
    borderLeftColor: '#BBF7D0', borderRightColor: '#BBF7D0',
    backgroundColor: '#F0FDF4',
    color: '#16A34A',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  btnDelete: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    borderRadius: '7px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    backgroundColor: 'transparent',
    color: tokens.colorNeutralForeground3,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  icon15: {
    width: '15px',
    height: '15px',
  },
  icon16: {
    width: '16px',
    height: '16px',
  },
  dialogSurface520: {
    borderRadius: tokens.borderRadiusLarge,
    maxWidth: '520px',
  },
  dialogTitleBold: {
    fontWeight: 800,
  },
  dialogContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    marginTop: '12px',
  },
  grid2Col: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  dialogActions: {
    marginTop: '24px',
    display: 'flex',
    gap: '10px',
    justifyContent: 'flex-end',
  },
  modalCancelBtn: {
    borderRadius: '8px',
    fontWeight: 600,
    padding: '8px 18px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    whiteSpace: 'nowrap',
  },
  modalSubmitBtn: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: '8px',
    fontWeight: 700,
    padding: '9px 22px',
    minWidth: '140px',
    whiteSpace: 'nowrap',
    borderTopStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none', borderRightStyle: 'none',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.25)',
    ':hover': {
      backgroundColor: '#C6172E',
    },
  },
  dialogSurface440: {
    borderRadius: tokens.borderRadiusLarge,
    maxWidth: '440px',
  },
  selectedCustCard: {
    padding: '12px',
    backgroundColor: tokens.colorNeutralBackground3,
    borderRadius: '8px',
  },
  selectedCustTitle: {
    fontWeight: 700,
  },
  selectedCustSub: {
    color: tokens.colorNeutralForeground2,
    display: 'block',
  },
  currentBalStrong: {
    color: '#E51937',
  },
  transSubmitGreen: {
    backgroundColor: '#107C41',
    color: '#FFFFFF',
    borderRadius: '8px',
    fontWeight: 700,
    padding: '9px 22px',
    minWidth: '160px',
    whiteSpace: 'nowrap',
    borderTopStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none', borderRightStyle: 'none',
    boxShadow: '0 2px 8px rgba(16, 124, 65, 0.25)',
    ':hover': {
      backgroundColor: '#0D6535',
    },
  },
  transSubmitRed: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: '8px',
    fontWeight: 700,
    padding: '9px 22px',
    minWidth: '160px',
    whiteSpace: 'nowrap',
    borderTopStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none', borderRightStyle: 'none',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.25)',
    ':hover': {
      backgroundColor: '#C6172E',
    },
  },
  passbookSurface: {
    borderRadius: '16px',
    maxWidth: '920px',
    minWidth: '780px',
    width: '92vw',
    padding: '24px',
  },
  passbookInner: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    width: '100%',
  },
  passbookHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '14px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    gap: '16px',
    width: '100%',
  },
  passbookTitleCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  passbookTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  passbookTitle: {
    fontWeight: 800,
    fontSize: '20px',
    margin: 0,
    padding: 0,
    color: tokens.colorNeutralForeground1,
    whiteSpace: 'nowrap',
  },
  passbookStatusBadge: {
    fontSize: '11px',
    fontWeight: 700,
    padding: '3px 10px',
    borderRadius: '9999px',
    whiteSpace: 'nowrap',
  },
  passbookStatusDue: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    color: '#EF4444',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(239, 68, 68, 0.3)', borderBottomColor: 'rgba(239, 68, 68, 0.3)',
    borderLeftColor: 'rgba(239, 68, 68, 0.3)', borderRightColor: 'rgba(239, 68, 68, 0.3)',
  },
  passbookStatusSettled: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    color: '#10B981',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(16, 185, 129, 0.3)', borderBottomColor: 'rgba(16, 185, 129, 0.3)',
    borderLeftColor: 'rgba(16, 185, 129, 0.3)', borderRightColor: 'rgba(16, 185, 129, 0.3)',
  },
  passbookSubtitle: {
    color: tokens.colorNeutralForeground2,
    marginTop: '2px',
    fontSize: '13px',
  },
  passbookActionsRow: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
    flexShrink: 0,
  },
  passbookPrintBtn: {
    borderRadius: '8px',
    fontWeight: 600,
    whiteSpace: 'nowrap',
  },
  passbookWhatsAppBtn: {
    backgroundColor: '#25D366',
    color: '#FFFFFF',
    fontWeight: 700,
    borderRadius: '8px',
    borderTopStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none', borderRightStyle: 'none',
    boxShadow: '0 2px 8px rgba(37, 211, 102, 0.25)',
    whiteSpace: 'nowrap',
    ':hover': {
      backgroundColor: '#1EBE5D',
    },
  },
  passbookMetricGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '12px',
    width: '100%',
  },
  passbookStatCard: {
    padding: '12px 14px',
    borderRadius: '10px',
    backgroundColor: tokens.colorNeutralBackground3,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  passbookStatCardAlert: {
    padding: '12px 14px',
    borderRadius: '10px',
    backgroundColor: 'rgba(229, 25, 55, 0.08)',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.25)', borderBottomColor: 'rgba(229, 25, 55, 0.25)',
    borderLeftColor: 'rgba(229, 25, 55, 0.25)', borderRightColor: 'rgba(229, 25, 55, 0.25)',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  passbookStatTitle: {
    color: tokens.colorNeutralForeground3,
    fontWeight: 700,
    fontSize: '11px',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  passbookStatTitleAlert: {
    color: '#EF4444',
    fontWeight: 700,
    fontSize: '11px',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  passbookStatVal: {
    fontSize: '16px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    fontFamily: tokens.fontFamilyMonospace,
    whiteSpace: 'nowrap',
  },
  passbookStatValRed: {
    fontSize: '16px',
    fontWeight: 800,
    color: '#EF4444',
    fontFamily: tokens.fontFamilyMonospace,
    whiteSpace: 'nowrap',
  },
  passbookStatValGreen: {
    fontSize: '16px',
    fontWeight: 800,
    color: '#10B981',
    fontFamily: tokens.fontFamilyMonospace,
    whiteSpace: 'nowrap',
  },
  passbookStatValNet: {
    fontSize: '18px',
    fontWeight: 900,
    color: '#E51937',
    fontFamily: tokens.fontFamilyMonospace,
    whiteSpace: 'nowrap',
  },
  passbookTableWrap: {
    maxHeight: '400px',
    overflowY: 'auto',
    paddingRight: '2px',
    width: '100%',
  },
  passbookLoadingText: {
    padding: '40px',
    textAlign: 'center',
    color: tokens.colorNeutralForeground2,
  },
  passbookEmptyText: {
    padding: '40px',
    textAlign: 'center',
    color: tokens.colorNeutralForeground3,
  },
  passbookTableCard: {
    borderRadius: '10px',
    overflow: 'hidden',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  passbookTable: {
    width: '100%',
    tableLayout: 'fixed',
    borderCollapse: 'separate',
    borderSpacing: 0,
  },
  passbookTheadTr: {
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  passbookThDate: {
    padding: '12px 14px',
    fontWeight: 700,
    fontSize: '11px',
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground2,
    width: '140px',
    whiteSpace: 'nowrap',
  },
  passbookThDesc: {
    padding: '12px 14px',
    fontWeight: 700,
    fontSize: '11px',
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground2,
    width: 'auto',
  },
  passbookThDebit: {
    padding: '12px 14px',
    textAlign: 'right',
    fontWeight: 700,
    fontSize: '11px',
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground2,
    width: '130px',
    whiteSpace: 'nowrap',
  },
  passbookThCredit: {
    padding: '12px 14px',
    textAlign: 'right',
    fontWeight: 700,
    fontSize: '11px',
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground2,
    width: '130px',
    whiteSpace: 'nowrap',
  },
  passbookThBal: {
    padding: '12px 14px',
    textAlign: 'right',
    fontWeight: 700,
    fontSize: '11px',
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground2,
    width: '120px',
    whiteSpace: 'nowrap',
  },
  passbookTbodyTr: {
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke3,
  },
  passbookTdDate: {
    padding: '12px 14px',
    fontSize: '12px',
    color: tokens.colorNeutralForeground2,
  },
  passbookDatePrimary: {
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    whiteSpace: 'nowrap',
  },
  passbookTimeSecondary: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    marginTop: '2px',
    whiteSpace: 'nowrap',
  },
  passbookTdDesc: {
    padding: '12px 14px',
  },
  passbookDescTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    fontSize: '13px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  passbookDescMode: {
    color: tokens.colorNeutralForeground3,
    textTransform: 'capitalize',
    marginTop: '2px',
    fontSize: '11px',
    whiteSpace: 'nowrap',
  },
  passbookTdRight: {
    padding: '12px 14px',
    textAlign: 'right',
  },
  passbookTdBal: {
    padding: '12px 14px',
    textAlign: 'right',
    fontWeight: 800,
    fontSize: '13px',
    fontFamily: tokens.fontFamilyMonospace,
    color: tokens.colorNeutralForeground1,
    whiteSpace: 'nowrap',
  },
  debitTag: {
    display: 'inline-flex',
    alignItems: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    color: '#EF4444',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(239, 68, 68, 0.25)', borderBottomColor: 'rgba(239, 68, 68, 0.25)',
    borderLeftColor: 'rgba(239, 68, 68, 0.25)', borderRightColor: 'rgba(239, 68, 68, 0.25)',
    padding: '4px 10px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 700,
    fontFamily: tokens.fontFamilyMonospace,
    whiteSpace: 'nowrap',
  },
  creditTag: {
    display: 'inline-flex',
    alignItems: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    color: '#10B981',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(16, 185, 129, 0.25)', borderBottomColor: 'rgba(16, 185, 129, 0.25)',
    borderLeftColor: 'rgba(16, 185, 129, 0.25)', borderRightColor: 'rgba(16, 185, 129, 0.25)',
    padding: '4px 10px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 700,
    fontFamily: tokens.fontFamilyMonospace,
    whiteSpace: 'nowrap',
  },
  dashText: {
    color: tokens.colorNeutralForeground3,
  },
  passbookFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: '8px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2,
  },
  passbookRecordCount: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  passbookCloseBtn: {
    borderRadius: '8px',
    fontWeight: 600,
    padding: '8px 20px',
  },
});

export const useStyles = useKhataStyles;
