import { makeStyles, tokens } from '@fluentui/react-components';

export const useAdminSettingsStyles = makeStyles({
  container: {
    padding: '28px 32px',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    backgroundColor: tokens.colorNeutralBackground2,
    overflowY: 'auto',
  },
  pageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingBottom: '20px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
  },
  pageTitle: {
    fontWeight: 700,
    fontSize: '20px',
    color: tokens.colorNeutralForeground1,
    margin: 0,
    display: 'block',
  },
  pageSubtitle: {
    color: tokens.colorNeutralForeground2,
    marginTop: '4px',
    marginBottom: 0,
    display: 'block',
    fontSize: '13px',
  },
  primaryRedButton: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: tokens.borderRadiusMedium,
    fontWeight: 700,
    whiteSpace: 'nowrap',
    flexShrink: 0,
    padding: '0 18px',
    height: '38px',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.3)',
    ':hover': {
      backgroundColor: '#C4122C',
      color: '#FFFFFF',
    },
  },
  saveButton: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: tokens.borderRadiusMedium,
    fontWeight: 600,
    whiteSpace: 'nowrap',
    flexShrink: 0,
    padding: '0 20px',
    height: '38px',
    ':hover': {
      backgroundColor: '#C4122C',
      color: '#FFFFFF',
    },
  },
  tabNavContainer: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    paddingBottom: '12px',
    flexWrap: 'wrap',
  },
  tabButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '9px 18px',
    borderRadius: tokens.borderRadiusMedium,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    fontWeight: 700,
    fontSize: '13px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    boxShadow: 'none',
    transition: 'all 0.15s ease',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  tabButtonActive: {
    borderTopWidth: '1.5px', borderBottomWidth: '1.5px', borderLeftWidth: '1.5px', borderRightWidth: '1.5px',
    borderTopColor: '#E51937', borderBottomColor: '#E51937', borderLeftColor: '#E51937', borderRightColor: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.08)',
    color: '#E51937',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.12)',
  },
  tabIcon: {
    width: '18px',
    height: '18px',
    color: 'inherit',
  },
  tabIconActive: {
    color: '#E51937',
  },
  tabBadge: {
    fontWeight: 700,
    whiteSpace: 'nowrap',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    color: '#E51937',
  },
  tabBadgeActive: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    fontWeight: 700,
    whiteSpace: 'nowrap',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))',
    gap: '16px',
    alignItems: 'start',
  },
  card: {
    padding: '0',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    borderTopWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderRightWidth: '1px',
    borderTopStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1,
    borderRightColor: tokens.colorNeutralStroke1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  cardHeader: {
    padding: '16px 20px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  cardHeaderBetween: {
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '12px',
  },
  cardIconBox: {
    width: '36px',
    height: '36px',
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorNeutralBackground3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    color: tokens.colorNeutralForeground2,
  },
  cardIconBoxRed: {
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    color: '#E51937',
  },
  cardIconBoxBlue: {
    backgroundColor: 'rgba(0, 120, 212, 0.1)',
    color: '#0078D4',
  },
  cardIconBoxGreen: {
    backgroundColor: 'rgba(16, 124, 65, 0.1)',
    color: '#107C41',
  },
  cardIconBoxOrange: {
    backgroundColor: 'rgba(217, 119, 6, 0.1)',
    color: '#D97706',
  },
  cardIconBoxPurple: {
    backgroundColor: 'rgba(136, 23, 152, 0.1)',
    color: '#881798',
  },
  backupGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: '16px',
  },
  backupActionCard: {
    padding: '20px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    boxShadow: tokens.shadow2,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: '14px',
    transition: 'all 0.15s ease',
    ':hover': {
      boxShadow: tokens.shadow4,
      borderTopColor: tokens.colorNeutralStroke1Hover,
      borderBottomColor: tokens.colorNeutralStroke1Hover,
      borderLeftColor: tokens.colorNeutralStroke1Hover,
      borderRightColor: tokens.colorNeutralStroke1Hover,
    },
  },
  icon20: {
    width: '20px',
    height: '20px',
  },
  headerFlex: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  headerTextCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  headerTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  headerTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    display: 'block',
    lineHeight: '20px',
  },
  headerBadge: {
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    color: '#E51937',
  },
  headerSubtitle: {
    color: tokens.colorNeutralForeground2,
    display: 'block',
    fontSize: '12px',
    lineHeight: '16px',
  },
  cardBody: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  formRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  segmentedGroup: {
    display: 'flex',
    borderRadius: tokens.borderRadiusSmall,
    overflow: 'hidden',
    borderTopWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderRightWidth: '1px',
    borderTopStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1,
    borderRightColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground3,
  },
  segmentedItem: {
    flex: 1,
    height: '32px',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.1s ease',
    fontFamily: 'inherit',
    fontSize: '13px',
  },
  segmentedItemActive: {
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    fontWeight: 700,
  },
  segmentedItemInactive: {
    backgroundColor: 'transparent',
    color: tokens.colorNeutralForeground2,
    fontWeight: 400,
  },
  switchRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: '6px',
    paddingBottom: '6px',
  },
  switchLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  switchRowTitle: {
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
  },
  switchRowDesc: {
    color: tokens.colorNeutralForeground2,
  },
  statusBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px',
    borderBottomWidth: '1px',
    borderLeftWidth: '1px',
    borderRightWidth: '1px',
    borderTopStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1,
    borderRightColor: tokens.colorNeutralStroke1,
  },
  tableWrapper: {
    overflowX: 'auto',
    width: '100%',
  },
  userTable: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
    fontSize: '13px',
  },
  th: {
    padding: '12px 16px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    backgroundColor: tokens.colorNeutralBackground3,
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  thRight: {
    textAlign: 'right',
  },
  td: {
    padding: '14px 16px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    color: tokens.colorNeutralForeground1,
    verticalAlign: 'middle',
  },
  tdRight: {
    textAlign: 'right',
  },
  tableRow: {
    transition: 'background-color 0.15s ease',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  userCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  userName: {
    fontWeight: 700,
    display: 'block',
    color: tokens.colorNeutralForeground1,
  },
  userPhone: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  usernamePill: {
    fontFamily: 'monospace',
    fontWeight: 700,
    backgroundColor: tokens.colorNeutralBackground3,
    padding: '2px 6px',
    borderRadius: '4px',
  },
  roleBadge: {
    fontWeight: 700,
    textTransform: 'uppercase',
    fontSize: '10px',
  },
  statusToggleBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  statusDotActive: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#10B981',
  },
  statusDotInactive: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#94A3B8',
  },
  statusTextActive: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#10B981',
  },
  statusTextInactive: {
    fontSize: '12px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
  },
  permissionsBadgeRow: {
    display: 'flex',
    gap: '4px',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  permissionsCountBadge: {
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    color: '#E51937',
  },
  permissionsListText: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  actionBtnsRow: {
    display: 'flex',
    gap: '6px',
    justifyContent: 'flex-end',
  },
  deleteIcon: {
    color: '#E51937',
  },
  engineCard: {
    padding: '16px',
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorNeutralBackground3,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    lineHeight: 1.6,
  },
  engineTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    display: 'block',
  },
  engineSubtitle: {
    color: tokens.colorNeutralForeground2,
    display: 'block',
    marginTop: '6px',
  },
  engineStatusRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    marginTop: '12px',
  },
  engineDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#107C41',
  },
  engineReadyText: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#107C41',
  },
  paperWidthLabel: {
    fontWeight: 600,
    color: tokens.colorNeutralForeground2,
  },
  testPrintRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  testPrintBtn: {
    color: tokens.colorNeutralForeground1,
    borderRadius: tokens.borderRadiusMedium,
    fontWeight: 600,
  },
  testPrintSuccess: {
    color: '#107C41',
    fontWeight: 600,
  },
  taxHelper: {
    color: tokens.colorNeutralForeground3,
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginTop: '4px',
  },
  icon12: {
    width: '12px',
    height: '12px',
  },
  statusBarLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  statusShieldIcon: {
    color: '#107C41',
    width: '18px',
    height: '18px',
  },
  statusTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    display: 'block',
  },
  statusSubtitle: {
    color: tokens.colorNeutralForeground2,
  },
  statusTerminalActive: {
    color: '#107C41',
    fontWeight: 600,
  },
  technicianBtn: {
    color: tokens.colorNeutralForeground3,
    fontSize: '12px',
  },
  dialogSurfaceLarge: {
    borderRadius: tokens.borderRadiusLarge,
    maxWidth: '640px',
    width: '100%',
    overflowX: 'hidden',
  },
  dialogSurfaceSmall: {
    borderRadius: tokens.borderRadiusLarge,
    maxWidth: '440px',
    width: '100%',
    overflowX: 'hidden',
  },
  dialogBodyNoOverflow: {
    overflowX: 'hidden',
  },
  dialogContentFlex: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    marginTop: '14px',
    overflowX: 'hidden',
    overflowY: 'auto',
  },
  dialogDescText: {
    color: tokens.colorNeutralForeground2,
  },
  dialogGrid2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  permMatrixHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  permMatrixTitle: {
    fontWeight: 700,
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground1,
  },
  btnGroup: {
    display: 'flex',
    gap: '6px',
  },
  permissionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '10px',
    marginTop: '6px',
    maxHeight: '340px',
    overflowY: 'auto',
    padding: '4px',
  },
  permItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    padding: '10px 12px',
    borderRadius: '8px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1, borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  permItemActive: {
    borderTopColor: '#E51937', borderBottomColor: '#E51937', borderLeftColor: '#E51937', borderRightColor: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.05)',
  },
  permItemDisabled: {
    cursor: 'not-allowed',
  },
  permCheckbox: {
    marginTop: '2px',
    accentColor: '#E51937',
  },
  permTextCol: {
    display: 'flex',
    flexDirection: 'column',
  },
  permItemTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
  },
  permItemDesc: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  formErrorText: {
    color: '#E51937',
    fontWeight: 600,
  },
  dialogActionsRow: {
    marginTop: '20px',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
  },
  dialogCancelBtn: {
    whiteSpace: 'nowrap',
    flexShrink: 0,
    height: '38px',
    padding: '0 16px',
  },
  dialogSubmitBtn: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    fontWeight: 700,
    whiteSpace: 'nowrap',
    flexShrink: 0,
    padding: '0 24px',
    height: '38px',
    borderRadius: tokens.borderRadiusMedium,
    ':hover': {
      backgroundColor: '#C4122C',
      color: '#FFFFFF',
    },
  },
  userBannerRow: {
    padding: '10px 14px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground3,
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  userBannerName: {
    fontWeight: 700,
    display: 'block',
    fontSize: '13px',
    color: tokens.colorNeutralForeground1,
  },
  userBannerMeta: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  successRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    color: '#10B981',
  },
  licenseDescText: {
    color: tokens.colorNeutralForeground2,
    marginBottom: '16px',
    display: 'block',
  },
  dialogColGap14: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  licenseErrText: {
    color: '#E51937',
    fontWeight: 600,
  },
  licenseOkText: {
    color: '#107C41',
    fontWeight: 600,
  },
  licenseActions: {
    paddingTop: '16px',
  },
  tabColumnContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  cardBodyGap14: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  dbStatusGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '14px',
    backgroundColor: tokens.colorNeutralBackground3,
    padding: '16px',
    borderRadius: tokens.borderRadiusMedium,
  },
  mutedBlockCaption: {
    color: tokens.colorNeutralForeground3,
    display: 'block',
  },
  monoBreakText: {
    wordBreak: 'break-all',
    fontFamily: 'monospace',
  },
  blueBoldText: {
    color: '#0078D4',
  },
  greenBoldText: {
    color: '#107C41',
  },
  mutedBoldText: {
    color: tokens.colorNeutralForeground4,
  },
  backupSuccessBanner: {
    padding: '12px 16px',
    borderRadius: '8px',
    backgroundColor: 'rgba(16, 124, 65, 0.1)',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(16, 124, 65, 0.3)', borderBottomColor: 'rgba(16, 124, 65, 0.3)',
    borderLeftColor: 'rgba(16, 124, 65, 0.3)', borderRightColor: 'rgba(16, 124, 65, 0.3)',
    color: '#107C41',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: 600,
  },
  backupDangerBanner: {
    padding: '12px 16px',
    borderRadius: '8px',
    backgroundColor: 'rgba(209, 52, 56, 0.1)',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(209, 52, 56, 0.3)', borderBottomColor: 'rgba(209, 52, 56, 0.3)',
    borderLeftColor: 'rgba(209, 52, 56, 0.3)', borderRightColor: 'rgba(209, 52, 56, 0.3)',
    color: '#D13438',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: 600,
  },
  cardColGap8: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  boldTitle15: {
    fontWeight: 700,
    fontSize: '15px',
  },
  mutedTextLineHeight: {
    color: tokens.colorNeutralForeground2,
    lineHeight: 1.5,
  },
  btnStackCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginTop: '10px',
  },
  primaryBlueBtn: {
    backgroundColor: '#0078D4',
    color: '#FFFFFF',
    fontWeight: 700,
    ':hover': {
      backgroundColor: '#106EBE',
      color: '#FFFFFF',
    },
  },
  btnWrapTop10: {
    marginTop: '10px',
  },
  fullWidthMediumBtn: {
    width: '100%',
    fontWeight: 600,
  },
  restoreAmberBtn: {
    width: '100%',
    borderTopColor: '#D97706', borderBottomColor: '#D97706', borderLeftColor: '#D97706', borderRightColor: '#D97706',
    color: '#D97706',
    fontWeight: 700,
  },
  helpTipBanner: {
    padding: '14px 18px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground3,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
  },
  blueInfoIcon: {
    color: '#0078D4',
    marginTop: '2px',
    flexShrink: 0,
  },
  helpTipText: {
    color: tokens.colorNeutralForeground2,
    lineHeight: 1.6,
  },
  dialogSurface460: {
    maxWidth: '460px',
  },
  dialogContentCol12: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginTop: '8px',
  },
  dialogWarningRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    color: '#D97706',
  },
  icon28: {
    width: '28px',
    height: '28px',
  },
  dialogSafetySnapshotBox: {
    padding: '10px',
    borderRadius: '6px',
    backgroundColor: tokens.colorNeutralBackground3,
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground2,
  },
  dialogActionsTop16: {
    marginTop: '16px',
  },
  dangerRedBtn: {
    backgroundColor: '#D13438',
    color: '#FFFFFF',
    ':hover': {
      backgroundColor: '#A80000',
      color: '#FFFFFF',
    },
  },
});

export const useStyles = useAdminSettingsStyles;
