import { makeStyles, tokens } from '@fluentui/react-components';

export const useInventoryDashboardStyles = makeStyles({
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '16px',
  },
  metricCard: {
    padding: '18px 20px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  sectionCard: {
    padding: '20px 24px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
  },
  quickLinksGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '16px',
  },
  quickLinkCard: {
    padding: '18px 20px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground3,
      borderTopColor: '#E51937', borderBottomColor: '#E51937',
      borderLeftColor: '#E51937', borderRightColor: '#E51937',
      transform: 'translateY(-2px)',
      boxShadow: tokens.shadow8,
    },
  },
  twoColGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(380px, 1fr))',
    gap: '20px',
  },
  movementRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 14px',
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorNeutralBackground3,
    marginBottom: '8px',
  },
  alertItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 14px',
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorNeutralBackground3,
    marginBottom: '8px',
    borderLeftWidth: '3px',
    borderLeftStyle: 'solid',
    borderLeftColor: '#D13438',
  },
  cardSubtitle: {
    color: tokens.colorNeutralForeground2,
    fontWeight: 600,
  },
  cardMetricNum: {
    fontSize: '28px',
    fontWeight: 800,
    marginTop: '8px',
    color: tokens.colorNeutralForeground1,
  },
  cardMetricNumBlue: {
    fontSize: '28px',
    fontWeight: 800,
    marginTop: '8px',
    color: '#0078D4',
  },
  cardMetricNumGreen: {
    fontSize: '28px',
    fontWeight: 800,
    marginTop: '8px',
    color: '#107C41',
  },
  cardMetricNumRed: {
    fontSize: '28px',
    fontWeight: 800,
    marginTop: '8px',
    color: '#E51937',
  },
  cardHint: {
    color: tokens.colorNeutralForeground3,
    marginTop: '4px',
  },
  cursorPointer: {
    cursor: 'pointer',
  },
  quickLinkLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  quickLinkIconGreen: {
    color: '#107C41',
    backgroundColor: 'rgba(16, 124, 65, 0.1)',
    padding: '10px',
    borderRadius: '8px',
    display: 'inline-flex',
  },
  quickLinkIconRed: {
    color: '#D13438',
    backgroundColor: 'rgba(209, 52, 56, 0.1)',
    padding: '10px',
    borderRadius: '8px',
    display: 'inline-flex',
  },
  quickLinkIconBlue: {
    color: '#0078D4',
    backgroundColor: 'rgba(0, 120, 212, 0.1)',
    padding: '10px',
    borderRadius: '8px',
    display: 'inline-flex',
  },
  quickLinkIconBrand: {
    color: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    padding: '10px',
    borderRadius: '8px',
    display: 'inline-flex',
  },
  quickLinkTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    display: 'block',
  },
  quickLinkDesc: {
    color: tokens.colorNeutralForeground2,
  },
  quickLinkChevron: {
    color: tokens.colorNeutralForeground3,
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '14px',
  },
  sectionHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  warningIcon: {
    color: '#D13438',
  },
  sectionTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
  },
  reorderAllBtn: {
    fontWeight: 600,
    color: '#E51937',
  },
  emptyText: {
    padding: '24px',
    textAlign: 'center',
    color: tokens.colorNeutralForeground3,
  },
  alertItemLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  alertItemTitle: {
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
  },
  alertItemSubtitle: {
    color: tokens.colorNeutralForeground2,
  },
  alertItemRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  badgeBold: {
    fontWeight: 700,
  },
  restockBtn: {
    backgroundColor: '#E51937',
    color: '#fff',
    fontSize: '11px',
    padding: '4px 10px',
    height: '26px',
  },
  viewFullBtn: {
    fontWeight: 600,
    color: tokens.colorNeutralForeground2,
  },
  movementItemLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  movementInfo: {
    display: 'flex',
    flexDirection: 'column',
  },
  movementTitle: {
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    fontSize: '13px',
  },
  movementMeta: {
    color: tokens.colorNeutralForeground3,
    fontSize: '11px',
  },
  movementCostIn: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#107C41',
  },
  movementCostOut: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#D13438',
  },
  distributionTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    marginBottom: '16px',
    display: 'block',
  },
  distributionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: '12px',
  },
  catCard: {
    padding: '14px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground3,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  catCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  catCardTitle: {
    fontWeight: 700,
    fontSize: '13px',
    color: tokens.colorNeutralForeground1,
  },
  catCardUnits: {
    color: tokens.colorNeutralForeground2,
    fontWeight: 600,
  },
  catProgressBar: {
    height: '4px',
  },
  catCardFooter: {
    color: tokens.colorNeutralForeground3,
    fontSize: '11px',
  },
  scopeBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '12px',
    padding: '12px 16px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    boxShadow: tokens.shadow2,
  },
  scopeLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  scopeLabel: {
    fontSize: '11px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  scopeTabList: {
    display: 'inline-flex',
    backgroundColor: tokens.colorNeutralBackground3,
    padding: '3px',
    borderRadius: '8px',
    gap: '4px',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
  },
  scopeBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 14px',
    borderRadius: '6px',
    borderTopStyle: 'none', borderBottomStyle: 'none',
    borderLeftStyle: 'none', borderRightStyle: 'none',
    fontFamily: 'inherit',
    cursor: 'pointer',
    fontSize: '12.5px',
    fontWeight: 500,
    color: tokens.colorNeutralForeground2,
    backgroundColor: 'transparent',
    transitionProperty: 'all',
    transitionDuration: '0.12s',
    transitionTimingFunction: 'ease',
  },
  scopeBtnActive: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    fontWeight: 700,
  },
  scopeBtnBadge: {
    fontSize: '10px',
    padding: '1px 6px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
    fontWeight: 700,
  },
  scopeBtnBadgeActive: {
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  icon15Red: {
    width: '15px',
    height: '15px',
    color: '#E51937',
  },
  icon15Blue: {
    width: '15px',
    height: '15px',
    color: '#2563EB',
  },
  icon15Neutral: {
    width: '15px',
    height: '15px',
  },
  scopeSingleChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 12px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground3,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    fontSize: '12.5px',
    fontWeight: 600,
  },
  scopeCountChip: {
    fontSize: '10px',
    padding: '1px 6px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
    fontWeight: 700,
  },
  scopeRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
});

export const useStyles = useInventoryDashboardStyles;
