import { makeStyles, tokens } from '@fluentui/react-components';

export const useStockLedgerStyles = makeStyles({
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '16px',
  },
  metricCard: {
    padding: '18px 20px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  card: {
    borderRadius: tokens.borderRadiusMedium,
    padding: '22px 24px',
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  filterBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
    marginBottom: '16px',
  },
  tableWrapper: {
    overflowX: 'auto',
    width: '100%',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
  },
  th: {
    padding: '12px 14px',
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground2,
    fontSize: '12px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  td: {
    padding: '13px 14px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    fontSize: '13px',
    color: tokens.colorNeutralForeground1,
  },
  tableRow: {
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground3,
    },
  },
  kpiLabel: {
    color: tokens.colorNeutralForeground2,
    fontWeight: 600,
  },
  kpiValueDefault: {
    fontSize: '26px',
    fontWeight: 800,
    marginTop: '6px',
    color: tokens.colorNeutralForeground1,
    display: 'block',
  },
  kpiValueSuccess: {
    fontSize: '26px',
    fontWeight: 800,
    marginTop: '6px',
    color: '#107C41',
    display: 'block',
  },
  kpiValueDanger: {
    fontSize: '26px',
    fontWeight: 800,
    marginTop: '6px',
    color: '#D13438',
    display: 'block',
  },
  kpiValueBrand: {
    fontSize: '26px',
    fontWeight: 800,
    marginTop: '6px',
    color: '#0078D4',
    display: 'block',
  },
  kpiSubtext: {
    color: tokens.colorNeutralForeground3,
    marginTop: '4px',
    display: 'block',
  },
  filterLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  filterIcon: {
    color: '#E51937',
  },
  filterTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
  },
  filterBadge: {
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    color: '#E51937',
  },
  filterRight: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  searchBox: {
    minWidth: '240px',
  },
  timeSelectBox: {
    minWidth: '140px',
  },
  printBtn: {
    backgroundColor: '#E51937',
    color: '#ffffff',
    fontWeight: 600,
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.25)',
    borderRadius: '6px',
  },
  thRight: {
    textAlign: 'right',
  },
  thCenter: {
    textAlign: 'center',
  },
  emptyTd: {
    padding: '40px',
    textAlign: 'center',
    color: tokens.colorNeutralForeground3,
  },
  dateBold: {
    fontWeight: 600,
  },
  mutedCaption: {
    color: tokens.colorNeutralForeground3,
    display: 'block',
  },
  badgeBold: {
    fontWeight: 700,
  },
  productName: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    display: 'block',
  },
  reasonText: {
    fontSize: '13px',
    color: tokens.colorNeutralForeground1,
    display: 'block',
  },
  tdRight: {
    textAlign: 'right',
    fontWeight: 600,
  },
  tdCenter: {
    textAlign: 'center',
  },
  qtyIn: {
    fontWeight: 800,
    color: '#107C41',
    fontSize: '14px',
  },
  qtyOut: {
    fontWeight: 800,
    color: '#D13438',
    fontSize: '14px',
  },
  impactValIn: {
    textAlign: 'right',
    fontWeight: 700,
    color: '#107C41',
  },
  impactValOut: {
    textAlign: 'right',
    fontWeight: 700,
    color: '#D13438',
  },
  actionBtnDelete: {
    width: '30px',
    height: '30px',
    minWidth: '30px',
    padding: 0,
    borderRadius: '6px',
    backgroundColor: 'rgba(209, 52, 56, 0.12)',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(209, 52, 56, 0.25)', borderBottomColor: 'rgba(209, 52, 56, 0.25)',
    borderLeftColor: 'rgba(209, 52, 56, 0.25)', borderRightColor: 'rgba(209, 52, 56, 0.25)',
  },
  iconDelete: {
    color: '#D13438',
  },
  scopeRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '10px',
    paddingBottom: '12px',
    marginBottom: '14px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  scopeLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  scopeLabel: {
    fontSize: '11px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  scopeTabList: {
    display: 'inline-flex',
    backgroundColor: tokens.colorNeutralBackground3,
    padding: '3px',
    borderRadius: '8px',
    gap: '3px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
  },
  scopeBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 12px',
    borderRadius: '6px',
    borderTopStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none', borderRightStyle: 'none',
    backgroundColor: 'transparent',
    color: tokens.colorNeutralForeground2,
    fontWeight: 500,
    fontSize: '12px',
    fontFamily: 'inherit',
    cursor: 'pointer',
    transition: 'all 0.12s ease',
  },
  scopeBtnActive: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    fontWeight: 700,
  },
  scopeBtnBadge: {
    fontSize: '10px',
    padding: '1px 5px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
    fontWeight: 700,
  },
  scopeBtnBadgeActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    color: '#FFFFFF',
  },
  scopeSingleChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 10px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground3,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    fontSize: '12px',
    fontWeight: 600,
  },
  icon14Neutral: {
    width: '14px',
    height: '14px',
  },
  icon14Red: {
    width: '14px',
    height: '14px',
    color: '#E51937',
  },
  icon14Blue: {
    width: '14px',
    height: '14px',
    color: '#2563EB',
  },
});

export const useStyles = useStockLedgerStyles;
