import { makeStyles, tokens } from '@fluentui/react-components';

export const useStockInStyles = makeStyles({
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    width: '100%',
  },
  card: {
    padding: '20px 24px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  cardTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    display: 'block',
    letterSpacing: '-0.2px',
  },
  row1: {
    display: 'grid',
    gridTemplateColumns: '1.1fr 1fr 1fr 1.6fr',
    gap: '14px',
    '@media (max-width: 1100px)': {
      gridTemplateColumns: '1fr 1fr',
    },
    '@media (max-width: 650px)': {
      gridTemplateColumns: '1fr',
    },
  },
  categoryBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    backgroundColor: tokens.colorNeutralBackground3,
    padding: '2px 7px',
    borderRadius: '4px',
    width: 'fit-content',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  productDetailCard: {
    backgroundColor: tokens.colorNeutralBackground2,
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    padding: '14px 18px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  productDetailHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '10px',
  },
  productDetailLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  productThumb: {
    width: '42px',
    height: '42px',
    borderRadius: '8px',
    overflow: 'hidden',
    backgroundColor: tokens.colorNeutralBackground3,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  productDetailGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
    gap: '10px',
    padding: '10px 14px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  detailStatBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  detailStatLabel: {
    fontSize: '10.5px',
    fontWeight: 700,
    textTransform: 'uppercase',
    color: tokens.colorNeutralForeground3,
    letterSpacing: '0.4px',
  },
  detailStatVal: {
    fontSize: '14px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  row2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr 1.2fr 1.6fr',
    gap: '14px',
    alignItems: 'flex-end',
    '@media (max-width: 1024px)': {
      gridTemplateColumns: '1fr 1fr',
    },
  },
  fieldLabel: {
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    color: tokens.colorNeutralForeground2,
    marginBottom: '6px',
    display: 'block',
  },
  lineTotalBox: {
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    padding: '0 14px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: 'rgba(16, 124, 65, 0.12)',
    border: '1.5px solid rgba(16, 124, 65, 0.35)',
    boxSizing: 'border-box',
  },
  lineTotalValue: {
    fontSize: '14px',
    fontWeight: 800,
    color: '#107C41',
  },
  saveBtn: {
    height: '36px',
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: tokens.borderRadiusMedium,
    fontWeight: 700,
    fontSize: '13px',
    border: 'none',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.35)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    whiteSpace: 'nowrap',
    ':hover': {
      backgroundColor: '#C6172E',
    },
  },
  filterBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
  },
  tableWrapper: {
    overflowX: 'auto',
    width: '100%',
    borderRadius: tokens.borderRadiusSmall,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
    fontSize: '12px',
  },
  th: {
    padding: '12px 14px',
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground2,
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    whiteSpace: 'nowrap',
  },
  td: {
    padding: '12px 14px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    color: tokens.colorNeutralForeground1,
    fontSize: '12.5px',
    verticalAlign: 'middle',
  },
  tableRow: {
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground3,
    },
  },

  /* Right-Side Slide-Over Drawer */
  drawerOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    backdropFilter: 'blur(3px)',
    zIndex: 1000,
    display: 'flex',
    justifyContent: 'flex-end',
  },
  drawerPanel: {
    width: '460px',
    maxWidth: '92vw',
    height: '100%',
    backgroundColor: tokens.colorNeutralBackground1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    boxShadow: tokens.shadow64,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    boxSizing: 'border-box',
    animationName: {
      from: { transform: 'translateX(100%)' },
      to: { transform: 'translateX(0)' },
    },
    animationDuration: '0.2s',
    animationTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
  },
  drawerHeader: {
    padding: '20px 24px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: tokens.colorNeutralBackground3,
  },
  drawerBody: {
    padding: '24px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    flex: 1,
  },
  drawerFooter: {
    padding: '16px 24px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
    backgroundColor: tokens.colorNeutralBackground3,
  },

  /* Print Voucher Slip */
  voucherSlip: {
    padding: '24px',
    backgroundColor: '#FFFFFF',
    color: '#000000',
    borderRadius: '8px',
    fontFamily: 'monospace',
  },

  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  productImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  productEmoji: {
    fontSize: '20px',
  },
  productTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  productName: {
    fontSize: '15px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  productMetaRow: {
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground3,
    display: 'flex',
    gap: '10px',
    marginTop: '3px',
    flexWrap: 'wrap',
  },
  skuCode: {
    color: tokens.colorNeutralForeground1,
    fontWeight: 700,
  },
  productActionWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  detailStatValLow: {
    color: '#E51937',
  },
  detailStatValBlue: {
    color: '#0F6CBD',
  },
  detailStatValGreen: {
    color: '#107C41',
  },
  detailStatSubtext: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    fontWeight: 500,
  },
  variantsWrap: {
    paddingTop: '10px',
    borderTopWidth: '1px',
    borderTopStyle: 'dashed',
    borderTopColor: tokens.colorNeutralStroke2,
  },
  variantsHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '8px',
    marginBottom: '8px',
  },
  variantsTitle: {
    fontSize: '11.5px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  variantHeaderActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  variantActionBtn: {
    padding: '3px 9px',
    fontSize: '11px',
    fontWeight: 600,
    borderRadius: '4px',
    backgroundColor: 'rgba(229, 25, 55, 0.08)',
    color: '#E51937',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.25)', borderBottomColor: 'rgba(229, 25, 55, 0.25)',
    borderLeftColor: 'rgba(229, 25, 55, 0.25)', borderRightColor: 'rgba(229, 25, 55, 0.25)',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    ':hover': {
      backgroundColor: 'rgba(229, 25, 55, 0.16)',
    },
  },
  variantActionBtnSubtle: {
    padding: '3px 8px',
    fontSize: '11px',
    fontWeight: 500,
    borderRadius: '4px',
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground2,
    border: 'none',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground4,
    },
  },
  variantsList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  variantCard: {
    padding: '8px 12px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    minWidth: '150px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.03)',
    transition: 'all 0.15s ease',
  },
  variantCardActive: {
    borderTopColor: '#E51937', borderBottomColor: '#E51937',
    borderLeftColor: '#E51937', borderRightColor: '#E51937',
    backgroundColor: '#FFF5F5',
  },
  variantCardTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
  },
  variantLabelBadge: {
    fontWeight: 800,
    fontSize: '13px',
    color: '#E51937',
  },
  variantCardMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    gap: '8px',
  },
  variantMetaItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '3px',
  },
  stockValZero: {
    color: '#DC2626',
    fontWeight: 700,
  },
  stockValNormal: {
    color: '#15803D',
    fontWeight: 700,
  },
  variantInputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    marginTop: '2px',
  },
  variantInputPlus: {
    fontSize: '12px',
    fontWeight: 800,
    color: '#E51937',
  },
  variantNumberInput: {
    width: '64px',
    height: '28px',
    textAlign: 'center',
    fontWeight: 700,
    fontSize: '13px',
    borderRadius: '4px',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    outline: 'none',
    ':focus': {
      borderTopColor: '#E51937', borderBottomColor: '#E51937',
      borderLeftColor: '#E51937', borderRightColor: '#E51937',
    },
  },
  variantUnitBadge: {
    fontSize: '10px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase',
  },
  variantProjected: {
    fontSize: '10.5px',
    color: '#15803D',
    fontWeight: 600,
    textAlign: 'right',
  },
  variantSkuBadge: {
    fontFamily: 'monospace',
    fontSize: '10px',
    color: tokens.colorNeutralForeground3,
    backgroundColor: tokens.colorNeutralBackground3,
    padding: '1px 4px',
    borderRadius: '3px',
  },
  emptyCategoryNotice: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '12px',
    padding: '12px 16px',
    backgroundColor: '#FFFBEB',
    borderRadius: '8px',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#FDE68A', borderBottomColor: '#FDE68A',
    borderLeftColor: '#FDE68A', borderRightColor: '#FDE68A',
    marginTop: '6px',
    marginBottom: '6px',
  },
  emptyCategoryNoticeLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  emptyCategoryNoticeTitle: {
    fontWeight: 700,
    fontSize: '13px',
    color: '#92400e',
  },
  emptyCategoryNoticeSub: {
    fontSize: '12px',
    color: '#b45309',
    marginTop: '2px',
  },
  percentSuffix: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    fontWeight: 700,
    paddingRight: '4px',
  },
  discountPill: {
    fontSize: '11px',
    color: '#107C41',
    marginLeft: '6px',
    fontWeight: 600,
  },
  btnIcon18: {
    width: '18px',
    height: '18px',
  },
  btnIcon16: {
    width: '16px',
    height: '16px',
  },
  searchWrap: {
    minWidth: '280px',
    maxWidth: '420px',
    width: '100%',
  },
  countCaption: {
    color: tokens.colorNeutralForeground3,
    fontWeight: 600,
  },
  thCenter: {
    textAlign: 'center',
  },
  thRight: {
    textAlign: 'right',
  },
  thCheckbox: {
    width: '36px',
    textAlign: 'center',
  },
  thActions: {
    textAlign: 'center',
    minWidth: '100px',
  },
  tdCenter: {
    textAlign: 'center',
  },
  tdRight: {
    textAlign: 'right',
    fontWeight: 600,
  },
  tdRightGreen: {
    textAlign: 'right',
    fontWeight: 700,
    color: '#107C41',
  },
  emptyTd: {
    padding: '36px',
    textAlign: 'center',
    color: tokens.colorNeutralForeground3,
  },
  logProdName: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    display: 'block',
  },
  badgeBold: {
    fontWeight: 700,
  },
  reasonText: {
    color: tokens.colorNeutralForeground1,
  },
  dateTimeText: {
    color: tokens.colorNeutralForeground2,
    fontSize: '12px',
  },
  actionGroup: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
  },
  actionBtnPrint: {
    width: '30px',
    height: '30px',
    minWidth: '30px',
    padding: 0,
    borderRadius: '6px',
    backgroundColor: 'rgba(0, 120, 212, 0.12)',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(0, 120, 212, 0.25)', borderBottomColor: 'rgba(0, 120, 212, 0.25)',
    borderLeftColor: 'rgba(0, 120, 212, 0.25)', borderRightColor: 'rgba(0, 120, 212, 0.25)',
  },
  actionBtnEdit: {
    width: '30px',
    height: '30px',
    minWidth: '30px',
    padding: 0,
    borderRadius: '6px',
    backgroundColor: 'rgba(16, 124, 65, 0.12)',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(16, 124, 65, 0.25)', borderBottomColor: 'rgba(16, 124, 65, 0.25)',
    borderLeftColor: 'rgba(16, 124, 65, 0.25)', borderRightColor: 'rgba(16, 124, 65, 0.25)',
  },
  actionBtnDelete: {
    width: '30px',
    height: '30px',
    minWidth: '30px',
    padding: 0,
    borderRadius: '6px',
    backgroundColor: 'rgba(209, 52, 56, 0.12)',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(209, 52, 56, 0.25)', borderBottomColor: 'rgba(209, 52, 56, 0.25)',
    borderLeftColor: 'rgba(209, 52, 56, 0.25)', borderRightColor: 'rgba(209, 52, 56, 0.25)',
  },
  iconPrint: {
    color: '#0078D4',
    width: '16px',
    height: '16px',
  },
  iconEdit: {
    color: '#107C41',
    width: '16px',
    height: '16px',
  },
  iconDelete: {
    color: '#D13438',
    width: '16px',
    height: '16px',
  },
  drawerHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  drawerHeaderBadge: {
    backgroundColor: 'rgba(16, 124, 65, 0.12)',
    color: '#107C41',
    padding: '8px',
    borderRadius: '8px',
    display: 'inline-flex',
  },
  drawerHeaderTitle: {
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    display: 'block',
  },
  drawerHeaderSub: {
    color: tokens.colorNeutralForeground3,
  },
  iconBtn28: {
    minWidth: '28px',
    width: '28px',
    height: '28px',
    padding: 0,
  },
  grid2Col: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  drawerCancelBtn: {
    borderRadius: '8px',
  },
  drawerUpdateBtn: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: '8px',
    fontWeight: 700,
    borderTopStyle: 'none', borderBottomStyle: 'none',
    borderLeftStyle: 'none', borderRightStyle: 'none',
    ':hover': {
      backgroundColor: '#C6172E',
    },
  },
  printDialogSurface: {
    borderRadius: '14px',
    width: '680px',
    maxWidth: '96vw',
    padding: '24px',
    boxSizing: 'border-box',
  },
  printHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  printModalTitle: {
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    margin: 0,
    fontSize: '18px',
  },
  iconBtn32: {
    minWidth: '32px',
    width: '32px',
    height: '32px',
    padding: 0,
  },
  printSheet: {
    backgroundColor: '#FFFFFF',
    color: '#111827',
    padding: '20px 22px',
    borderRadius: '10px',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#E2E8F0', borderBottomColor: '#E2E8F0',
    borderLeftColor: '#E2E8F0', borderRightColor: '#E2E8F0',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.06)',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  invoiceTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: '2px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#E51937',
    paddingBottom: '12px',
  },
  invoiceBrandWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  logoBox: {
    width: '36px',
    height: '36px',
    borderRadius: '6px',
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 900,
    fontSize: '15px',
  },
  brandName: {
    fontWeight: 800,
    fontSize: '16px',
    color: '#111827',
    lineHeight: 1.1,
  },
  brandSub: {
    fontSize: '9.5px',
    color: '#64748B',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  invHeaderRight: {
    textAlign: 'right',
  },
  invTitle: {
    fontSize: '14px',
    fontWeight: 800,
    color: '#E51937',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  invMetaText: {
    fontSize: '10.5px',
    color: '#475569',
    marginTop: '2px',
  },
  partiesGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  partyCard: {
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#E2E8F0', borderBottomColor: '#E2E8F0',
    borderLeftColor: '#E2E8F0', borderRightColor: '#E2E8F0',
    borderRadius: '8px',
    padding: '10px 14px',
    backgroundColor: '#F8FAFC',
  },
  supplierTag: {
    fontSize: '9.5px',
    fontWeight: 800,
    color: '#E51937',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    marginBottom: '4px',
  },
  storeTag: {
    fontSize: '9.5px',
    fontWeight: 800,
    color: '#15803D',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    marginBottom: '4px',
  },
  partyName: {
    fontSize: '13.5px',
    fontWeight: 800,
    color: '#0F172A',
    marginBottom: '3px',
  },
  partyDetail: {
    fontSize: '11px',
    color: '#475569',
    lineHeight: 1.35,
  },
  vendorBalanceTag: {
    marginTop: '8px',
    display: 'inline-block',
    backgroundColor: '#FEF2F2',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#FECACA', borderBottomColor: '#FECACA',
    borderLeftColor: '#FECACA', borderRightColor: '#FECACA',
    borderRadius: '4px',
    padding: '3px 8px',
    fontSize: '11px',
    fontWeight: 700,
    color: '#991B1B',
  },
  verifiedTag: {
    marginTop: '8px',
    fontSize: '10.5px',
    color: '#15803D',
    fontWeight: 700,
  },
  slipTable: {
    width: '100%',
    borderCollapse: 'collapse',
    marginTop: '4px',
  },
  slipTrHeader: {
    backgroundColor: '#F1F5F9',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: '#CBD5E1',
    borderBottomWidth: '2px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#94A3B8',
  },
  slipTh: {
    padding: '7px 10px',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    color: '#334155',
  },
  slipThNum: {
    padding: '7px 10px',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    textAlign: 'center',
    color: '#334155',
    width: '32px',
  },
  slipThLeft: {
    padding: '7px 10px',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    textAlign: 'left',
    color: '#334155',
  },
  slipThRate: {
    padding: '7px 10px',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    textAlign: 'right',
    color: '#334155',
    width: '90px',
  },
  slipThQty: {
    padding: '7px 10px',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    textAlign: 'center',
    color: '#334155',
    width: '80px',
  },
  slipThDiscount: {
    padding: '7px 10px',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    textAlign: 'right',
    color: '#334155',
    width: '70px',
  },
  slipThTotal: {
    padding: '7px 10px',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase',
    textAlign: 'right',
    color: '#334155',
    width: '110px',
  },
  slipTdNum: {
    padding: '8px 10px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#E2E8F0',
    fontSize: '11px',
    textAlign: 'center',
    color: '#64748B',
  },
  slipTdDesc: {
    padding: '8px 10px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#E2E8F0',
    fontSize: '11.5px',
  },
  slipProdTitle: {
    fontWeight: 700,
    color: '#0F172A',
  },
  slipProdNote: {
    fontSize: '10px',
    color: '#64748B',
    marginTop: '2px',
  },
  slipTdRate: {
    padding: '8px 10px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#E2E8F0',
    fontSize: '11.5px',
    textAlign: 'right',
    fontWeight: 600,
  },
  slipTdQty: {
    padding: '8px 10px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#E2E8F0',
    fontSize: '11.5px',
    textAlign: 'center',
    fontWeight: 800,
    color: '#15803D',
  },
  slipTdDiscount: {
    padding: '8px 10px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#E2E8F0',
    fontSize: '11.5px',
    textAlign: 'right',
    color: '#64748B',
  },
  slipTdTotal: {
    padding: '8px 10px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#E2E8F0',
    fontSize: '11.5px',
    textAlign: 'right',
    fontWeight: 800,
    color: '#0F172A',
  },
  calcWrap: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: '4px',
  },
  calcCard: {
    width: '280px',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#E2E8F0', borderBottomColor: '#E2E8F0',
    borderLeftColor: '#E2E8F0', borderRightColor: '#E2E8F0',
    borderRadius: '8px',
    padding: '10px 14px',
    backgroundColor: '#F8FAFC',
  },
  calcRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11.5px',
    color: '#475569',
    marginBottom: '4px',
  },
  calcGrossVal: {
    fontWeight: 600,
  },
  calcDiscountRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11.5px',
    color: '#15803D',
    marginBottom: '4px',
  },
  calcInvoiceTotalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '12.5px',
    fontWeight: 800,
    color: '#0F172A',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: '#0F172A',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: '#0F172A',
    padding: '5px 0',
    margin: '5px 0',
  },
  calcInvoiceTotalVal: {
    color: '#E51937',
  },
  calcPrevRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11px',
    color: '#475569',
    marginBottom: '3px',
  },
  calcAddedRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11px',
    color: '#15803D',
    marginBottom: '4px',
  },
  balanceDueBox: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11.5px',
    fontWeight: 800,
    color: '#991B1B',
    backgroundColor: '#FEF2F2',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: '#FECACA', borderBottomColor: '#FECACA',
    borderLeftColor: '#FECACA', borderRightColor: '#FECACA',
    borderRadius: '4px',
    padding: '4px 6px',
    marginTop: '4px',
  },
  signaturesRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '14px',
    paddingTop: '10px',
    borderTopWidth: '1px',
    borderTopStyle: 'dashed',
    borderTopColor: '#CBD5E1',
    fontSize: '10px',
    color: '#64748B',
  },
  signatureBlock: {
    textAlign: 'center',
    width: '130px',
  },
  signatureLine: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: '#64748B',
    marginBottom: '3px',
  },
  modalActionsBar: {
    marginTop: '18px',
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  modalCloseBtn: {
    height: '38px',
    padding: '0 20px',
    borderRadius: '8px',
    fontWeight: 600,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground1,
    cursor: 'pointer',
  },
  modalPrintBtn: {
    height: '38px',
    padding: '0 22px',
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    fontWeight: 700,
    borderRadius: '8px',
    borderTopStyle: 'none', borderBottomStyle: 'none',
    borderLeftStyle: 'none', borderRightStyle: 'none',
    whiteSpace: 'nowrap',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.35)',
    ':hover': {
      backgroundColor: '#C6172E',
    },
  },
  scopeRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '10px',
  },
  scopeLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  scopeLabel: {
    fontSize: '11px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground3,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  scopeTabList: {
    display: 'inline-flex',
    backgroundColor: tokens.colorNeutralBackground3,
    padding: '3px',
    borderRadius: '8px',
    gap: '3px',
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
  },
  scopeBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 12px',
    borderRadius: '6px',
    borderTopStyle: 'none', borderBottomStyle: 'none',
    borderLeftStyle: 'none', borderRightStyle: 'none',
    fontFamily: 'inherit',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 500,
    color: tokens.colorNeutralForeground2,
    backgroundColor: 'transparent',
    transitionProperty: 'all',
    transitionDuration: '0.12s',
    transitionTimingFunction: 'ease',
  },
  scopeBtnActive: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    fontWeight: 700,
  },
  scopeBtnBadge: {
    fontSize: '10px',
    padding: '1px 5px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground1,
    fontWeight: 700,
  },
  scopeBtnBadgeActive: {
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  scopeSingleChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '12px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground1,
    padding: '4px 10px',
    borderRadius: '6px',
    backgroundColor: tokens.colorNeutralBackground3,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
  },
  icon14Red: {
    width: '14px',
    height: '14px',
    color: '#E51937',
  },
  icon14Blue: {
    width: '14px',
    height: '14px',
    color: '#2563EB',
  },
  icon14Neutral: {
    width: '14px',
    height: '14px',
  },
  icon14Grey: {
    width: '14px',
    height: '14px',
    color: '#94A3B8',
  },
  icon12Blue: {
    width: '12px',
    height: '12px',
    color: '#2563EB',
  },
  icon22Orange: {
    width: '22px',
    height: '22px',
    color: '#D97706',
    flexShrink: 0,
  },
  icon24Grey: {
    width: '24px',
    height: '24px',
    color: '#94A3B8',
  },
  metaBadgeInline: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
  },
  variantBtnInline: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
  },
  historyHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '12px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    paddingBottom: '10px',
  },
  minWidth170: {
    minWidth: '170px',
  },
  filterActionsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  deleteDangerBtn: {
    backgroundColor: '#D13438',
    color: '#FFFFFF',
    fontWeight: 600,
  },
  productCellStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  verifiedTagFlex: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
});

export const useStyles = useStockInStyles;
