import { makeStyles, tokens } from '@fluentui/react-components';

export const useVendorsStyles = makeStyles({
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    width: '100%',
  },
  card: {
    padding: '20px 24px',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    borderTopWidth: '1px', borderBottomWidth: '1px',
    borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid',
    borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    display: 'block',
    letterSpacing: '-0.2px',
  },
  cardForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  fieldLabel: {
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    color: tokens.colorNeutralForeground2,
    marginBottom: '6px',
    display: 'block',
  },
  row1: {
    display: 'grid',
    gridTemplateColumns: '1.5fr 1fr 1fr',
    gap: '16px',
    '@media (max-width: 900px)': {
      gridTemplateColumns: '1fr',
    },
  },
  row2: {
    display: 'grid',
    gridTemplateColumns: '1.2fr 1fr 2fr auto',
    gap: '16px',
    alignItems: 'flex-end',
    '@media (max-width: 1000px)': {
      gridTemplateColumns: '1fr 1fr',
    },
    '@media (max-width: 600px)': {
      gridTemplateColumns: '1fr',
    },
  },
  saveBtn: {
    height: '38px',
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    borderRadius: tokens.borderRadiusMedium,
    fontWeight: 700,
    fontSize: '13px',
    border: 'none',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.35)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    padding: '0 22px',
    whiteSpace: 'nowrap',
    transition: 'all 0.15s ease',
    ':hover': {
      backgroundColor: '#C6172E',
    },
  },
  filterBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
  },
  tableWrapper: {
    overflowX: 'auto',
    width: '100%',
    borderRadius: tokens.borderRadiusSmall,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
    fontSize: '12px',
  },
  th: {
    padding: '12px 14px',
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground2,
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    whiteSpace: 'nowrap',
  },
  td: {
    padding: '14px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
    color: tokens.colorNeutralForeground1,
    verticalAlign: 'middle',
  },
  tableRow: {
    transition: 'background-color 0.15s ease',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  // Slide-over Drawer styles
  drawerOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    backdropFilter: 'blur(3px)',
    zIndex: 1000,
    display: 'flex',
    justifyContent: 'flex-end',
  },
  drawerPanel: {
    width: '460px',
    maxWidth: '92vw',
    height: '100%',
    backgroundColor: tokens.colorNeutralBackground1,
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: tokens.colorNeutralStroke1,
    boxShadow: tokens.shadow64,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    boxSizing: 'border-box',
    animationName: {
      from: { transform: 'translateX(100%)' },
      to: { transform: 'translateX(0)' },
    },
    animationDuration: '0.2s',
    animationTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
  },
  drawerHeader: {
    padding: '20px 24px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke1,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: tokens.colorNeutralBackground3,
  },
  drawerBody: {
    padding: '24px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    flex: 1,
  },
  drawerFooter: {
    padding: '16px 24px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1,
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '10px',
    backgroundColor: tokens.colorNeutralBackground3,
  },
  saveBtnIcon: {
    width: '16px',
    height: '16px',
  },
  directoryTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
  },
  searchBoxContainer: {
    minWidth: '280px',
    maxWidth: '420px',
    width: '100%',
  },
  totalCountCaption: {
    color: tokens.colorNeutralForeground3,
    fontWeight: 600,
  },
  thSelect: {
    width: '36px',
    textAlign: 'center',
  },
  thRight: {
    textAlign: 'right',
  },
  thCenter: {
    textAlign: 'center',
    minWidth: '100px',
  },
  emptyTd: {
    padding: '36px',
    textAlign: 'center',
    color: tokens.colorNeutralForeground3,
  },
  tdCenter: {
    textAlign: 'center',
  },
  vendorNameCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  vendorNameText: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    fontSize: '13px',
  },
  vendorRepText: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  badgeBold: {
    fontWeight: 600,
  },
  phoneText: {
    color: tokens.colorNeutralForeground1,
    fontWeight: 500,
  },
  secondaryText: {
    color: tokens.colorNeutralForeground2,
    fontSize: '12px',
  },
  tdBalanceDebit: {
    textAlign: 'right',
    fontWeight: 700,
    color: '#D13438',
  },
  tdBalanceCredit: {
    textAlign: 'right',
    fontWeight: 700,
    color: '#107C41',
  },
  actionBtnsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
  },
  actionBtnStockIn: {
    width: '30px',
    height: '30px',
    minWidth: '30px',
    padding: 0,
    borderRadius: '6px',
    backgroundColor: 'rgba(16, 124, 65, 0.12)',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(16, 124, 65, 0.25)', borderBottomColor: 'rgba(16, 124, 65, 0.25)', borderLeftColor: 'rgba(16, 124, 65, 0.25)', borderRightColor: 'rgba(16, 124, 65, 0.25)',
  },
  actionBtnPrint: {
    width: '30px',
    height: '30px',
    minWidth: '30px',
    padding: 0,
    borderRadius: '6px',
    backgroundColor: 'rgba(0, 120, 212, 0.12)',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(0, 120, 212, 0.25)', borderBottomColor: 'rgba(0, 120, 212, 0.25)', borderLeftColor: 'rgba(0, 120, 212, 0.25)', borderRightColor: 'rgba(0, 120, 212, 0.25)',
  },
  actionBtnEdit: {
    width: '30px',
    height: '30px',
    minWidth: '30px',
    padding: 0,
    borderRadius: '6px',
    backgroundColor: 'rgba(229, 25, 55, 0.12)',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(229, 25, 55, 0.25)', borderBottomColor: 'rgba(229, 25, 55, 0.25)', borderLeftColor: 'rgba(229, 25, 55, 0.25)', borderRightColor: 'rgba(229, 25, 55, 0.25)',
  },
  actionBtnDelete: {
    width: '30px',
    height: '30px',
    minWidth: '30px',
    padding: 0,
    borderRadius: '6px',
    backgroundColor: 'rgba(209, 52, 56, 0.12)',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(209, 52, 56, 0.25)', borderBottomColor: 'rgba(209, 52, 56, 0.25)', borderLeftColor: 'rgba(209, 52, 56, 0.25)', borderRightColor: 'rgba(209, 52, 56, 0.25)',
  },
  iconStockIn: {
    color: '#107C41',
    width: '16px',
    height: '16px',
  },
  iconPrint: {
    color: '#0078D4',
    width: '16px',
    height: '16px',
  },
  iconEdit: {
    color: '#E51937',
    width: '16px',
    height: '16px',
  },
  iconDelete: {
    color: '#D13438',
    width: '16px',
    height: '16px',
  },
  drawerHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  drawerTitle: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
    margin: 0,
  },
  drawerCloseBtn: {
    minWidth: 'auto',
    padding: '6px',
  },
  drawerForm: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    overflow: 'hidden',
  },
  drawerSaveBtn: {
    backgroundColor: '#E51937',
  },
  printModalSurface: {
    maxWidth: '480px',
    width: '92vw',
    borderRadius: '12px',
    padding: '24px',
  },
  printModalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  printModalTitle: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 800,
  },
  printModalCloseBtn: {
    minWidth: 'auto',
    padding: '4px',
  },
  slipContainer: {
    backgroundColor: '#FFFFFF',
    color: '#000000',
    padding: '24px',
    borderRadius: '8px',
    fontFamily: 'monospace',
    fontSize: '12px',
    lineHeight: '1.6',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
  },
  slipHeader: {
    textAlign: 'center',
    borderBottomTopWidth: 0,
    borderBottomWidth: '1px',
    borderBottomStyle: 'dashed',
    borderBottomColor: '#000000',
    paddingBottom: '10px',
    marginBottom: '12px',
  },
  slipStoreTitle: {
    fontWeight: 700,
    fontSize: '16px',
    letterSpacing: '1px',
  },
  slipDateText: {
    fontSize: '10px',
    color: '#555555',
  },
  slipSection: {
    marginBottom: '12px',
  },
  slipRowBetween: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  slipBoldLabel: {
    fontWeight: 700,
  },
  slipInvoicesBox: {
    margin: '10px 0',
    borderTopWidth: '1px',
    borderTopStyle: 'dashed',
    borderTopColor: '#BBBBBB',
    borderBottomWidth: '1px',
    borderBottomStyle: 'dashed',
    borderBottomColor: '#BBBBBB',
    padding: '8px 0',
  },
  slipInvoicesHeader: {
    fontWeight: 700,
    fontSize: '11px',
    marginBottom: '4px',
    textTransform: 'uppercase',
    color: '#333333',
  },
  slipInvoiceRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11px',
    padding: '2px 0',
  },
  slipInvoiceCost: {
    fontWeight: 600,
  },
  slipBalanceBox: {
    borderTopWidth: '1px',
    borderTopStyle: 'dashed',
    borderTopColor: '#000000',
    paddingTop: '10px',
    marginBottom: '10px',
  },
  slipBalanceRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontWeight: 700,
    fontSize: '14px',
  },
  slipFooterSignature: {
    textAlign: 'center',
    fontSize: '10px',
    color: '#777777',
    marginTop: '16px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: '#DDDDDD',
    paddingTop: '8px',
  },
  printModalActions: {
    marginTop: '20px',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
  },
  printModalCloseActionBtn: {
    height: '38px',
    padding: '0 20px',
    borderRadius: '6px',
  },
  printModalConfirmBtn: {
    height: '38px',
    padding: '0 22px',
    borderRadius: '6px',
    backgroundColor: '#0078D4',
    whiteSpace: 'nowrap',
    fontWeight: 600,
  },
});

export const useStyles = useVendorsStyles;
