import { makeStyles, tokens } from '@fluentui/react-components';

export const useCustomersStyles = makeStyles({
  container: {
    padding: '24px 28px',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    backgroundColor: tokens.colorNeutralBackground2,
    overflowY: 'auto',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '12px',
  },
  headerLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  title: {
    fontSize: '22px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  subtitle: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  primaryBtn: {
    backgroundColor: '#E51937',
    color: '#FFFFFF',
    fontWeight: 700,
    border: 'none',
    boxShadow: '0 2px 8px rgba(229, 25, 55, 0.35)',
    ':hover': {
      backgroundColor: '#be123c',
      color: '#FFFFFF',
    },
  },
  refundHeaderBtn: {
    backgroundColor: '#2563EB',
    color: '#FFFFFF',
    fontWeight: 700,
    border: 'none',
    boxShadow: '0 2px 8px rgba(37, 99, 235, 0.35)',
    ':hover': {
      backgroundColor: '#1d4ed8',
      color: '#FFFFFF',
    },
  },

  // Stats Grid
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '14px',
  },
  statCard: {
    padding: '16px 20px',
    borderRadius: '10px',
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    boxShadow: tokens.shadow2,
  },
  statIconBox: {
    width: '42px',
    height: '42px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  statContent: {
    display: 'flex',
    flexDirection: 'column',
  },
  statValue: {
    fontSize: '20px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
  },
  statLabel: {
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground3,
    fontWeight: 600,
  },

  // Card Panel
  card: {
    padding: '20px 24px',
    borderRadius: '12px',
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    boxShadow: tokens.shadow2,
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  filterBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '12px',
  },
  searchBox: {
    width: '360px',
    '@media (max-width: 600px)': {
      width: '100%',
    },
  },

  // Table
  tableContainer: {
    width: '100%',
    overflowX: 'auto',
    borderRadius: '8px',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
    fontSize: '13px',
  },
  th: {
    padding: '12px 16px',
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground2,
    fontWeight: 700,
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  td: {
    padding: '12px 16px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke3}`,
    color: tokens.colorNeutralForeground1,
    verticalAlign: 'middle',
  },
  tr: {
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground2,
    },
  },

  // Action Buttons in Table
  actionGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  actionBtn: {
    width: '30px',
    height: '30px',
    borderRadius: '6px',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: tokens.colorNeutralForeground2,
    transition: 'all 0.15s ease',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground3,
      color: tokens.colorNeutralForeground1,
    },
  },
  refundActionBtn: {
    width: '30px',
    height: '30px',
    borderRadius: '6px',
    border: '1px solid rgba(37, 99, 235, 0.3)',
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: '#2563EB',
    transition: 'all 0.15s ease',
    ':hover': {
      backgroundColor: '#2563EB',
      color: '#FFFFFF',
    },
  },

  // Modal / Dialog Details
  dialogSurface: {
    maxWidth: '720px',
    width: '100%',
  },
  orderItemRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 14px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground2,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    marginBottom: '8px',
    gap: '12px',
  },
  qtyStepper: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  stepperBtn: {
    width: '28px',
    height: '28px',
    borderRadius: '6px',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
    cursor: 'pointer',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperInput: {
    width: '44px',
    textAlign: 'center',
    height: '28px',
    borderRadius: '6px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke1, borderBottomColor: tokens.colorNeutralStroke1,
    borderLeftColor: tokens.colorNeutralStroke1, borderRightColor: tokens.colorNeutralStroke1,
    fontWeight: 700,
  },
  headerLeftRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  headerIconRed: {
    color: '#E51937',
    width: '28px',
    height: '28px',
  },
  statIconBoxRed: {
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    color: '#E51937',
  },
  statIconBoxAmber: {
    backgroundColor: 'rgba(217, 119, 6, 0.12)',
    color: '#D97706',
  },
  statIconBoxBlue: {
    backgroundColor: 'rgba(37, 99, 235, 0.12)',
    color: '#2563EB',
  },
  icon22: {
    width: '22px',
    height: '22px',
  },
  icon16: {
    width: '16px',
    height: '16px',
  },
  icon13: {
    width: '13px',
    height: '13px',
  },
  icon15: {
    width: '15px',
    height: '15px',
  },
  viewTabRow: {
    display: 'flex',
    gap: '10px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: tokens.colorNeutralStroke2,
    paddingBottom: '8px',
  },
  viewTabBtn: {
    padding: '8px 18px',
    borderRadius: '6px',
    fontWeight: 700,
    fontSize: '13px',
    cursor: 'pointer',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    backgroundColor: 'transparent',
    color: tokens.colorNeutralForeground2,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
  },
  viewTabBtnActiveCustomers: {
    borderTopWidth: '2px', borderBottomWidth: '2px', borderLeftWidth: '2px', borderRightWidth: '2px',
    borderTopColor: '#E51937', borderBottomColor: '#E51937', borderLeftColor: '#E51937', borderRightColor: '#E51937',
    backgroundColor: 'rgba(229, 25, 55, 0.1)',
    color: '#E51937',
  },
  viewTabBtnActiveRefunds: {
    borderTopWidth: '2px', borderBottomWidth: '2px', borderLeftWidth: '2px', borderRightWidth: '2px',
    borderTopColor: '#2563EB', borderBottomColor: '#2563EB', borderLeftColor: '#2563EB', borderRightColor: '#2563EB',
    backgroundColor: 'rgba(37, 99, 235, 0.1)',
    color: '#2563EB',
  },
  showingCountText: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
    fontWeight: 600,
  },
  thRight: {
    textAlign: 'right',
  },
  emptyTableTd: {
    padding: '36px',
    textAlign: 'center',
    color: tokens.colorNeutralForeground3,
  },
  customerNameCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  customerAvatar: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    backgroundColor: tokens.colorNeutralBackground3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: '11px',
  },
  customerNameBold: {
    fontWeight: 700,
  },
  phoneCell: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    color: tokens.colorNeutralForeground2,
  },
  mutedNone: {
    color: tokens.colorNeutralForeground4,
  },
  mutedText: {
    color: tokens.colorNeutralForeground2,
  },
  weight600: {
    fontWeight: 600,
  },
  blueSpentText: {
    fontWeight: 700,
    color: '#0078D4',
  },
  amberDebtText: {
    fontWeight: 700,
    color: '#D97706',
  },
  greenZeroText: {
    color: '#107C41',
    fontWeight: 600,
  },
  actionGroupRight: {
    justifyContent: 'flex-end',
  },
  tableSubtitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground1,
  },
  tableSubCount: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  dateText: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground2,
  },
  orderIdBlue: {
    fontWeight: 700,
    color: '#2563EB',
  },
  itemsCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  itemLineText: {
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground1,
  },
  refundAmountDanger: {
    fontWeight: 800,
    color: '#D13438',
    fontSize: '14px',
  },
  dialogSurface480: {
    maxWidth: '480px',
  },
  dialogBodyCol14: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    marginTop: '12px',
  },
  grid2Col: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  regularNoticeBox: {
    padding: '8px 12px',
    borderRadius: '6px',
    backgroundColor: tokens.colorNeutralBackground3,
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground2,
  },
  dialogActionsTop20: {
    marginTop: '20px',
  },
  dialogTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  blueIcon: {
    color: '#2563EB',
  },
  greenIcon: {
    color: '#107C41',
  },
  dialogBodyCol16: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    marginTop: '10px',
  },
  refundSuccessMsgBox: {
    padding: '12px 16px',
    borderRadius: '8px',
    backgroundColor: 'rgba(16, 124, 65, 0.12)',
    color: '#107C41',
    fontWeight: 700,
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(16, 124, 65, 0.3)', borderBottomColor: 'rgba(16, 124, 65, 0.3)',
    borderLeftColor: 'rgba(16, 124, 65, 0.3)', borderRightColor: 'rgba(16, 124, 65, 0.3)',
  },
  stepHeading: {
    marginBottom: '8px',
    fontSize: '12px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
  },
  orderScrollList: {
    marginTop: '12px',
    maxHeight: '300px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  emptyOrdersBox: {
    padding: '20px',
    textAlign: 'center',
    color: tokens.colorNeutralForeground3,
    fontSize: '12px',
  },
  orderSelectCard: {
    padding: '12px 16px',
    borderRadius: '8px',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: tokens.colorNeutralStroke2, borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2, borderRightColor: tokens.colorNeutralStroke2,
    backgroundColor: tokens.colorNeutralBackground1,
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    transition: 'all 0.15s ease',
  },
  orderCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  orderIdTitle: {
    fontWeight: 800,
    color: '#2563EB',
    fontSize: '13px',
  },
  orderMetaSub: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground2,
    marginTop: '2px',
  },
  orderLinesSub: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  textRight: {
    textAlign: 'right',
  },
  orderTotalBold: {
    fontSize: '14px',
    fontWeight: 800,
    color: tokens.colorNeutralForeground1,
    display: 'block',
  },
  marginTop4: {
    marginTop: '4px',
  },
  selectedOrderBanner: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 14px',
    borderRadius: '8px',
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    borderTopWidth: '1px', borderBottomWidth: '1px', borderLeftWidth: '1px', borderRightWidth: '1px',
    borderTopStyle: 'solid', borderBottomStyle: 'solid', borderLeftStyle: 'solid', borderRightStyle: 'solid',
    borderTopColor: 'rgba(37, 99, 235, 0.2)', borderBottomColor: 'rgba(37, 99, 235, 0.2)',
    borderLeftColor: 'rgba(37, 99, 235, 0.2)', borderRightColor: 'rgba(37, 99, 235, 0.2)',
    marginBottom: '14px',
  },
  orderCustomerMeta: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground2,
    marginLeft: '8px',
  },
  changeOrderBtn: {
    fontSize: '11px',
    color: '#E51937',
    fontWeight: 700,
    backgroundColor: 'transparent',
    borderTopStyle: 'none', borderBottomStyle: 'none', borderLeftStyle: 'none', borderRightStyle: 'none',
    cursor: 'pointer',
    textDecorationLine: 'underline',
  },
  step2Heading: {
    fontSize: '12px',
    fontWeight: 700,
    color: tokens.colorNeutralForeground2,
    marginBottom: '8px',
  },
  itemsScrollBox: {
    maxHeight: '240px',
    overflowY: 'auto',
  },
  flex1: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '0%',
  },
  itemName13: {
    fontWeight: 700,
    fontSize: '13px',
    display: 'block',
  },
  itemMeta11: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
  },
  stepperLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: tokens.colorNeutralForeground3,
  },
  returnItemCostCol: {
    minWidth: '90px',
    textAlign: 'right',
  },
  returnCostActive: {
    fontWeight: 700,
    color: '#D13438',
  },
  returnCostInactive: {
    fontWeight: 700,
    color: tokens.colorNeutralForeground3,
  },
  reasonGrid: {
    display: 'grid',
    gridTemplateColumns: '1.2fr 1fr',
    gap: '12px',
    marginTop: '12px',
  },
  summaryBanner: {
    padding: '12px 16px',
    borderRadius: '8px',
    backgroundColor: tokens.colorNeutralBackground3,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '10px',
  },
  summaryLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  summaryNoticeText: {
    fontSize: '11.5px',
    color: tokens.colorNeutralForeground2,
  },
  totalRefundLabel: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground3,
    display: 'block',
  },
  totalRefundVal: {
    fontSize: '18px',
    fontWeight: 800,
    color: '#D13438',
  },
  dialogActionsTop16: {
    marginTop: '16px',
  },
});

export const useStyles = useCustomersStyles;
